* ABME





In this revision, the figures have been much improved, which illustrate the concept of the proposed robotic drill and navigation system, as well as its setting in for a lab-based validation task. However, the manuscript still need a major revision to improve in the following aspects:
  - In the proposed clinical setting, the global frame-of-reference has to be setup by fixing a tracking unit on the patient's femur using bone pins (page 27, Fig.9). The authors has to make justifications for this setup, and provide/cite references to support the feasibility of this routine.
  - In addition, because the accuracy of the proposed tracking and navigation system clearly depends on this global frame-of-reference, further details are expected to be included. For example:
    - 1) how to determine the position of setting up the global frame-of-reference on the femur, and
    - 2) how the pre-operative 3D bone model from the CT scans (or any virtual objects) can be accurately register relative to this global frame-of-reference.
  - 7DOF system is misleading. Throughout the paper, only the performance of a planar 3-joints robot actuated by 1 tendon is demonstrated.
  - The video can be further improved by demonstrating the synchronization between the real robot motion and the virtual model in the navigation system.
  - The organization of the results section and discussion section (section 6 and 7) has to be improved. Section 5.1, 5.2 and the first paragraph of 5.3 can be placed under a section describing the experimentation method; The second paragraph of 5.3 and section 6 can be put in a "Results and discussion" section. 
  - Table 1 for comparison purpose should not be placed in the conclusion section. 
  - There are still typos and typesetting issues (e.g. double white space).
  - For each comment in the response letter, the authors have to state where each amendment has been made. It is difficult to trace whether the revisions have been properly made in the manuscript. There are also many subjective answers without evidence (e.g. in Response 4).
 


* IEEE RAM
** IEEE-RAM Review Form 
*** Details of the Submission
Title  	RollerBall: a mobile colon screening robot
Authors 	Norton, Joseph* (194386), Hood, Adrian (194437), Neville, Anne (153145), Jayne, David (153147), Boyle, Jordan Hylke (154050), Alazmani, Ali (123952), Culmer, Peter Robert (123932)
Submission number and version 	16-0078 (Submission ID 16-0078), Version 1
Review requested by 	Merrifield, Robert (Guest Editor (Guest Editor), 160970)
Under review for publication as 	Paper for special issue on Surgical Robot Challenge
Review ID 	8845
Reviewer 	Ka-Wai Kwok (127660)
*** Some Review Guidelines
Articles appearing in the magazine should be of general interest to readers of the magazine which is primarily society members: not only academics but also students and industry practioners. The maximum length for an article is 8 magazine pages but the mapping from submission format to magazine layout makes this hard to judge. A rule of thumb is that 8 pages in TRO double column format is about 8 magazine pages, but mileage will vary.

It is important to consider that this a magazine and not a "transactions light". Papers must be:

    interesting,
    readable,
    technically substantive,
    have good images or graphics, and
    describe a working system

We do not want papers that simply describe a robot that works, there needs to be some insight or learning from the exercise.

It is not a requirement that papers:

    make a theoretical contribution
    have theorems or lots of equations, 10 equations is probably a reasonable upper bound
    have lots of references, 20 is probably a reasonable upper bound

Regular papers and special issue papers should all conform to these guidelines.

If you do not have the time personally to review the paper within the allotted time on the review form, please see if one of your qualified associates or students can review the paper. In this case, please notify the Associate Editor or Editor who invited you to review this paper so that the paper may be-reassigned. Otherwise, inform us at your earliest convenience so that we may find an alternative reviewer.

You undoubtedly appreciate the importance of minimizing publication delays to provide papers of current interest. Therefore it is important that you complete the review form as soon as possible. Hopefully the paper is related to your previous or present activities to make the review relatively interesting and useful to you.

Please note: an author retains the rights to all unpublished work, and any results and ideas from this work must not be used by a referee for research publications if they are obtained exclusively through the reviewing process.

Please supply any information that you think will be useful to the author in revision, in enhancing the appeal of the paper, or in convincing the author of any mistakes.

Your name will appear in this or next year’s reviewers’ list that RAM publishes each year in the December issue.

Thank you in advance for your time on behalf of the Robotics and Automation Society and the Robotics and Automation Magazine Editorial Board.
*** Assessment/Evaluation Section
**** Is_the_paper_clearly_written?
- [ ] A (Excellent)
- [ ] B (Good)
- [ ] C (Fair)
- [ ] D (Unsatisfactory)
- [ ] U (Unsuitable)
**** Interest_to_journal_audience
- [ ] Exceptional
- [ ] Major
- [ ] Minor
- [ ] Questionable
- [ ] None
**** Technological_contribution
- [ ] A (Excellent)
- [ ] B (Good)
- [ ] C (Fair)
- [ ] D (Unsatisfactory)
- [ ] U (Unsuitable)
**** Thoroughness_of_results
- [ ] A (Excellent)
- [ ] B (Good)
- [ ] C (Fair)
- [ ] D (Unsatisfactory)
- [ ] U (Unsuitable)
**** How do you rate the paper quality?
Paper_quality
- [ ] A (Excellent)
- [ ] B (Good)
- [ ] C (Fair)
- [ ] D (Unsatisfactory)
- [ ] U (Unsuitable)
*** Recommendation Section
**** Overall Recommendation
- [ ] Publish
- [ ] Publish subject to revision
- [ ] Not publishable as it is
- [ ] Reject
**** If publishable then publish as
- [ ] Regular Paper
- [ ] Survey Paper
- [ ] Tutorial Paper
- [ ] Special Issue Paper
- [ ] General Non-Technical Article
- [ ] Not applicable
**** How do you rate your own level of confidence in the subject of the submission that you have been asked to review?
- [ ] Very confident
- [ ] Confident
- [ ] Fairly confident
- [ ] Not very confident
- [ ] No confidence
*** Comments Section
**** Confidential Comments to the Editorial Staff*
- Not more than 2000 characters (about 33 full lines)
-  Motivate your evaluation and recommendation 
**** Comments to the Author*
- Not more than 5000 characters (about 83 full lines)
- Please type or paste your comments for the author or authors into the box. You may also upload your review as a file below. Do not identify yourself if you wish to remain anonymous.

- Discuss the following points
  - Does the Introduction state the purpose of the paper?
  - Is the significance of the paper explained relative to previous work?
  - Is the paper clearly written and well organized?
  - What is the contribution of the paper?
  - How may the paper be improved?

- Do not just write "yes" or "no" because the questions themselves are not included in the comments that the author receives

**** Upload an attachment to the Comments to the Author (optional) 
Pdf file of size less than 2 MB

Only documents consisting of a single file are accepted. Do not identify yourself if you wish to remain anonymous. 	

Click on Submit or Save to upload the file

New: All pdf annotations, comments and markup included in your pdf file are retained.
Warning: Annotations that you make to a pdf file carry your identification. To make the review anonymous,
you must ensure that any identifying information is removed. Click here for help

Important: Please make sure that the name of any file that you try to upload,
as well as the names of all directories in the file path, only contain standard ASCII characters.
Otherwise you run the risk of receiving a security violation error message 

*** Save or Submit the Review
Save the possibly incomplete review to complete and submit it later 	
  	Warning: If you save the review then it has not been submitted
Do not forget to return to this page to complete the review and submit it
Send me a copy of the review by e-mail upon submission 	
Submit the review 	
  	Warning: Please check the review carefully before submitting it. You will not be able to revise the review after it has been submitted
After you have submitted the review, click on the status link of the review in your reviews list to see the reviews that are available for this paper (including your own) and, eventually, the publication decision 


** DONE review RollerBall: a mobile colon screening robot
   CLOSED: [2016-09-28 Wed 22:28] SCHEDULED: <2016-09-28 Wed> DEADLINE: <2016-09-29 Thu>
   :PROPERTIES:
   :local: [[file:~/Work/Reviews/IEEE_RAM/RollerBall-%20a%20mobile%20colon%20screening%20robot/][file:~/Work/Reviews/IEEE_RAM/RollerBall- a mobile colon screening robot/]]
   :END:
   - State "DONE"       from "TODO"       [2016-09-28 Wed 22:28]
*** IEEE-RAM Review Form 
**** Details of the Submission
Title  	RollerBall: a mobile colon screening robot
Authors 	Norton, Joseph* (194386), Hood, Adrian (194437), Neville, Anne (153145), Jayne, David (153147), Boyle, Jordan Hylke (154050), Alazmani, Ali (123952), Culmer, Peter Robert (123932)
Submission number and version 	16-0078 (Submission ID 16-0078), Version 1
Review requested by 	Merrifield, Robert (Guest Editor (Guest Editor), 160970)
Under review for publication as 	Paper for special issue on Surgical Robot Challenge
Review ID 	8845
Reviewer 	Ka-Wai Kwok (127660)
**** Some Review Guidelines
Articles appearing in the magazine should be of general interest to readers of the magazine which is primarily society members: not only academics but also students and industry practioners. The maximum length for an article is 8 magazine pages but the mapping from submission format to magazine layout makes this hard to judge. A rule of thumb is that 8 pages in TRO double column format is about 8 magazine pages, but mileage will vary.

It is important to consider that this a magazine and not a "transactions light". Papers must be:

    interesting,
    readable,
    technically substantive,
    have good images or graphics, and
    describe a working system

We do not want papers that simply describe a robot that works, there needs to be some insight or learning from the exercise.

It is not a requirement that papers:

    make a theoretical contribution
    have theorems or lots of equations, 10 equations is probably a reasonable upper bound
    have lots of references, 20 is probably a reasonable upper bound

Regular papers and special issue papers should all conform to these guidelines.

If you do not have the time personally to review the paper within the allotted time on the review form, please see if one of your qualified associates or students can review the paper. In this case, please notify the Associate Editor or Editor who invited you to review this paper so that the paper may be-reassigned. Otherwise, inform us at your earliest convenience so that we may find an alternative reviewer.

You undoubtedly appreciate the importance of minimizing publication delays to provide papers of current interest. Therefore it is important that you complete the review form as soon as possible. Hopefully the paper is related to your previous or present activities to make the review relatively interesting and useful to you.

Please note: an author retains the rights to all unpublished work, and any results and ideas from this work must not be used by a referee for research publications if they are obtained exclusively through the reviewing process.

Please supply any information that you think will be useful to the author in revision, in enhancing the appeal of the paper, or in convincing the author of any mistakes.

Your name will appear in this or next year’s reviewers’ list that RAM publishes each year in the December issue.

Thank you in advance for your time on behalf of the Robotics and Automation Society and the Robotics and Automation Magazine Editorial Board.
**** Assessment/Evaluation Section
***** Is_the_paper_clearly_written?
- [ ] A (Excellent)
- [X] B (Good) 
- [ ] C (Fair)
- [ ] D (Unsatisfactory)
- [ ] U (Unsuitable)
***** Interest_to_journal_audience
- [ ] Exceptional
- [X] Major
- [ ] Minor
- [ ] Questionable
- [ ] None
***** Technological_contribution
- [ ] A (Excellent)
- [ ] B (Good)
- [X] C (Fair)
- [ ] D (Unsatisfactory)
- [ ] U (Unsuitable)
***** Thoroughness_of_results
- [ ] A (Excellent)
- [ ] B (Good)
- [ ] C (Fair)
- [X] D (Unsatisfactory)
- [ ] U (Unsuitable)
***** How do you rate the paper quality?
Paper_quality
- [ ] A (Excellent)
- [ ] B (Good)
- [X] C (Fair)
- [ ] D (Unsatisfactory)
- [ ] U (Unsuitable)
**** Recommendation Section
***** Overall Recommendation
 - [ ] Publish
 - [ ] Publish subject to revision
 - [ ] Not publishable as it is
 - [ ] Reject
***** If publishable then publish as
- [ ] Regular Paper
- [ ] Survey Paper
- [ ] Tutorial Paper
- [X] Special Issue Paper
- [ ] General Non-Technical Article
- [ ] Not applicable
***** How do you rate your own level of confidence in the subject of the submission that you have been asked to review?
- [ ] Very confident
- [X] Confident
- [ ] Fairly confident
- [ ] Not very confident
- [ ] No confidence
**** Comments Section
***** Confidential Comments to the Editorial Staff*
- Not more than 2000 characters (about 33 full lines)
- Motivate your evaluation and recommendation 

This paper presents a robot prototype for colonoscopy. The robot features a novel locomotion mechanism: wheeling and expanding. It has 3 individual arms, each with a wheel at the end. The locomotion is achieved by controlling the expansion of the arms to maintain a certain contact force between the wheels and the inner wall of the colon. Since the robot is internally motorized, pain/discomfort caused by stretching between the colon and abdominal wall in conventional colonoscopy procedure is avoided. The expanding mechanism could be a promising idea for navigation in environments with dynamically changing morphology. 

This paper is well-written and organized, and easy to understand for RAM readers. The figures clearly illustrates the critical ideas and results of the proposed method. 

The proposed locomotion idea is novel and interesting. However, the current experiment settings are too simple; The experiments do not convince the feasibility of the proposed locomotion mechanism for colonoscopy. I would recommend this paper should be revised with enhanced evidence. 

***** Comments to the Author*
- Not more than 5000 characters (about 83 full lines)
- Please type or paste your comments for the author or authors into the box. You may also upload your review as a file below. Do not identify yourself if you wish to remain anonymous.

- Discuss the following points
  - Does the Introduction state the purpose of the paper?
  - Is the significance of the paper explained relative to previous work?
  - Is the paper clearly written and well organized?
  - What is the contribution of the paper?
  - How may the paper be improved?

This paper presents a robot prototype for colonoscopy. The robot features a novel locomotion mechanism: wheeling and expanding. It has 3 individual arms, each with a wheel at the end. The locomotion is achieved by controlling the expansion of the arms to maintain a certain contact force between the wheels and the inner wall of the colon. Since the robot is internally motorized, pain/discomfort caused by stretching between the colon and abdominal wall in conventional colonoscopy procedure is avoided. The expanding mechanism could be a promising idea for navigation in environments with dynamically changing morphology.

This paper is well-written and organized, and easy to understand. The figures clearly illustrates the critical ideas and results of the proposed method. 

I have the following concerns:

1. The colon phantoms are too simple to verify the feasibility of the locomotion mechanism:
   - Real colon is highly flexible. It likely has to pass through acute corners (could be nearly 180 degree), especially when passing through the "alpha loop"; Passing through the "alpha loop" is considered the most difficult. In the current experiment, the most acute corner is only 90 degree. To examine the locomotion efficacy, environment with more acute corners should be used. It is doubtful that the robot prototype can pass through the "alpha loop". 
   - Real colon is soft; It naturally collapses when insufflation is not applied. When it is insufflated, the 
lumen shape is not only with changing diameter as illustrate in Fig. 1a, but also in different shapes such as circular and triangular. Given that the proposed expansion mechanism can maintain contact between the wheels and the colon inner wall, skillful control techniques are required to carry out navigation for passing through non-circular lumen.
   - Real colon is very slippery. Because the locomotion is based on the friction, it is necessary to provide evidence that the current prototype can move on the surfaces with extremely low-friction. E.g. the minimum friction coefficients that the robot can move on, the necessary normal force to provide enough frictional force for locomotion, ... etc.. 

     
   At least, I would recommend to include more acute corners in the experiment to enhance the evidence of the feasibility of the robot prototype. I would suggest, if possible, to verify the locomotion mechanism at least using ex vivo such as pig colon, in addition with other fundamental functionalities such as insufflation and suction, ..., etc.. 

2. Safety: 
   From Fig. 1b, Are the edges of the wheels sharp that will cause damge to the colon tissue? 
   How to ensure the friction is enough for atraumatic locomotion?



- Do not just write "yes" or "no" because the questions themselves are not included in the comments that the author receives

***** Upload an attachment to the Comments to the Author (optional) 
Pdf file of size less than 2 MB

Only documents consisting of a single file are accepted. Do not identify yourself if you wish to remain anonymous. 	

Click on Submit or Save to upload the file

New: All pdf annotations, comments and markup included in your pdf file are retained.
Warning: Annotations that you make to a pdf file carry your identification. To make the review anonymous,
you must ensure that any identifying information is removed. Click here for help

Important: Please make sure that the name of any file that you try to upload,
as well as the names of all directories in the file path, only contain standard ASCII characters.
Otherwise you run the risk of receiving a security violation error message 

**** Save or Submit the Review
Save the possibly incomplete review to complete and submit it later 	
  	Warning: If you save the review then it has not been submitted
Do not forget to return to this page to complete the review and submit it
Send me a copy of the review by e-mail upon submission 	
Submit the review 	
  	Warning: Please check the review carefully before submitting it. You will not be able to revise the review after it has been submitted
After you have submitted the review, click on the status link of the review in your reviews list to see the reviews that are available for this paper (including your own) and, eventually, the publication decision 


* IEEE T-RO

** IEEE T-RO Review Form Template
**** Details of the Submission
   Title  	
   Authors 	
   Submission number and version 	
   Review requested by 	
   Under review for publication as 	
   Review ID 	
   Reviewer 	Ka-Wai Kwok (127660)
**** Instructions for Reviewers of Regular papers
       Please respect the deadline. As an author, you undoubtedly appreciate the importance of minimizing delays.

       Please provide detailed comments to the authors, including AT LEAST A FEW SENTENCES JUSTIFYING YOUR RECOMMENDATION. The following points are suggested for your comments:
       - What is the contribution of the paper?
       - Does the author explain the significance of this paper?
       - Is the paper clearly written and well organized?
       - Does the introduction state the purpose of the paper?
       - Are the references relevant and complete? Supply missing references.
       - If the paper is not technically sound, why not?
       - If the paper is too long for its category, how can it be shortened?
       - In particular, if you recommend to revise and resubmit or to conditionally accept the paper as Short, please provide indications to the authors on how to accomplish this reduction.
       - If the paper is intended for a Special Issue, please comment on its pertinence.

       Supply any information that you think will be useful to the author for a revision, for enhancing the appeal of the paper, or for convincing him/her of the weak points or mistakes. The reviewer's recommendation for acceptance or rejection should not be included in the comments to the author. Do not identify yourself or your organization within the review text.

       In your critical comments to the author, please be specific. If you find that the results are already known, please give references to earlier papers which contain these or similar results. If you say that the reasoning is incorrect or vague, please indicate specifically where and why. If you suggest that the paper be rewritten, give specific suggestions as to which parts of the paper should be deleted, amplified or modified, and please indicate how.

       If the paper has a multimedia attachment (typically, a video clip), please evaluate this in the Comments Section. Is it consistent with the paper content? Does it enhance the paper quality? If it is a video, how is the technical quality? Is it free of commercialism?

       Please note the following T-RO policy: If a paper is submitted as Regular, there is no direct recommendation of acceptance as Short. In view of the presumably large changes needed, the paper should first be conditionally accepted as Short.

       The paper review procedure for the IEEE Transactions on Robotics involves a recommendation prepared by the Associate Editor on the basis of the paper reviews by peers. The final decision on publication, sustaining or modifying this recommendation, is taken by the Editor handling the paper.
**** Recommendation Section for Regular papers
***** Overall Recommendation
- [ ] Accept as Regular Paper provided that all typographic errors and minor recommendations are corrected in the final version
- [ ] Conditionally Accept as Regular Paper provided that minor revisions are made as indicated in the Comments Section
- [ ] Conditionally Accept as Short Paper provided that minor revisions are made as indicated in the Comments Section
- [ ] Revise and Resubmit as Regular Paper as indicated in the Comments Section (if resubmitted, the revised paper should undergo a full review cycle keeping past review material into account)
- [ ] Revise and Resubmit as Short Paper as indicated in the Comments Section (if resubmitted, the revised paper should undergo a full review cycle keeping past review material into account)
- [ ] Reject the Paper (future submission of this work will be treated as a new paper)
- [ ] Submit to Another Journal
***** Please check if you wish to see the revision [] <- checkbox
***** Should this paper be considered for the annual BEST T-RO PAPER AWARD? 	[]
***** If the paper has a multimedia attachment, should this be included in case of final acceptance? 	[]
***** If you have recommended submission to another journal, please indicate which one 	
**** Assessment/Evaluation. Please rate the paper according to the following criteria:
***** Paper Contribution
- [ ] Exceptional
- [ ] Major
- [ ] Minor
- [ ] Questionable
- [ ] None
***** Technical Quality
- [ ] Excellent
- [ ] Good
- [ ] Fair
- [ ] Poor
***** Originality
- [ ] Excellent
- [ ] Good
- [ ] Fair
- [ ] Poor
***** Thoroughness of Results
- [ ] Excellent
- [ ] Good
- [ ] Fair
- [ ] Poor
***** Clarity of Presentation
- [ ] Excellent
- [ ] Good
- [ ] Fair
- [ ] Poor
***** Adequacy of Citations
- [ ] Excellent
- [ ] Good
- [ ] Fair
- [ ] Poor
***** Relevance to the Field
- [ ] Excellent
- [ ] Good
- [ ] Fair
- [ ] Poor
- [ ] Excellent
**** Comments Section
***** Confidential Comments to the Editorial Staff.
Not more than 2000 characters (about 33 full lines)


***** Comments to the Author


Not more than 9000 characters (about 150 full lines)
Please discuss:
- Major Contribution of the Paper
  - Organization and Style
  - Technical Accuracy
  - Presentation
  - Adequacy of Citations
  - Multimedia (if present)
***** Upload an attachment to the Comments to the Author (optional)
Upload an attachment to the Comments to the Author (optional)

Pdf file of size less than 1 MB

Use this for including additional material (e.g., review with equations or graphs). Please mention this attachment in your Comments to the Author. 	

Click on Submit or Save to upload the file

New: All pdf annotations, comments and markup included in your pdf file are retained.
Warning: Annotations that you make to a pdf file carry your identification. To make the review anonymous,
you must ensure that any identifying information is removed. Click here for help

Important: Please make sure that the name of any file that you try to upload,
as well as the names of all directories in the file path, only contain standard ASCII characters.
Otherwise you run the risk of receiving a security violation error message 

**** Save or Submit the Review
Save the possibly incomplete review to complete and submit it later 	
  	Warning: If you save the review then it has not been submitted
Do not forget to return to this page to complete the review and submit it
Send me a copy of the review by e-mail upon submission 	
Submit the review 	
  	Warning: Please check the review carefully before submitting it. You will not be able to revise the review after it has been submitted
After you have submitted the review, click on the status link of the review in your reviews list to see the reviews that are available for this paper (including your own) and, eventually, the publication decision

** TODO review Kim et al, "Active Stiffness Tuning of a Spring-based Continuum Robot for MRI-Guided Neurosurgery"
   DEADLINE: <2017-07-13 Thu> SCHEDULED: <2017-07-13 Thu>
   :PROPERTIES:
   :local: [[file:~/Work/Reviews/IEEE_TRO/Kim2016Active/][file:~/Work/Reviews/IEEE_TRO/Kim2016Active/]]
   :END:
   - State "DONE"       from "TODO"       [2017-03-07 Tue 19:05]
   - State "DONE"       from "TODO"       [2016-09-29 Thu 15:49]

*** IEEE T-RO Review Form (3nd review on <2017-07-11 Tue>)
**** Details of the Submission
   Title  	Active Stiffness Tuning of a Spring-based Continuum Robot for MRI-Guided Neurosurgery
   Authors 	Kim, Yeongjin (119984), Cheng, Shing Shin* (178362), Desai, Jaydev P. (101676)
   Submission number and version 	16-0481 (Submission ID 16-0481), Version 1
   Review requested by 	Wang, Hesheng (Associate Editor, 103003)
   Under review for publication as 	Regular Paper
   Review ID 	44809
   Reviewer 	Ka-Wai Kwok (127660)
**** Instructions for Reviewers of Regular papers
       Please respect the deadline. As an author, you undoubtedly appreciate the importance of minimizing delays.

       Please provide detailed comments to the authors, including AT LEAST A FEW SENTENCES JUSTIFYING YOUR RECOMMENDATION. The following points are suggested for your comments:
       - What is the contribution of the paper?
       - Does the author explain the significance of this paper?
       - Is the paper clearly written and well organized?
       - Does the introduction state the purpose of the paper?
       - Are the references relevant and complete? Supply missing references.
       - If the paper is not technically sound, why not?
       - If the paper is too long for its category, how can it be shortened?
       - In particular, if you recommend to revise and resubmit or to conditionally accept the paper as Short, please provide indications to the authors on how to accomplish this reduction.
       - If the paper is intended for a Special Issue, please comment on its pertinence.

       Supply any information that you think will be useful to the author for a revision, for enhancing the appeal of the paper, or for convincing him/her of the weak points or mistakes. The reviewer's recommendation for acceptance or rejection should not be included in the comments to the author. Do not identify yourself or your organization within the review text.

       In your critical comments to the author, please be specific. If you find that the results are already known, please give references to earlier papers which contain these or similar results. If you say that the reasoning is incorrect or vague, please indicate specifically where and why. If you suggest that the paper be rewritten, give specific suggestions as to which parts of the paper should be deleted, amplified or modified, and please indicate how.

       If the paper has a multimedia attachment (typically, a video clip), please evaluate this in the Comments Section. Is it consistent with the paper content? Does it enhance the paper quality? If it is a video, how is the technical quality? Is it free of commercialism?

       Please note the following T-RO policy: If a paper is submitted as Regular, there is no direct recommendation of acceptance as Short. In view of the presumably large changes needed, the paper should first be conditionally accepted as Short.

       The paper review procedure for the IEEE Transactions on Robotics involves a recommendation prepared by the Associate Editor on the basis of the paper reviews by peers. The final decision on publication, sustaining or modifying this recommendation, is taken by the Editor handling the paper.
**** Recommendation Section for Regular papers
***** Overall Recommendation
- [X] Accept as Regular Paper provided that all typographic errors and minor recommendations are corrected in the final version
- [ ] Conditionally Accept as Regular Paper provided that minor revisions are made as indicated in the Comments Section
- [ ] Conditionally Accept as Short Paper provided that minor revisions are made as indicated in the Comments Section
- [ ] Revise and Resubmit as Regular Paper as indicated in the Comments Section (if resubmitted, the revised paper should undergo a full review cycle keeping past review material into account)
- [ ] Revise and Resubmit as Short Paper as indicated in the Comments Section (if resubmitted, the revised paper should undergo a full review cycle keeping past review material into account)
- [ ] Reject the Paper (future submission of this work will be treated as a new paper)
- [ ] Submit to Another Journal
***** Please check if you wish to see the revision [] <- checkbox
***** Should this paper be considered for the annual BEST T-RO PAPER AWARD? 	[]
***** If the paper has a multimedia attachment, should this be included in case of final acceptance? 	[]
***** If you have recommended submission to another journal, please indicate which one 	
**** Assessment/Evaluation. Please rate the paper according to the following criteria:
***** Paper Contribution
- [ ] Exceptional
- [X] Major
- [ ] Minor
- [ ] Questionable
- [ ] None
***** Technical Quality
- [ ] Excellent
- [X] Good
- [ ] Fair
- [ ] Poor
***** Originality
- [ ] Excellent
- [ ] Good
- [X] Fair
- [ ] Poor
***** Thoroughness of Results
- [ ] Excellent
- [X] Good
- [ ] Fair
- [ ] Poor
***** Clarity of Presentation
- [ ] Excellent
- [X] Good
- [ ] Fair
- [ ] Poor
***** Adequacy of Citations
- [ ] Excellent
- [X] Good
- [ ] Fair
- [ ] Poor
***** Relevance to the Field
- [ ] Excellent
- [X] Good
- [ ] Fair
- [ ] Poor
- [ ] Excellent
**** Comments Section
***** Confidential Comments to the Editorial Staff.
Not more than 2000 characters (about 33 full lines)

In this 3rd revision, the authors have experimentally verified that the surface temperature of the SMA device is 35°C, which is lower than the brain necrosis temperature at ~44°C. The reviewer accept this answer and agree the acceptance of this manuscript.


***** Comments to the Author

The authors have experimentally verified that the surface temperature of the SMA device is 35°C, which is lower than the brain necrosis temperature at ~44°C. The reviewer accept this answer and agree the current content is publishable. 


Not more than 9000 characters (about 150 full lines)
Please discuss:
- Major Contribution of the Paper
  - Organization and Style
  - Technical Accuracy
  - Presentation
  - Adequacy of Citations
  - Multimedia (if present)
***** Upload an attachment to the Comments to the Author (optional)
Upload an attachment to the Comments to the Author (optional)

Pdf file of size less than 1 MB

Use this for including additional material (e.g., review with equations or graphs). Please mention this attachment in your Comments to the Author. 	

Click on Submit or Save to upload the file

New: All pdf annotations, comments and markup included in your pdf file are retained.
Warning: Annotations that you make to a pdf file carry your identification. To make the review anonymous,
you must ensure that any identifying information is removed. Click here for help

Important: Please make sure that the name of any file that you try to upload,
as well as the names of all directories in the file path, only contain standard ASCII characters.
Otherwise you run the risk of receiving a security violation error message 
**** Save or Submit the Review
Save the possibly incomplete review to complete and submit it later 	
  	Warning: If you save the review then it has not been submitted
Do not forget to return to this page to complete the review and submit it
Send me a copy of the review by e-mail upon submission 	
Submit the review 	
  	Warning: Please check the review carefully before submitting it. You will not be able to revise the review after it has been submitted
After you have submitted the review, click on the status link of the review in your reviews list to see the reviews that are available for this paper (including your own) and, eventually, the publication decision
  	
 

*** IEEE T-RO Review Form (2nd review on <2017-03-07 Tue 19:05>)
**** Details of the Submission
   Title  	Active Stiffness Tuning of a Spring-based Continuum Robot for MRI-Guided Neurosurgery
   Authors 	Kim, Yeongjin (119984), Cheng, Shing Shin* (178362), Desai, Jaydev P. (101676)
   Submission number and version 	16-0481 (Submission ID 16-0481), Version 1
   Review requested by 	Wang, Hesheng (Associate Editor, 103003)
   Under review for publication as 	Regular Paper
   Review ID 	44809
   Reviewer 	Ka-Wai Kwok (127660)
**** Instructions for Reviewers of Regular papers
       Please respect the deadline. As an author, you undoubtedly appreciate the importance of minimizing delays.

       Please provide detailed comments to the authors, including AT LEAST A FEW SENTENCES JUSTIFYING YOUR RECOMMENDATION. The following points are suggested for your comments:
       - What is the contribution of the paper?
       - Does the author explain the significance of this paper?
       - Is the paper clearly written and well organized?
       - Does the introduction state the purpose of the paper?
       - Are the references relevant and complete? Supply missing references.
       - If the paper is not technically sound, why not?
       - If the paper is too long for its category, how can it be shortened?
       - In particular, if you recommend to revise and resubmit or to conditionally accept the paper as Short, please provide indications to the authors on how to accomplish this reduction.
       - If the paper is intended for a Special Issue, please comment on its pertinence.

       Supply any information that you think will be useful to the author for a revision, for enhancing the appeal of the paper, or for convincing him/her of the weak points or mistakes. The reviewer's recommendation for acceptance or rejection should not be included in the comments to the author. Do not identify yourself or your organization within the review text.

       In your critical comments to the author, please be specific. If you find that the results are already known, please give references to earlier papers which contain these or similar results. If you say that the reasoning is incorrect or vague, please indicate specifically where and why. If you suggest that the paper be rewritten, give specific suggestions as to which parts of the paper should be deleted, amplified or modified, and please indicate how.

       If the paper has a multimedia attachment (typically, a video clip), please evaluate this in the Comments Section. Is it consistent with the paper content? Does it enhance the paper quality? If it is a video, how is the technical quality? Is it free of commercialism?

       Please note the following T-RO policy: If a paper is submitted as Regular, there is no direct recommendation of acceptance as Short. In view of the presumably large changes needed, the paper should first be conditionally accepted as Short.

       The paper review procedure for the IEEE Transactions on Robotics involves a recommendation prepared by the Associate Editor on the basis of the paper reviews by peers. The final decision on publication, sustaining or modifying this recommendation, is taken by the Editor handling the paper.
**** Recommendation Section for Regular papers
***** Overall Recommendation
- [ ] Accept as Regular Paper provided that all typographic errors and minor recommendations are corrected in the final version
- [X] Conditionally Accept as Regular Paper provided that minor revisions are made as indicated in the Comments Section
- [ ] Conditionally Accept as Short Paper provided that minor revisions are made as indicated in the Comments Section
- [ ] Revise and Resubmit as Regular Paper as indicated in the Comments Section (if resubmitted, the revised paper should undergo a full review cycle keeping past review material into account)
- [ ] Revise and Resubmit as Short Paper as indicated in the Comments Section (if resubmitted, the revised paper should undergo a full review cycle keeping past review material into account)
- [ ] Reject the Paper (future submission of this work will be treated as a new paper)
- [ ] Submit to Another Journal
***** Please check if you wish to see the revision [] <- checkbox
***** Should this paper be considered for the annual BEST T-RO PAPER AWARD? 	[]
***** If the paper has a multimedia attachment, should this be included in case of final acceptance? 	[]
***** If you have recommended submission to another journal, please indicate which one 	
**** Assessment/Evaluation. Please rate the paper according to the following criteria:
***** Paper Contribution
- [ ] Exceptional
- [X] Major
- [ ] Minor
- [ ] Questionable
- [ ] None
***** Technical Quality
- [ ] Excellent
- [X] Good
- [ ] Fair
- [ ] Poor
***** Originality
- [ ] Excellent
- [ ] Good
- [X] Fair
- [ ] Poor
***** Thoroughness of Results
- [ ] Excellent
- [X] Good
- [ ] Fair
- [ ] Poor
***** Clarity of Presentation
- [ ] Excellent
- [X] Good
- [ ] Fair
- [ ] Poor
***** Adequacy of Citations
- [ ] Excellent
- [X] Good
- [ ] Fair
- [ ] Poor
***** Relevance to the Field
- [ ] Excellent
- [X] Good
- [ ] Fair
- [ ] Poor
- [ ] Excellent
**** Comments Section
***** Confidential Comments to the Editorial Staff.
Not more than 2000 characters (about 33 full lines)

The authors have revised accordingly to the previous comments. The answers are acceptable. This paper is publishable after the including the response about the heating problem answered in R3Q3 in the rebuttal. 

***** Comments to the Author

The authors have revised accordingly to the previous comments. The answers are acceptable. The heating problem is important safety for surgical application. The answer in R3Q3 in the rebuttal should be included in the paper. 


Not more than 9000 characters (about 150 full lines)
Please discuss:
- Major Contribution of the Paper
  - Organization and Style
  - Technical Accuracy
  - Presentation
  - Adequacy of Citations
  - Multimedia (if present)
***** Upload an attachment to the Comments to the Author (optional)
Upload an attachment to the Comments to the Author (optional)

Pdf file of size less than 1 MB

Use this for including additional material (e.g., review with equations or graphs). Please mention this attachment in your Comments to the Author. 	

Click on Submit or Save to upload the file

New: All pdf annotations, comments and markup included in your pdf file are retained.
Warning: Annotations that you make to a pdf file carry your identification. To make the review anonymous,
you must ensure that any identifying information is removed. Click here for help

Important: Please make sure that the name of any file that you try to upload,
as well as the names of all directories in the file path, only contain standard ASCII characters.
Otherwise you run the risk of receiving a security violation error message 
**** Save or Submit the Review
Save the possibly incomplete review to complete and submit it later 	
  	Warning: If you save the review then it has not been submitted
Do not forget to return to this page to complete the review and submit it
Send me a copy of the review by e-mail upon submission 	
Submit the review 	
  	Warning: Please check the review carefully before submitting it. You will not be able to revise the review after it has been submitted
After you have submitted the review, click on the status link of the review in your reviews list to see the reviews that are available for this paper (including your own) and, eventually, the publication decision
*** rebuttal (Reviewer 3 <- kawai)
Reviewer #3:
This paper presents a spring-based continuum robot for MRI-guided deep intracranial tumor removal surgery. The robot is composed of tendon driven mechanism integrated with shape memory alloy (SMA) spring. The robot joint could be independently controlled. A tendon routing configuration was designed to adjust local stiffness of the SMA spring backbone. Analytical stiffness model was developed, and experiments were carried out to analyze the resistive force, and also to evaluate MRI compatibility of the robot. However, the major weakness is that the proposed experimental validation may not sufficiently demonstrate the work relevant to the real surgical requirement, giving rise to many concerns from the clinical side as follows:
Major concerns:

**** R3Q1.
The outer diameter of robot is 13mm and it is proposed for deep intracranial tumor removal aforementioned in the part of abstract. To insert such a device into the brain, a burr hole with diameter much more than 13mm is needed to create on the patient’s skull, since it may require more than one instrument in this procedure. Large effect of “brain shift” in this case could significantly affect the overall accuracy of the surgical manipulation, and further safety. The length of each segment is not clearly depicted in the paper. As can be seen in Fig. 1, the length is approximately 18mm. To reach the deep brain region, the robot needs to comprise four or more segments, thus traveling all the way beyond the critical structures that may deviate from the brain map pre-operatively obtained by functional/DT MRI. Note that such images are not obtainable during the procedure. Experimental validation is expected to ensure how the robot is capable to precisely reach the deep tumors, and meanwhile avoiding excessive damage under the further manipulation by this Ø13-mm SMA-based instrument.

***** Response: Thank you for your comments. The robot is MR-compatible so that it can work in an MRI scanner while obtaining intraoperative MRI images. These intraoperative MRI images are necessary to understand “brain shift” or deviation between preoperative brain map and intra-operative brain map. The robot is designed to fit in a commercially available straight neuroendoport (11-13 mm) used commonly in microsurgery that allows direct access to a deep-seated brain tumor [1,2]. Three segments are sufficient to provide the additional degrees of freedom to move around critical regions in the tumor region, should the condition calls for it. Divided into three segments, the robot has a 60 mm length and a diameter of 12.6 mm. Its length and multiple degrees of freedom allow the robot to have a sufficiently large enough workspace to cover deep brain tumors which have an average diameter of less than 40 mm [3]. The robot motion experiment in gelatin during the MRI compatibility test (See Figure 18) serves as preliminary verification of the motion capability of the robot inside the brain.
  The amendment is as follows:
  The robot is designed to have the workspace to cover deep brain tumors which have an average diameter of less than 40 mm [51] and each segment should achieve a bending angle of at least 45o. It is important to note that the bending angle is relative to the orientation (surface normal vector) of the prior disk. Hence the change in bending angle causes twice the change in the surface normal of the subsequent disk. For example, a bending angle of 45o results in a 90o orientation change of the subsequent disk as illustrated in Fig. 1(c). The diameter was selected so that the entire robot can fit inside an existing endoport (11-13 mm) used in microsurgical resection of deep-seated brain tumor [52], [53]. The lumen through the center of the robot has to be at least 4 mm to have enough room for the electrocautery wires, and suction and irrigation tubes. The electrocautery probes are embedded at the tip of the end segment of the robot. The robot has a 65 mm length, an outer diameter of 12.6 mm, and a lumen diameter of 4.1 mm to cover the required workspace, fit in the existing endoport, and to house the required wires and cables.
and is located in section II titled “Robot Design”.
[1]Ding, Dale, Robert M. Starke, R. Webster Crowley, and Kenneth C. Liu. "Endoport- assisted microsurgical resection of cerebral cavernous malformations." Journal of Clinical Neuroscience 22, no. 6 (2015): 1025-1029.
[2]Jo, Kwang-Wook, Hyung Jin Shin, Do-Hyun Nam, Jung-Il Lee, Kwan Park, Jong Hyun Kim, and Doo-Sik Kong. "Efficacy of endoport-guided endoscopic resection for deep-seated brain lesions." Neurosurgical review 34, no. 4 (2011): 457-463.
[3] Linzer, D., S. M. Ling, H. Villalobos, W. Raub Jr, X. Wu, J. Ting, A. Berti, H. Landy, and A. M. Markoe. "Gamma knife radiosurgery for large volume brain tumors: An analysis of acute and chronic toxicity." Stereotactic and functional neurosurgery 70, no. Suppl. 1 (1998): 11-18.

**** R3Q2.
In Fig. 12, the largest bending angle seems to be 10 degree for each segment. For a three- segment robot, maximum 30 degrees could be obtained in one direction. Detailed workspace analysis is expected to ensure if the dexterity sufficiently capable to perform the required manipulation. Test applied on a brain phantom (e.g. made of gelatin-based materials) is also expect to evaluate the performance.
***** Response: Thank you for your comment. In the previously submitted paper, we only performed the experiments for small bending angles. Per the reviewer’s comment, we have repeated the experiments and bent each robot segment up to around 45o bending angle. It should be noted that a bending angle of 45o represents 90o change in the surface normal of the segment disk. Tests have also been performed in a brain-like gelatin phantom and the MR images are shown in Fig. 18 in the revised manuscript. The robot motion experiment in gelatin during the MRI compatibility test serves as preliminary verification of the motion capability of the robot inside the brain.
 The amendment is as follows
Fig. 1(c): Illustration showing that the surface normal of the end segment disk has an orientation change of 90o that is twice the bending angle of 45o 
and is located in section II titled “Robot Design”.
The amendment is as follows:
Figure 12: Experimental results of the independent joint motion for (a) only end segment actuation, (b) only middle segment actuation, and (c) only base segment actuation
and is located in section V titled “Independent Joint Control”.

**** R3Q3.
The local stiffness of each segment could be tuned by varying the temperature of SMA backbone, thus its stiffness, and locking the tendon. The stiffness test was only applied on a single segment of the robot. Experiment is expected to evaluate the entire robot to obtain the overall performance. It also intuitively comes up a question if brain tissue can withstand up to 47°C. If so, clinical support is mostly required.
***** Response: Thank you for your comment. As the reviewer mentioned, we performed the stiffness modulation experiment for the complete three-segmented robot. The results are shown in Fig. 14. The outer spring, which is covered with vinyl, prevents contact between the spring joint and the brain tissue. The outer surface temperature of the robot was measured to be 3-4 degrees lower than the SMA temperature consistently. Following our current work that proves the ability to modulate the stiffness of the individual robot segment, we plan to train SMA springs at a lower temperature to achieve a lower austenite finish temperature. This would provide more assurance that the robot surface temperature would not be close to the brain tissue necrosis temperature of 44oC [4].
Fig. 14 Changes in resistive force when the robot tip moves by a lateral displacement of 5 mm in the four aforementioned cases.

[4] Matsumi, N., Matsumoto K., Mishima, N., Moriyama, E., Furuta, T., Nishimoto, A., & Taguchi, K. (1994). Thermal Damage Threshold of Brain Tissue—Histological Study of Heated Normal Monkey Brains—. Neurologia medico-chirurgica, 34(4), 209-215.
This amendment is as follows:
all robot segments were taut. The results shown in Fig. 14 confirm that the tip forces of the three-segmented robot are smaller than those of a single robot segment for all conditions. The conclusion that the combination of tendon locking and SMA backbone stiffening leads to the highest rigidity, followed by SMA backbone stiffening only, and tendon locking only remains the same for the three-segmented robot.
and can be found in the section VI (A) titled “Local stiffness changes by SMA backbone stiffening and tendon locking”.

**** R3Q4.
Fish wire is adopted as the robot tendon, of which wire elasticity in certain amount would reduce lateral deflection of the robot segment, thus making control of its bending angle very challenging. In addition, the elastic deformation of such wire may transform to plastic deformation after sustaining a long-time force. Such validation is required. If this is not the case, specification of this choice of wire has to be emphasized in detail.

***** Response: Thank you and we agree with your comment. The tendons we used to connect between the robot segment discs and the SMA spring actuators are fishing lines (Omniflex 8lb, Zebco Fishing, USA). The fishing line is made of nylon and is likely to undergo plastic deformation provided the elongation is beyond the elastic limit. In our experiments, the force threshold was below the plastic deformation limit. In our future work, we are planning to use Kevlar wire, which would ensure minimal plastic deformation.


**** R3Q5.
In the experiments of local stiffness characterization, resistive forces in four different cases were tested, as shown in Fig 13. However, the forces plotted in Fig.13b according to lateral displacement of the micromanipulator dose only tell a little useful information. Correlation of such resistive force with the robot tip displacement is expected to show various rigidities of the structure.

***** Response: Fig. 13 shows the correlation between the resistive force and the lateral displacement of the robot tip. For instance, the graph for Case IV (combination of tendon locking and SMA backbone stiffening) has the largest slope, meaning that robot rigidity in this particular case is the largest. We also measured and recorded the lateral displacement and resistive force data at several intermediate temperatures during the heating process to determine how the rigidity of the robot segment changes, the results of which are plotted in Fig. 15. Figure 16 shows how the resistive force changes with temperature at several fixed lateral displacements. The theoretical data are plotted alongside the experimental data in both Figs. 15 and 16 to show that our stiffness model matches the experimental data well.
  	
 
* Hamlyn Symposium 2016
     
** A Dual-Arm Robotic Neuroendoscope: Early Results
*** General info
- [[file:~/Work/Review/Hamlyn2016/][working directory]]
- Paper ID: 78
*** Review report
  1. Does this paper fit the scope of the symposium?
     
  Yes
  
  2. Please provide your expertise in the topic area of this paper
  3-Knowledgeable 
  
  3. Originality
     
  Yes really 
  
  4. Soundness of experimental design
     
  Yes really 
  
  5. Clinical/Technical novelty
     
  Technically novel
  
  6. Detailed Comments
     
  This paper presents a dual-arm teleoperated robotic neuroendoscope. 
  It is well-written with clear description of mechanical design, operation interface and control methods.
  
  Evaluations demonstrate that the robot is capable to operate in small workspace with adequate dexterity and compliance for neurosurgical operations.
  
  All the figures, and especially the video, are of high quality to clearly illustrate design of the robot and demonstrate the functionality.
  
  Possibly due to the limited pages, it would be better to include comparison with existing/similar robotic systems, at least to mention in the Introduction, to emphasize the novelty of the presented robot.
  
  7. Please provide your overall rating for this paper
     
  4-Probably accept: I would argue for accepting this paper
  
  8. Comments to Program Chair
     
  The dual-arm teleoperated robotic neuroendoscope presented in this paper is well-designed. 
  The performance shown in both the paper and the video is promising that the presented robot is beneficial to various neurosurgical operations.
  
  I recommend this paper to be accepted for the Hamlyn Symposium. 

** Instrument tip angular kinematics in teleoperated needle-driving
*** General info
- [[file:~/Work/Review/Hamlyn2016/][working directory]]
- Paper ID: 9
*** Review report
  1. Does this paper fit the scope of the symposium?
     
     Yes
     
  2. Please provide your expertise in the topic area of this paper
     
     2-Passing Knowledge
     
  3. Originality
     
     Yes really
     
  4. Soundness of experimental design
     
     Yes really
     
  5. Clinical/Technical novelty
     
     Clinically novel
     
  6. Detailed Comments
     
     Summary:
     The author presents a new metric for evaluation of robot-assisted surgical skills. They propose the normalized angular displacement, the accumulated change in instrument angular displacement normalized by the path length which is the accumulated translational displacement, to assess the tele-operation skill level using surgical robot. In a experiment, they compared the skill level between 6 experienced surgeons and 9 novices without surgical experience in a needle-driving short training (80 trials) using a da Vinci Research Kit. It was found that in the comparison of the last 10 trials, the normalized angular displacement difference between the experienced surgeons and the novices was significant. In contrast, the path length difference between the experienced surgeons and the novices was not significant. The author thereby deduces the path length metric, which is a common measure of surgical skill, is insufficient.
     
     Some detailed comments:
     The paper is well-written and easy to follow.
     The method is clearly described and the results are properly presented. 
     The photos in Figure 1 are blurred.
     
     A question:
     The proposed metric is reasonable that experienced surgeons implicitly manipulate surgical tools with minimum change of orientation.
     Because the operators change both the tool's translational and angular displancement, did the authors try to compare the performance using the metric of both the angular displacement and the translational displacement?
     
     
  
  7. Please provide your overall rating for this paper
     
     4-Probably accept: I would argue for accepting this paper
     
  8. Comments to Program Chair
     
     The proposed metric based on instrument augular displacement for quantitative robot-assisted surgical skill evaluation has shown to be capable of distinguishing experienced surgeons' skill and novices' skill. This result supports the proposed metric would improve assessment in robot-assisted surgical training.
     
     
  I recommend this paper to be accepted for the Hamlyn Symposium. 
  
** A Shape similarity framework for brain fibers classification based on Frénet Frame
*** General info
- [[file:~/Work/Review/Hamlyn2016/][working directory]]
- Paper ID: 39
*** Review report
  1. Does this paper fit the scope of the symposium?
     
     Yes
     
  2. Please provide your expertise in the topic area of this paper
     
     2-Passing Knowledge
     
  3. Originality
     
     Yes really
     
  4. Soundness of experimental design
     
     Yes really
     
  5. Clinical/Technical novelty
     
     Technically novel
     
  6. Detailed Comments 
     
     Summary
     In simplifying visualization and analysis of Diffusion Tensor Imaging (DTI) data of human brain, most methods use metrics that measure local distances of brain fiber data in data clustering process. This paper proposes a framework based on a composite similarity metric to improve data clustering performance. The composite similarity metric consists of a global metric and a local metric. The global metric, obtained based on the Fr\'{e}net equations, measures the similarity of fiber shape; the local metric, obtained based on the Fr\'{e}chet distance, measures the proximity of fibers. The proposed similarity metric is computed by applying the local metric on the results of the global metric.
     Results show that from detailed 3D anatomical representation of brain fiber (arcuate fascicle), the propose method can 1) extract individual fibers, 2) measure the similarity of shape of multiple fibers a 2D similarity matrix visualization and 3) measure and visualize the overall similarity of two fibers -- different fibers have higher value of the proposed metric. 
     
     
  some detailed comments/questions:
  The figures can give superficial understanding about the proposed method and the results.
  However the paper itself is not very well-written, for example, the four steps mentioned in the material and methods section are not explained accordingly in the results section; the figures axes are not labeled; 
  
  Because it is claimed that this research is to improve clustering performance, it is better to show comparison between the proposed metric (global+local) and the common metric (local) to show the improvement. 
  Please revise Figure 3 caption.
  Why the Fr\'{e}net equations and the Fr\'{e}chet distance is chosen? 
  how to determine the threshold? It should be the important part of the research.
  
  
  7. Please provide your overall rating for this paper
     
  3-Neutral: I would not argue for the acceptance/rejection of this paper 
  
  8. Comments to Program Chair
     
     To improve data clustering performance in visualization of human brain fiber using Diffusion Tensor Imaging (DTI), this paper proposes a framework based on a composite metric that measures both the similarity between fibers the shape globally and the proximity locally. 
     Results show that the proposed method can visually classify different brain fiber. 
     
     However, considering the overall quality of the paper, I am neutral for either the acceptance or the rejection.
  
* Frontier  
  
** DONE H T Sen, A Cheng, K Ding, E Boctor, J Wong, I Iordachita, and P Kazanzides, Cooperative Control with Ultrasound Guidance for Radiation Therapy
   CLOSED: [2016-04-28 Thu 16:35] SCHEDULED: <2016-04-28 Thu 11:00-16:00> DEADLINE: <2016-04-28 Thu>
   
   
*** General info
- [[file:~/Work/Reviews/FrontiersinRoboticsandAI/senAPR2016cooperative/][file:~/Work/Reviews/FrontiersinRoboticsandAI/senAPR2016cooperative/]]
- Title: Cooperative Control with Ultrasound Guidance for Radiation Therapy
- Authors: H. Tutkun Sen, Alexis Cheng, Kai Ding, Emad Boctor, John Wong, Iulian Iordachita, and Peter Kazanzides
*** Review report [[file:~/Work/Reviews/FrontiersinRoboticsandAI/senAPR2016cooperative/review_report.org]]
    My independent review report
    Please fill in each field of the independent review questionnaire below. Your review report will only be submitted to the Associate Editor and Authors when clicking on Submit my report.

    S1. ARTICLE TYPE AND STRUCTURE
    ARTICLE TYPE
    Q 1
    Does this manuscript conform to the definition below of Original Research articles? If not, please contact the Frontiers Editorial Office (editorial.office@frontiersin.org).
    
    Original Research articles describe the aims, study, and methods of original research. Results are reported, interpreted and may include a discussion of possible implications. They may also encompass disconfirming results allowing hypothesis elimination, reformulation; or they may report on the non-reproducibility of previously published results.
    Yes
    
    MANUSCRIPT LENGTH
    Q 2
    An Original Research article should not exceed 12'000 words. Should any part of the manuscript be shortened? If so, please specify.
    
    No

    LANGUAGE AND GRAMMAR

    Q 3
    Is the language, specifically the grammar, of sufficient quality?
    Yes
    
    Q 4
    Should the authors send this manuscript to an expert in English editing and academic writing?
    
    No

    S2. GENERAL EVALUATION
    MAIN MESSAGE
    Q 5
What are the main findings reported in this manuscript?
This manuscript presents a cooperative control framework that provides real-time guidance to locate
soft-tissue for radiotherapy. 
Results show that a tumor 3D position in a abdomen phantom could be estimated within 2mm; the ultrasound probe can be positioned within 10mm and 2 degree accuracy.
The results imply an inexperienced operators can reproduce ultrasound image that previously found by an expert. 
    
    Q 6
    Is the study presented in a consistent and succinct form?
    Yes
    
    OBJECTIVE ERRORS
    Q 7
    Are there any objective errors in the methodology? If so, please specify.

    No

    Q 8
    Are there any objective errors in the results? If so, please specify.

    No

    INITIAL OVERVIEW
    Q 9
    Significance of the results:
    7
    Q 10
    Quality of the methods:
    6
    Q 11
    Quality of the writing:
    6
    Q 12
    Quality of the figure(s):
    7
    Q 13
    Quality of the table(s):
    6
    Q 14
    Quality of the approach:
    6
    Q 15
    Novelty of the results:
    6

    S3. INDIVIDUAL SECTIONS
    MANDATORY SECTIONS
    Q 16
    An Original Research article is composed of the following five mandatory sections: abstract, introduction, materials and methods, results, and discussion. Are all these sections present?
    Yes

    TITLE AND ABSTRACT
    Q 17
    Does the title clearly and precisely reflect the findings of the manuscript, as described in the author guidelines?
    Yes
    
    Q 18
    Is the abstract written in a clear and comprehensive way?
    Yes
    
    INTRODUCTION
    Q 19
    Does the introduction present the study in an appropriate context?
    Yes
    
    Q 20
    Other comments on the introduction.
- the term patient setup should be defined more clearly. the general description in the first paragraph "the goal is to set up the
patient in accordance with the plan prior to delivering the radiation" is ok. but the "patient setup with US image" should be desribed in more detailed in the following paragraph. E.g. tasks and requirements in the patient setup

Q 21
Is the purpose of the study, including motivation for new studies, explained?
Yes

MATERIAL AND METHODS
Q 22
Are the procedures sufficiently advanced and accurate to address the research questions posed?
Yes

Q 23
Are the statistical methods used valid?
Yes


Q 24
Other comments on the materials and methods.
- Since cooperative control with virtual fixtures is the central issue of the paper, although the "virtual fixture" method was developed in the author's previous work, more detailed should be elaborated.
e.g.
How the VFs relate to the VF Stiffness matrix in Figure 3? 
Equations of the cooperative control should be shown to illustrate how virtual fixture forece (Fig. 3) is generated to cooperate with the operator's force to manipulate the probe to the desired position and orientation, and provide haptic feedback.

- line 109: "minimal ultrasound experience" is unfair to describe the skill of radiation therapists
  
Q 25
Are the materials and methods sufficiently described?

No
RESULTS
Q 26
Are the results presented appropriately?
Yes

Q 27
Have the author(s) included all the information required to reach the conclusions?

No
Q 28
Other comments on the results.
One of the claim is that the proposed framework produce consistence soft-tissue deformation at all stages of the radiotherapy (line 43-45), results of soft-tissue deformation should be shown.

Is it possible to improve the interpretation of the equations (2)-(5)? e.g. visualization 
It took me some time to recall the knowledge of homogeneous transformation in order to understand and verify the meaning of the equations.


DISCUSSION
Q 29
Does the Discussion address the research questions posed in the Introduction?
Yes

Q 30
Does the Discussion interpret the results in light of previous knowledge?
Yes

Q 31
Are the conclusions justified?
Yes

Q 32
Other comments on the discussion or the conclusions.

line 242: "the US probe placement difference is 8.64 ± 4.86 mm in translation and 1.79 ± 1.45 degrees in rotation. This measurement may be clinically significant, ...""
it is difficult to judge if this accuracy achievement is clinically significant. The authors explain this by a treatment plan case where a beam is passed within 10mm of the probe. So, what if the plan requirement is within "5mm"?
So maybe the control performance should be compared with existing stage-of-art achievement. 



S4. ETHICAL STANDARDS
ETHICAL STANDARDS
Q 33
Has the work been conducted in conformity with the ethical standards of the field?
Yes
No
Not Applicable
Q 34
For research involving human subjects or animals, do the author(s) identify the committee approving the studies and provide confirmation that all studies conform to the relevant regulatory standards?


Not Applicable
CLINICAL TRIALS
Q 35
Has the clinical trial been registered in a public trials registry?


Not Applicable
BIOSECURITY STANDARDS
Q 36
Does the manuscript describe experiments using a select agent or toxin?


Not Applicable
Q 37
Is it possible that this manuscript contains a National Science Advisory Board for Biosecurity (NSABB)-defined experiment of concern?


Not Applicable
S5. COMPLEMENTARY DATA
COMPLEMENTARY DATA
Q 38
Does the manuscript include any complementary data that should be deposited to an online repository or database (including nucleotide/amino acid sequences, crystallographic or NMR data, microarray data, etc)?


Not Applicable
Q 39
For any complementary data submitted to an online repository or database, do the author(s) provide the accession number?


Not Applicable
S6. OTHER COMMENTS
Q 40
Please add here any further comments on this manuscript.

comments on the figures
The results are promising, but the paper is still not publishable because some important ingredients is missing.

    
Figure 1: please use different annotation pointing color. Black is not a good choice.
     
Figure 2: 
     - please describe the functions of dash arrows.
     - please indicate the planning is done by expert and delivery is done by none expert
       
       
Figure 6:
     - please indicate which frames are fixed and which frames are moving 


*** Finished review - accepted <2016-07-05 Tue 21:00>
* IROS
** DONE Vincent Groenhuis, Francoise J. Siepel, Jeroen Veltman and Stefano Stramigioli, Design and characterization of Stormram 4: an MRI-compatible robotic system for breast biopsy
   CLOSED: [2017-04-06 Thu 18:28]
   - State "DONE"       from              [2017-04-06 Thu 18:28]
*** General info
    :PROPERTIES:
    :Directory: file:~/Work/Reviews/IROS_2017
    :Title: Design and characterization of Stormram 4: an MRI-compatible robotic system for breast biopsy
    :Authors: Vincent Groenhuis, Francoise J. Siepel, Jeroen Veltman and Stefano Stramigioli
    :END:
    
This paper presents a robot prototype, Strormram 4, for performing breast biopsy in MRI environment. It is a four degrees-of-freedom (DoFs) needle manipulator driven by pneumatic stepper motors. The motors are designed to have zero backlash, which is enabled by keeping the gear teeth in contact with a piston to "lock" the motion of a rack. The insertion and horizontal positioning of the needle are provided by two individual linear racks. The novelty of this work goes to use of two individual curved racks to provide the vertical positioning and insertion angle adjustment of the needle. Compared to its previous version, Strormarm 3, the robot has smaller size (26 X 21 X 16 mm) and finer step size (0.25mm). The end effector is positioned by solving the inverse kinematics of the system. In the experiment, the robot could automatically locate the needle tip in sub-millimeter precision, and transfer about 40N via 0.5 meter pneumatic transmission from the power source. The presented video has also demonstrated the smooth and stable actuation of all the DoFs.

The paper is easy-to-follow. The overall mechanical design, especially the zero backlash stepper motors, is impressive. Although the current work is a proof-of-concept, there are several concerns toward clinical application:

Major concerns:
•	Relatively short pneumatic tubes of 0.5 meter were used in the experimentation. However, in the clinical environment, the separation between the control room and the MRI scanner room should be much larger, e.g. 10 meters. Such long transmission would inevitably induce hysteresis and degrade the positioning accuracy and force output. Moreover, larger pressure should then be used to make the gas "more incompressible", as well as the pipelines should be as straight as possible; What is the maximum pressure the robot structure can sustain? The authors should consider evaluation of the robot performance using longer pipeline, or provide justifications of the feasibility in clinical setting based on the current results.
•	Despite the robot could be made of MR-safe materials, MRI-compatibility test is expected to support the claim of "MRI-compatible robotic system". Authors should evaluate the effects to the MR images in clinical setting when the robot is operating inside a MRI scanner. 
•	The two curved stepper motors only provide 2 DOF to adjust the insertion angle along the y-z plane (Fig.7). Does it imply the adjustment of insertion angle along the x-z plane is less important? How to alter the insertion angle along the x-z plane? 
•	In addition, how to decide the placement of the robot and how to fix it in practice? According to Fig. 1, one can image the robot would be placed on the patient body. The authors should clarify this practical concern in the paper.
•	Table 1 only shows the result in the X- and Z-direction, what is the precision of insertion in the Y-direction?
Minor concerns
•	Page 2: Should it be: zero backlash and "zero" hysteresis.?
•	What is the X-axis of E_phi? how to compute E_phi?
•	Please indicate l_1, alpha, beta and l_4 in Fig 6. 
•	The captions should be placed above the Table 1 and 2 according to the normal IEEE format.
•	Page 6: A typo: "Further tests on breast phantoms ... into account.n"


The video clearly demonstrates smooth and stable actuations of all the four degrees-of-freedom and its positioning accuracy in submillimeter level, which coincide with the claims in the paper.

To the editor:
- This paper presents an MRI-compatible needle manipulator
for breast biopsy. The overall mechanical design,
especially the zero backlash stepper motors, is impressive.
The results show the robot has high accuracy and the
provided video shows the needle motion is very smooth. The
weakness of the paper is the experimentation. Currently,
short (0.5 meter) pneumatic transmission was adopted,
however, the separation between MRI room and the control
room would be much larger, e.g. 10 meters. Moreover, it
lacks the validation of MRI-compatibility. Despite such
deficiencies, the novelty in terms of mechanical design deserves
the acceptance in the IROS 2017.




** DONE M Grammatikopoulou, K Leibrandt, and G. Z. Yang, Motor Channelling for Safe and Effective Dynamic Constraints in Minimally Invasive Surgery
   CLOSED: [2016-05-09 Mon 13:44] SCHEDULED: <2016-05-07 Sat> DEADLINE: <2016-05-09 Mon>
   - State "DONE"       from "INPROGRESS" [2016-05-09 Mon 13:44]
      
*** General info
    :PROPERTIES:
    :Directory: [[file:~/Work/Reviews/IROS_2016]]
    :Title: Motor Channelling for Safe and Effective Dynamic Constraints in Minimally Invasive Surgery
    :Authors: Maria Grammatikopoulou, Konrad Leibrandt, and Guang-Zhong Yang, Fellow, IEEE
    :END:

*** Review report


**** Motivation
     Active constraints have been employed in several researches to provide force feedback functionality in order to enhance precision and safety during minimally invasive surgery (MIS). This paper aims to solve several technical challenges in the active constraints framework and to incorporate several features to achieve motor channelling, which provides navigation and haptic feedback to operators in master-slave surgical setups.

**** Methodology
     This paper proposes to integrate the guidance active constraints (GACs) and forbidden region active constraints (FRACs) to simultaneously enable tool navigation assistance along predefined paths and tool restriction. As a result of the integration, smooth and continuous force-torque rendering is achieved by avoiding switching between attractive and repulsive forces. To achieve bounded rendering forces, a simplified frictional force model from reference [17] is employed to dissipate kinetic energy. The motion of the target anatomy is compensated such that the velocity of the slave manipulator is synchronized with that of the contact point (or the point being contacted) on the target anatomy surface. The contact point motion is estimated by online the signal reconstruction technique called least-squares spectral analysis (LSSA). 
     
**** Novelty
     The novelty of this paper is not clearly stated. 
It is stated that there is no a unified control strategy that integrate both GACs and (FRACs). 
However, it has already been done in some literature (please give suggestion here).
The novelty is weak because it is apparently an integration of existing algorithms.

**** Results
     The proposed motor chanelling control scheme was validated using the daVinci Research Kit in simulating surface scanning for in situ medical imaging and vessel manipulation for microvascular anastomosis in Totally Endoscopic Robotic Coronary Artery Bypass (TECAB). Results show that the penetration of the anatomy was reduced in the surface scanning task and the distance between the tool and the dynamics phantom surface was reduced in the vessel manipulation task.

**** More detailed comments 
     The paper is well-organized and well-written, with appropriate equations, figures and especially the high quality video to clearly elaborate the proposed method and results. 

     "Another challenge of active constraints ... instabilities to the robotic control system." is written in the introduction. Please clearly state that what is the corresponding challenge in the preceding paragraph. Is it about the merge of GACs and FRACs? Or is it about the identification of user's intentions? In this paper identifying user's intention is not installed. Instead the user's intentions are "respected" as stated in section II B. 

     About the proposed force-torque profile in Fig. 2, is there possibility that wrong direction of force will be exerted near the constraint boundary? Consider the case where the surface does not align with the constraints boundary due to measurement or estimation error but locates in zone (2) moving towards zone (1). According to the proposed force-torque profile an attractive force to the constraint boundary will give damage to the tissue. The proposed profile may need modification in such case. 
     It is also better to indicate the direction of force exerted on the manipulator in each zone.

     About the estimation of the motion prediction in section III B, how to determine the number of dominant frequencies $N$ needed in eq. (16) and how many sample $M$ is required? It would be better to demonstrate the estimation result with aperiodic signal. For instance, the results demonstrated in Yuen et al. "Robotic Motion Compensation for Beating Heart Intracardiac Surgery", IJRR, 2009, which is the extension of the reference [14].










* IEEE Sensors Journal

** DONE Y Noh, H Liu, S Sareh, D S Chathuranga, H Wurdemann, K Rhode, K Althoefer, Image-based Optical Miniaturized Three-Axis Force Sensor for Cardiac Catheterization
   CLOSED: [2016-08-03 Wed 13:14] DEADLINE: <2016-07-22 Fri>
   - State "DONE"       from "TODO"       [2016-08-03 Wed 13:14]
*** General info
    :PROPERTIES:
    :Directory: file:~/Work/Review//IEEE_Sensor_Journal
    :link: [[file:~/Work/Review/IEEE_Sensor_Journal/Image-based%20Optical%20Miniaturized%20Three-Axis%20Force%20Sensor%20for%20Cardiac%20Catheterization.pdf::%25PDF-1.5][.pdf]]
    :Title: Image-based Optical Miniaturized Three-Axis Force Sensor for Cardiac Catheterization
    :Authors: Yohan Noh, Hongbin Liu, Sina Sareh, Damith Suresh Chathuranga, Helge Wurdemann, Kawal Rhode, Kaspar Althoefer
    :END:

*** Review report (The score sheet)

Review
Please expand and give details in Comments to the Author

 
A. Suitability of Topic
1. Is the topic appropriate for publication in these transactions?

 Yes


2. Is the topic important to colleagues working in the field?

 Yes


 
B. Content
1. Is the paper technically sound? If no, why not?

 Yes

  
2. Is the coverage of the topic sufficiently comprehensive and balanced?

 Yes

3. How would you describe the technical depth of the paper?

 Appropriate for the generally knowledgeable individual Working in the Field or a Related Field

4. How would you rate the technical novelty of the paper?


 Somewhat novel


 
C. Presentation
1. How would you rate the overall organization of the paper?

 Satisfactory


2. Are the title and abstract satisfactory?

 Yes

  
3. Is the length of the paper appropriate? If not, recommend how the length of the paper should be amended, including a possible target length for the final manuscript.

 Yes

  
4. Are symbols, terms, and concepts adequately defined?

 Yes

5. How do you rate the English usage?

 Satisfactory

6. Rate the Bibliography?

 Satisfactory

 
D. Overall rating
1. How would you rate the technical contents of the paper? 	


 good
	

2. How would you rate the novelty of the paper? 	


 sufficiently novel
	

3. How would you rate the "literary" presentation of the paper? 	

 totally accessible
	

4. How would you rate the appropriateness of this paper for publication in this IEEE Transactions? 	


 good match
	

 
Would you recommend this paper for a Best Paper Award?

	

No

 

Recommendation
	

Publish Unaltered
	

Would you be willing to review a revision of this manuscript?
	

Yes
	

Comments

Confidential Comments to the Associate Editor

I recommend this paper to be published in the IEEE Sensors Journal. 
This paper presents a force sensor based on fiber-optic technology, specifically for the application to cardiac electrophysiology treatment.
This paper is very well-written, where the objective, methods and results are clearly presented with high-quality figures. The novelty is on the miniaturization of the design to attain sensitive force measurement using fiber-optic technology, which is a promising technology for the development of MR-compatible sensory devices. 

Comments to the Author

Please include all comments to be sent to the author in this section. If comments are in a file, please type "see attached file."


This paper presents a force sensor based on fiber-optic technology, specifically for the application to cardiac electrophysiology treatment. The presented sensor measures forces in three orthogonal axes. There is a mirror inside the sensor to reflect light from an optical fiber to 3 other optical fibers. A digital camera is installed at the other end of the fibers. When force is applied to the deformable structure of the sensor, the light intensity received at the camera changes. The image is processed in real time to reduce noise using a Kalman filter. A calibration method is proposed for the force estimation, where the relationship between the 3-axis forces and the light intensity is approximated by a linear equation with so called the decoupling stiffness matrix. The result is promising, although the estimation error is still not very satisfactory. 

This paper is very well-written, where the objective, methods and results are clearly presented with high-quality figures. The novelty is on the miniaturization of the design to attain sensitive force measurement using fiber-optic technology, which is a promising technology for the development of MR-compatible sensory devices. The only weak point of this paper is the large estimation error. Due to the nonlinearity of the measured data, the use of linear approximation is, of course, less suitable. To this end, adopting nonlinear regression techniques such as SVM may improve the estimation performance in a simple way. 

     
*** Other reviewers' comments and authors' response

List of changes and response to reviewers

We would like to thank the reviewers for their helpful comments. We have updated the manuscript in line with these comments and highlighted the changes in red in the manuscript and in the responses below.

Reviewer 1

Comments:
This paper presents a novel miniaturized 3-axis force sensor using optic-fiber technology. The sensor composes of 3D printed deformable structure, in which 4 optical fibers are embedded at one end, and a mirror is installed at one end. The force applied on the tip of deformable structure can be measured by detecting the reflected light image from the mirror. A digital camera is integrated at the other end of the fiber bundles to retrieve such images, and image processing algorithm is also proposed to compute the force in real time. The paper is very well written. The part of introduction provides a good overview why such 3-axis tactile sensing is of importance to RF ablation in cardiac electrophysiology (EP), particularly for MRI-guided one. The content is clear with detailed explanation and illustration of the design and fabrication process. Comparison between the estimated force and the ground truth is also conducted, and the experimental results are promising. The work presented is impressive and convincing in general. The authors are expected to improve the manuscript by taking account for the following concerns:

Sensor material property:

1. Any hysteresis occurs in the 3D printed deformable structure? e.g. measurement difference between applying and releasing force on the structure

Answer: Thank you for this comment. In principle, hysteresis property is influenced by the characteristics of the material properties. In the future research, we will consider to fabricate the sensor structure from titanium which has very low hysteresis, e.g. titanium. To make this clearer, we have added the following paragraph to the discussion (highlighted in yellow):
In 6), the sensor structure is made out of a UV curable acrylic plastic (VisiJet®EX200) manufactured by a rapid prototyping machine (Projet 3000, 3D SYSTEM Co., Ltd), with relatively large hysteresis values. The hysteresis influences the sensor’s linearity and, hence, negatively impacts the accuracy of calibration matrix, resulting in sensor value estimation errors.

2. Although the optical fiber and the signal are not sensitive to the temperature change, the printed deformable part probably does. The air gap, if any, inside the tip between the mirror and optical fibers may cause variation.

Answer: we agree that the change of temperature may cause the printed part small displacement, therefore affect the sensor readings. In the future, we will make further investigations on the effect of the temperature change to the distance between mirror and optical fibers using different structural materials (highlighted in green):
In addition, the change of temperature may produce small displacements in the sensing structure and, therefore, affect the sensor readings. The use of MR-compatible materials such as titanium and cobalt-chromium in future designs can potentially reduce the error due to hysteresis and temperature change.

3. Is it feasible to integrate the proposed sensor with the current standard EP catheter? If not, how far could it be? What is the corresponding technical challenges?

Answer: Thanks. To address this comment we have added the following paragraph to the discussion (highlighted in sky blue):
The conventional catheters are around 7-7.5 French (2.31-2.475 mm) in diameter. In extreme case of the ablation, catheters are around 8-10 French (2.64-3.3mm) thick. Hence, in order to integrate our sensor development approach into the catheters (including EP and ablation Catheters) and secure some space to pass electric cables through, it is essential to miniaturize the overall size of the sensor structure. This can be done through reducing the diameter of the optical fiber bundle; the size of a bundle of the multi-cores can be further miniaturized by using a 0.125 mm optical fiber bundle which is available off the shelf. The diameter of the catheter tip could be further reduced through optimization of the material properties of the sensing structure. In the future work, we will use MR-compatible materials such as titanium and cobalt-chromium to minimize the catheter’s tip size to around 7-7.5 French (2.31-2.475 mm).

Future work:
4. Would a high-quality CMOS camera be useful to offer images with less light intensity noise? Is the image processing technique capable to reduce such noise with higher image input rate?

Answer: Many thanks for this point. We have added the following sentences to the discussion section to address it (highlighted in purple):
Using a high-quality CMOS camera or providing a higher image input rate to the image processing approach can potentially reduce the light intensity noise, leading to a reduced force estimation error. We will investigate this further in our future research. However, there will be always a trade-off between the image quality and the image input rate.

5. While Kalman filter is demonstrated to estimate/reduce noise error, another adaptive approach is also recommended with the aim to model/process the noise variable for better estimation/reduction.

Answer: We would like to thank to recommendation of the reviewer. In our future study, we will improve the filtering algorithm with the aim of modelling/processing the noise variable for better estimation, so that reducing the noise effectively (highlighted in Cyan):
Furthermore, we will improve the filtering algorithm with aim of modelling/processing the noise variable for better estimation/reduction to reduce the noise effectively.
Experiment and validation:

6. Additional validation is suggested to investigate the sensing error in combinations of the three axes, rather than just along a single axis at once only.

Answer: We would like to thank to recommendation of the reviewer. We will consider your recommendation for our future work and have added the following sentences to the discussion to further clarify on this point (highlighted in red):
This should be mentioned that the sensing error was validated along a single axis at once only. The future work will investigate the sensor error in combination of the three axes.

Reviewer 2

Comments:
1. This research work targets the development of a triaxial force sensor with fiber-optics technology, in order to achieve miniaturization of the tip and hence applicability in surgical procedures with particular respect to cardiac ones.
The developed technology appears to be sound and the rationale towards miniaturization of the sensor (though not guaranteeing very high precision) is clear.
I have only a suggested discussion point to be addressed by the authors in the revised paper.
The sensing principle based on a mirror appears to be highly sensitive to shear forces because such tangential forces alter the angle of the mirror plane. Conversely, normal forces do not cause modification in such angle and hence the transduction is due to change in the distance between the mirror and the lower plate. Due to this, I had a doubt that the calibration matrix K could have been ill-conditioned, and I calculated the conditioning number (“cond” function in Matlab), obtaining about 2 which is acceptable (though not excellent).
So, I encourage the authors to discuss those aspects in the revised paper, linking in a more direct manner the FEM analysis of Fig. 7, the calibration matrix (Equation 9) and the proposed revised design in Fig. 17. The ingredients are there, but the dots have to be connected along the paper for the sake of proper discussion.

Answer: We would like to thank to recommendation of the reviewer and added the following sentences to the discussion section to clarify this point (highlighted in dark yellow):
The matrix calibrated experimentally as shown in equation (8) and (9) could be potentially ill-conditioned, so to avoid such drawback, in the future, we will carry out FEM analysis to obtain an initial theoretical calibration matrix under controlled condition. This process will also allow the structure to be adjusted to optimize the condition number of the matrix. The calibration matrix will be then fine-tuned using experimental data.

2. In Section V, please complement the dimension in “French” with measurement units of the International System.

Answer: Thanks for this comment which has been addresses in the text according to your recommendation.

3. Written English language is very good. Only some minor typos, or some sentences not being fluid, shall be corrected in the revised paper. Examples are:
- “catheter catheterization”
- “makes the sensor is free”
- “allows the sensor immune to”

Answer: Thanks for this comment which has been addressed in the text. 
