* Hamlyn Symposium 2016
     
** A Dual-Arm Robotic Neuroendoscope: Early Results
*** General info
- [[file:~/Work/Review/Hamlyn2016/][working directory]]
- Paper ID: 78
*** Review report
  1. Does this paper fit the scope of the symposium?
     
  Yes
  
  2. Please provide your expertise in the topic area of this paper
  3-Knowledgeable 
  
  3. Originality
     
  Yes really 
  
  4. Soundness of experimental design
     
  Yes really 
  
  5. Clinical/Technical novelty
     
  Technically novel
  
  6. Detailed Comments
     
  This paper presents a dual-arm teleoperated robotic neuroendoscope. 
  It is well-written with clear description of mechanical design, operation interface and control methods.
  
  Evaluations demonstrate that the robot is capable to operate in small workspace with adequate dexterity and compliance for neurosurgical operations.
  
  All the figures, and especially the video, are of high quality to clearly illustrate design of the robot and demonstrate the functionality.
  
  Possibly due to the limited pages, it would be better to include comparison with existing/similar robotic systems, at least to mention in the Introduction, to emphasize the novelty of the presented robot.
  
  7. Please provide your overall rating for this paper
     
  4-Probably accept: I would argue for accepting this paper
  
  8. Comments to Program Chair
     
  The dual-arm teleoperated robotic neuroendoscope presented in this paper is well-designed. 
  The performance shown in both the paper and the video is promising that the presented robot is beneficial to various neurosurgical operations.
  
  I recommend this paper to be accepted for the Hamlyn Symposium. 

** Instrument tip angular kinematics in teleoperated needle-driving
*** General info
- [[file:~/Work/Review/Hamlyn2016/][working directory]]
- Paper ID: 9
*** Review report
  1. Does this paper fit the scope of the symposium?
     
     Yes
     
  2. Please provide your expertise in the topic area of this paper
     
     2-Passing Knowledge
     
  3. Originality
     
     Yes really
     
  4. Soundness of experimental design
     
     Yes really
     
  5. Clinical/Technical novelty
     
     Clinically novel
     
  6. Detailed Comments
     
     Summary:
     The author presents a new metric for evaluation of robot-assisted surgical skills. They propose the normalized angular displacement, the accumulated change in instrument angular displacement normalized by the path length which is the accumulated translational displacement, to assess the tele-operation skill level using surgical robot. In a experiment, they compared the skill level between 6 experienced surgeons and 9 novices without surgical experience in a needle-driving short training (80 trials) using a da Vinci Research Kit. It was found that in the comparison of the last 10 trials, the normalized angular displacement difference between the experienced surgeons and the novices was significant. In contrast, the path length difference between the experienced surgeons and the novices was not significant. The author thereby deduces the path length metric, which is a common measure of surgical skill, is insufficient.
     
     Some detailed comments:
     The paper is well-written and easy to follow.
     The method is clearly described and the results are properly presented. 
     The photos in Figure 1 are blurred.
     
     A question:
     The proposed metric is reasonable that experienced surgeons implicitly manipulate surgical tools with minimum change of orientation.
     Because the operators change both the tool's translational and angular displancement, did the authors try to compare the performance using the metric of both the angular displacement and the translational displacement?
     
     
  
  7. Please provide your overall rating for this paper
     
     4-Probably accept: I would argue for accepting this paper
     
  8. Comments to Program Chair
     
     The proposed metric based on instrument augular displacement for quantitative robot-assisted surgical skill evaluation has shown to be capable of distinguishing experienced surgeons' skill and novices' skill. This result supports the proposed metric would improve assessment in robot-assisted surgical training.
     
     
  I recommend this paper to be accepted for the Hamlyn Symposium. 
  
** A Shape similarity framework for brain fibers classification based on Frénet Frame
*** General info
- [[file:~/Work/Review/Hamlyn2016/][working directory]]
- Paper ID: 39
*** Review report
  1. Does this paper fit the scope of the symposium?
     
     Yes
     
  2. Please provide your expertise in the topic area of this paper
     
     2-Passing Knowledge
     
  3. Originality
     
     Yes really
     
  4. Soundness of experimental design
     
     Yes really
     
  5. Clinical/Technical novelty
     
     Technically novel
     
  6. Detailed Comments 
     
     Summary
     In simplifying visualization and analysis of Diffusion Tensor Imaging (DTI) data of human brain, most methods use metrics that measure local distances of brain fiber data in data clustering process. This paper proposes a framework based on a composite similarity metric to improve data clustering performance. The composite similarity metric consists of a global metric and a local metric. The global metric, obtained based on the Fr\'{e}net equations, measures the similarity of fiber shape; the local metric, obtained based on the Fr\'{e}chet distance, measures the proximity of fibers. The proposed similarity metric is computed by applying the local metric on the results of the global metric.
     Results show that from detailed 3D anatomical representation of brain fiber (arcuate fascicle), the propose method can 1) extract individual fibers, 2) measure the similarity of shape of multiple fibers a 2D similarity matrix visualization and 3) measure and visualize the overall similarity of two fibers -- different fibers have higher value of the proposed metric. 
     
     
  some detailed comments/questions:
  The figures can give superficial understanding about the proposed method and the results.
  However the paper itself is not very well-written, for example, the four steps mentioned in the material and methods section are not explained accordingly in the results section; the figures axes are not labeled; 
  
  Because it is claimed that this research is to improve clustering performance, it is better to show comparison between the proposed metric (global+local) and the common metric (local) to show the improvement. 
  Please revise Figure 3 caption.
  Why the Fr\'{e}net equations and the Fr\'{e}chet distance is chosen? 
  how to determine the threshold? It should be the important part of the research.
  
  
  7. Please provide your overall rating for this paper
     
  3-Neutral: I would not argue for the acceptance/rejection of this paper 
  
  8. Comments to Program Chair
     
     To improve data clustering performance in visualization of human brain fiber using Diffusion Tensor Imaging (DTI), this paper proposes a framework based on a composite metric that measures both the similarity between fibers the shape globally and the proximity locally. 
     Results show that the proposed method can visually classify different brain fiber. 
     
     However, considering the overall quality of the paper, I am neutral for either the acceptance or the rejection.
  
* Frontier 
  
** DONE review paper 
   CLOSED: [2016-04-28 Thu 16:35] SCHEDULED: <2016-04-28 Thu 11:00-16:00> DEADLINE: <2016-04-28 Thu>
   
   
*** General info
- [[file:~/Work/Review/FrontiersinRoboticsandAI/senAPR2016cooperative/][working directory]]
- [[file:~/Work/Review/FrontiersinRoboticsandAI/senAPR2016cooperative/204220_Kazanzides_Manuscript.PDF::%25PDF-1.5%0D][paper pdf]]
- Title: Cooperative Control with Ultrasound Guidance for Radiation Therapy
- Authors: H. Tutkun Sen, Alexis Cheng, Kai Ding, Emad Boctor, John Wong, Iulian Iordachita, and Peter Kazanzides
*** Review report
    My independent review report
    Please fill in each field of the independent review questionnaire below. Your review report will only be submitted to the Associate Editor and Authors when clicking on Submit my report.

    S1. ARTICLE TYPE AND STRUCTURE
    ARTICLE TYPE
    Q 1
    Does this manuscript conform to the definition below of Original Research articles? If not, please contact the Frontiers Editorial Office (editorial.office@frontiersin.org).
    
    Original Research articles describe the aims, study, and methods of original research. Results are reported, interpreted and may include a discussion of possible implications. They may also encompass disconfirming results allowing hypothesis elimination, reformulation; or they may report on the non-reproducibility of previously published results.
    Yes
    
    MANUSCRIPT LENGTH
    Q 2
    An Original Research article should not exceed 12'000 words. Should any part of the manuscript be shortened? If so, please specify.
    
    No

    LANGUAGE AND GRAMMAR

    Q 3
    Is the language, specifically the grammar, of sufficient quality?
    Yes
    
    Q 4
    Should the authors send this manuscript to an expert in English editing and academic writing?
    
    No

    S2. GENERAL EVALUATION
    MAIN MESSAGE
    Q 5
What are the main findings reported in this manuscript?
This manuscript presents a cooperative control framework that provides real-time guidance to locate
soft-tissue for radiotherapy. 
Results show that a tumor 3D position in a abdomen phantom could be estimated within 2mm; the ultrasound probe can be positioned within 10mm and 2 degree accuracy.
The results imply an inexperienced operators can reproduce ultrasound image that previously found by an expert. 
    
    Q 6
    Is the study presented in a consistent and succinct form?
    Yes
    
    OBJECTIVE ERRORS
    Q 7
    Are there any objective errors in the methodology? If so, please specify.

    No

    Q 8
    Are there any objective errors in the results? If so, please specify.

    No

    INITIAL OVERVIEW
    Q 9
    Significance of the results:
    7
    Q 10
    Quality of the methods:
    6
    Q 11
    Quality of the writing:
    6
    Q 12
    Quality of the figure(s):
    7
    Q 13
    Quality of the table(s):
    6
    Q 14
    Quality of the approach:
    6
    Q 15
    Novelty of the results:
    6

    S3. INDIVIDUAL SECTIONS
    MANDATORY SECTIONS
    Q 16
    An Original Research article is composed of the following five mandatory sections: abstract, introduction, materials and methods, results, and discussion. Are all these sections present?
    Yes

    TITLE AND ABSTRACT
    Q 17
    Does the title clearly and precisely reflect the findings of the manuscript, as described in the author guidelines?
    Yes
    
    Q 18
    Is the abstract written in a clear and comprehensive way?
    Yes
    
    INTRODUCTION
    Q 19
    Does the introduction present the study in an appropriate context?
    Yes
    
    Q 20
    Other comments on the introduction.
- the term patient setup should be defined more clearly. the general description in the first paragraph "the goal is to set up the
patient in accordance with the plan prior to delivering the radiation" is ok. but the "patient setup with US image" should be desribed in more detailed in the following paragraph. E.g. tasks and requirements in the patient setup

Q 21
Is the purpose of the study, including motivation for new studies, explained?
Yes

MATERIAL AND METHODS
Q 22
Are the procedures sufficiently advanced and accurate to address the research questions posed?
Yes

Q 23
Are the statistical methods used valid?
Yes


Q 24
Other comments on the materials and methods.
- Since cooperative control with virtual fixtures is the central issue of the paper, although the "virtual fixture" method was developed in the author's previous work, more detailed should be elaborated.
e.g.
How the VFs relate to the VF Stiffness matrix in Figure 3? 
Equations of the cooperative control should be shown to illustrate how virtual fixture forece (Fig. 3) is generated to cooperate with the operator's force to manipulate the probe to the desired position and orientation, and provide haptic feedback.

- line 109: "minimal ultrasound experience" is unfair to describe the skill of radiation therapists
  
Q 25
Are the materials and methods sufficiently described?

No
RESULTS
Q 26
Are the results presented appropriately?
Yes

Q 27
Have the author(s) included all the information required to reach the conclusions?

No
Q 28
Other comments on the results.
One of the claim is that the proposed framework produce consistence soft-tissue deformation at all stages of the radiotherapy (line 43-45), results of soft-tissue deformation should be shown.

Is it possible to improve the interpretation of the equations (2)-(5)? e.g. visualization 
It took me some time to recall the knowledge of homogeneous transformation in order to understand and verify the meaning of the equations.


DISCUSSION
Q 29
Does the Discussion address the research questions posed in the Introduction?
Yes

Q 30
Does the Discussion interpret the results in light of previous knowledge?
Yes

Q 31
Are the conclusions justified?
Yes

Q 32
Other comments on the discussion or the conclusions.

line 242: "the US probe placement difference is 8.64 ± 4.86 mm in translation and 1.79 ± 1.45 degrees in rotation. This measurement may be clinically significant, ...""
it is difficult to judge if this accuracy achievement is clinically significant. The authors explain this by a treatment plan case where a beam is passed within 10mm of the probe. So, what if the plan requirement is within "5mm"?
So maybe the control performance should be compared with existing stage-of-art achievement. 



S4. ETHICAL STANDARDS
ETHICAL STANDARDS
Q 33
Has the work been conducted in conformity with the ethical standards of the field?
Yes
No
Not Applicable
Q 34
For research involving human subjects or animals, do the author(s) identify the committee approving the studies and provide confirmation that all studies conform to the relevant regulatory standards?


Not Applicable
CLINICAL TRIALS
Q 35
Has the clinical trial been registered in a public trials registry?


Not Applicable
BIOSECURITY STANDARDS
Q 36
Does the manuscript describe experiments using a select agent or toxin?


Not Applicable
Q 37
Is it possible that this manuscript contains a National Science Advisory Board for Biosecurity (NSABB)-defined experiment of concern?


Not Applicable
S5. COMPLEMENTARY DATA
COMPLEMENTARY DATA
Q 38
Does the manuscript include any complementary data that should be deposited to an online repository or database (including nucleotide/amino acid sequences, crystallographic or NMR data, microarray data, etc)?


Not Applicable
Q 39
For any complementary data submitted to an online repository or database, do the author(s) provide the accession number?


Not Applicable
S6. OTHER COMMENTS
Q 40
Please add here any further comments on this manuscript.

*** comments on the figures
The results are promising, but the paper is still not publishable because some important ingredients is missing.

    
**** Figure 1: please use different annotation pointing color. Black is not a good choice.
     
**** Figure 2: 
     - please describe the functions of dash arrows.
     - please indicate the planning is done by expert and delivery is done by none expert
       
       
**** Figure 6:
     - please indicate which frames are fixed and which frames are moving 
* IROS

** DONE review IROS 2016
   CLOSED: [2016-05-09 Mon 13:44] SCHEDULED: <2016-05-07 Sat> DEADLINE: <2016-05-09 Mon>
   - State "DONE"       from "INPROGRESS" [2016-05-09 Mon 13:44]
      
*** General info
    :PROPERTIES:
    :Directory: file:~/Work/Review/IROS_2016
    :Title: Motor Channelling for Safe and Effective Dynamic Constraints in Minimally Invasive Surgery
    :Authors: Maria Grammatikopoulou, Konrad Leibrandt, and Guang-Zhong Yang, Fellow, IEEE
    :END:

*** Review report


**** Motivation
     Active constraints have been employed in several researches to provide force feedback functionality in order to enhance precision and safety during minimally invasive surgery (MIS). This paper aims to solve several technical challenges in the active constraints framework and to incorporate several features to achieve motor channelling, which provides navigation and haptic feedback to operators in master-slave surgical setups.

**** Methodology
     This paper proposes to integrate the guidance active constraints (GACs) and forbidden region active constraints (FRACs) to simultaneously enable tool navigation assistance along predefined paths and tool restriction. As a result of the integration, smooth and continuous force-torque rendering is achieved by avoiding switching between attractive and repulsive forces. To achieve bounded rendering forces, a simplified frictional force model from reference [17] is employed to dissipate kinetic energy. The motion of the target anatomy is compensated such that the velocity of the slave manipulator is synchronized with that of the contact point (or the point being contacted) on the target anatomy surface. The contact point motion is estimated by online the signal reconstruction technique called least-squares spectral analysis (LSSA). 
     
**** Novelty
     The novelty of this paper is not clearly stated. 
It is stated that there is no a unified control strategy that integrate both GACs and (FRACs). 
However, it has already been done in some literature (please give suggestion here).
The novelty is weak because it is apparently an integration of existing algorithms.

**** Results
     The proposed motor chanelling control scheme was validated using the daVinci Research Kit in simulating surface scanning for in situ medical imaging and vessel manipulation for microvascular anastomosis in Totally Endoscopic Robotic Coronary Artery Bypass (TECAB). Results show that the penetration of the anatomy was reduced in the surface scanning task and the distance between the tool and the dynamics phantom surface was reduced in the vessel manipulation task.

**** More detailed comments 
     The paper is well-organized and well-written, with appropriate equations, figures and especially the high quality video to clearly elaborate the proposed method and results. 

     "Another challenge of active constraints ... instabilities to the robotic control system." is written in the introduction. Please clearly state that what is the corresponding challenge in the preceding paragraph. Is it about the merge of GACs and FRACs? Or is it about the identification of user's intentions? In this paper identifying user's intention is not installed. Instead the user's intentions are "respected" as stated in section II B. 

     About the proposed force-torque profile in Fig. 2, is there possibility that wrong direction of force will be exerted near the constraint boundary? Consider the case where the surface does not align with the constraints boundary due to measurement or estimation error but locates in zone (2) moving towards zone (1). According to the proposed force-torque profile an attractive force to the constraint boundary will give damage to the tissue. The proposed profile may need modification in such case. 
     It is also better to indicate the direction of force exerted on the manipulator in each zone.

     About the estimation of the motion prediction in section III B, how to determine the number of dominant frequencies $N$ needed in eq. (16) and how many sample $M$ is required? It would be better to demonstrate the estimation result with aperiodic signal. For instance, the results demonstrated in Yuen et al. "Robotic Motion Compensation for Beating Heart Intracardiac Surgery", IJRR, 2009, which is the extension of the reference [14].












