* Hamlyn Symposium 2016
     
** A Dual-Arm Robotic Neuroendoscope: Early Results
*** General info
- [[file:~/Work/Review/Hamlyn2016/][working directory]]
- Paper ID: 78
*** Review report
  1. Does this paper fit the scope of the symposium?
     
  Yes
  
  2. Please provide your expertise in the topic area of this paper
  3-Knowledgeable 
  
  3. Originality
     
  Yes really 
  
  4. Soundness of experimental design
     
  Yes really 
  
  5. Clinical/Technical novelty
     
  Technically novel
  
  6. Detailed Comments
     
  This paper presents a dual-arm teleoperated robotic neuroendoscope. 
  It is well-written with clear description of mechanical design, operation interface and control methods.
  
  Evaluations demonstrate that the robot is capable to operate in small workspace with adequate dexterity and compliance for neurosurgical operations.
  
  All the figures, and especially the video, are of high quality to clearly illustrate design of the robot and demonstrate the functionality.
  
  Possibly due to the limited pages, it would be better to include comparison with existing/similar robotic systems, at least to mention in the Introduction, to emphasize the novelty of the presented robot.
  
  7. Please provide your overall rating for this paper
     
  4-Probably accept: I would argue for accepting this paper
  
  8. Comments to Program Chair
     
  The dual-arm teleoperated robotic neuroendoscope presented in this paper is well-designed. 
  The performance shown in both the paper and the video is promising that the presented robot is beneficial to various neurosurgical operations.
  
  I recommend this paper to be accepted for the Hamlyn Symposium. 

** Instrument tip angular kinematics in teleoperated needle-driving
*** General info
- [[file:~/Work/Review/Hamlyn2016/][working directory]]
- Paper ID: 9
*** Review report
  1. Does this paper fit the scope of the symposium?
     
     Yes
     
  2. Please provide your expertise in the topic area of this paper
     
     2-Passing Knowledge
     
  3. Originality
     
     Yes really
     
  4. Soundness of experimental design
     
     Yes really
     
  5. Clinical/Technical novelty
     
     Clinically novel
     
  6. Detailed Comments
     
     Summary:
     The author presents a new metric for evaluation of robot-assisted surgical skills. They propose the normalized angular displacement, the accumulated change in instrument angular displacement normalized by the path length which is the accumulated translational displacement, to assess the tele-operation skill level using surgical robot. In a experiment, they compared the skill level between 6 experienced surgeons and 9 novices without surgical experience in a needle-driving short training (80 trials) using a da Vinci Research Kit. It was found that in the comparison of the last 10 trials, the normalized angular displacement difference between the experienced surgeons and the novices was significant. In contrast, the path length difference between the experienced surgeons and the novices was not significant. The author thereby deduces the path length metric, which is a common measure of surgical skill, is insufficient.
     
     Some detailed comments:
     The paper is well-written and easy to follow.
     The method is clearly described and the results are properly presented. 
     The photos in Figure 1 are blurred.
     
     A question:
     The proposed metric is reasonable that experienced surgeons implicitly manipulate surgical tools with minimum change of orientation.
     Because the operators change both the tool's translational and angular displancement, did the authors try to compare the performance using the metric of both the angular displacement and the translational displacement?
     
     
  
  7. Please provide your overall rating for this paper
     
     4-Probably accept: I would argue for accepting this paper
     
  8. Comments to Program Chair
     
     The proposed metric based on instrument augular displacement for quantitative robot-assisted surgical skill evaluation has shown to be capable of distinguishing experienced surgeons' skill and novices' skill. This result supports the proposed metric would improve assessment in robot-assisted surgical training.
     
     
  I recommend this paper to be accepted for the Hamlyn Symposium. 
  
** A Shape similarity framework for brain fibers classification based on Frénet Frame
*** General info
- [[file:~/Work/Review/Hamlyn2016/][working directory]]
- Paper ID: 39
*** Review report
  1. Does this paper fit the scope of the symposium?
     
     Yes
     
  2. Please provide your expertise in the topic area of this paper
     
     2-Passing Knowledge
     
  3. Originality
     
     Yes really
     
  4. Soundness of experimental design
     
     Yes really
     
  5. Clinical/Technical novelty
     
     Technically novel
     
  6. Detailed Comments 
     
     Summary
     In simplifying visualization and analysis of Diffusion Tensor Imaging (DTI) data of human brain, most methods use metrics that measure local distances of brain fiber data in data clustering process. This paper proposes a framework based on a composite similarity metric to improve data clustering performance. The composite similarity metric consists of a global metric and a local metric. The global metric, obtained based on the Fr\'{e}net equations, measures the similarity of fiber shape; the local metric, obtained based on the Fr\'{e}chet distance, measures the proximity of fibers. The proposed similarity metric is computed by applying the local metric on the results of the global metric.
     Results show that from detailed 3D anatomical representation of brain fiber (arcuate fascicle), the propose method can 1) extract individual fibers, 2) measure the similarity of shape of multiple fibers a 2D similarity matrix visualization and 3) measure and visualize the overall similarity of two fibers -- different fibers have higher value of the proposed metric. 
     
     
  some detailed comments/questions:
  The figures can give superficial understanding about the proposed method and the results.
  However the paper itself is not very well-written, for example, the four steps mentioned in the material and methods section are not explained accordingly in the results section; the figures axes are not labeled; 
  
  Because it is claimed that this research is to improve clustering performance, it is better to show comparison between the proposed metric (global+local) and the common metric (local) to show the improvement. 
  Please revise Figure 3 caption.
  Why the Fr\'{e}net equations and the Fr\'{e}chet distance is chosen? 
  how to determine the threshold? It should be the important part of the research.
  
  
  7. Please provide your overall rating for this paper
     
  3-Neutral: I would not argue for the acceptance/rejection of this paper 
  
  8. Comments to Program Chair
     
     To improve data clustering performance in visualization of human brain fiber using Diffusion Tensor Imaging (DTI), this paper proposes a framework based on a composite metric that measures both the similarity between fibers the shape globally and the proximity locally. 
     Results show that the proposed method can visually classify different brain fiber. 
     
     However, considering the overall quality of the paper, I am neutral for either the acceptance or the rejection.
  
* Frontier 
  
** DONE H T Sen, A Cheng, K Ding, E Boctor, J Wong, I Iordachita, and P Kazanzides, Cooperative Control with Ultrasound Guidance for Radiation Therapy
   CLOSED: [2016-04-28 Thu 16:35] SCHEDULED: <2016-04-28 Thu 11:00-16:00> DEADLINE: <2016-04-28 Thu>
   
   
*** General info
- [[file:~/Work/Review/FrontiersinRoboticsandAI/senAPR2016cooperative/][working directory]]
- [[file:~/Work/Review/FrontiersinRoboticsandAI/senAPR2016cooperative/204220_Kazanzides_Manuscript.PDF::%25PDF-1.5%0D][paper pdf]]
- Title: Cooperative Control with Ultrasound Guidance for Radiation Therapy
- Authors: H. Tutkun Sen, Alexis Cheng, Kai Ding, Emad Boctor, John Wong, Iulian Iordachita, and Peter Kazanzides
*** Review report
    My independent review report
    Please fill in each field of the independent review questionnaire below. Your review report will only be submitted to the Associate Editor and Authors when clicking on Submit my report.

    S1. ARTICLE TYPE AND STRUCTURE
    ARTICLE TYPE
    Q 1
    Does this manuscript conform to the definition below of Original Research articles? If not, please contact the Frontiers Editorial Office (editorial.office@frontiersin.org).
    
    Original Research articles describe the aims, study, and methods of original research. Results are reported, interpreted and may include a discussion of possible implications. They may also encompass disconfirming results allowing hypothesis elimination, reformulation; or they may report on the non-reproducibility of previously published results.
    Yes
    
    MANUSCRIPT LENGTH
    Q 2
    An Original Research article should not exceed 12'000 words. Should any part of the manuscript be shortened? If so, please specify.
    
    No

    LANGUAGE AND GRAMMAR

    Q 3
    Is the language, specifically the grammar, of sufficient quality?
    Yes
    
    Q 4
    Should the authors send this manuscript to an expert in English editing and academic writing?
    
    No

    S2. GENERAL EVALUATION
    MAIN MESSAGE
    Q 5
What are the main findings reported in this manuscript?
This manuscript presents a cooperative control framework that provides real-time guidance to locate
soft-tissue for radiotherapy. 
Results show that a tumor 3D position in a abdomen phantom could be estimated within 2mm; the ultrasound probe can be positioned within 10mm and 2 degree accuracy.
The results imply an inexperienced operators can reproduce ultrasound image that previously found by an expert. 
    
    Q 6
    Is the study presented in a consistent and succinct form?
    Yes
    
    OBJECTIVE ERRORS
    Q 7
    Are there any objective errors in the methodology? If so, please specify.

    No

    Q 8
    Are there any objective errors in the results? If so, please specify.

    No

    INITIAL OVERVIEW
    Q 9
    Significance of the results:
    7
    Q 10
    Quality of the methods:
    6
    Q 11
    Quality of the writing:
    6
    Q 12
    Quality of the figure(s):
    7
    Q 13
    Quality of the table(s):
    6
    Q 14
    Quality of the approach:
    6
    Q 15
    Novelty of the results:
    6

    S3. INDIVIDUAL SECTIONS
    MANDATORY SECTIONS
    Q 16
    An Original Research article is composed of the following five mandatory sections: abstract, introduction, materials and methods, results, and discussion. Are all these sections present?
    Yes

    TITLE AND ABSTRACT
    Q 17
    Does the title clearly and precisely reflect the findings of the manuscript, as described in the author guidelines?
    Yes
    
    Q 18
    Is the abstract written in a clear and comprehensive way?
    Yes
    
    INTRODUCTION
    Q 19
    Does the introduction present the study in an appropriate context?
    Yes
    
    Q 20
    Other comments on the introduction.
- the term patient setup should be defined more clearly. the general description in the first paragraph "the goal is to set up the
patient in accordance with the plan prior to delivering the radiation" is ok. but the "patient setup with US image" should be desribed in more detailed in the following paragraph. E.g. tasks and requirements in the patient setup

Q 21
Is the purpose of the study, including motivation for new studies, explained?
Yes

MATERIAL AND METHODS
Q 22
Are the procedures sufficiently advanced and accurate to address the research questions posed?
Yes

Q 23
Are the statistical methods used valid?
Yes


Q 24
Other comments on the materials and methods.
- Since cooperative control with virtual fixtures is the central issue of the paper, although the "virtual fixture" method was developed in the author's previous work, more detailed should be elaborated.
e.g.
How the VFs relate to the VF Stiffness matrix in Figure 3? 
Equations of the cooperative control should be shown to illustrate how virtual fixture forece (Fig. 3) is generated to cooperate with the operator's force to manipulate the probe to the desired position and orientation, and provide haptic feedback.

- line 109: "minimal ultrasound experience" is unfair to describe the skill of radiation therapists
  
Q 25
Are the materials and methods sufficiently described?

No
RESULTS
Q 26
Are the results presented appropriately?
Yes

Q 27
Have the author(s) included all the information required to reach the conclusions?

No
Q 28
Other comments on the results.
One of the claim is that the proposed framework produce consistence soft-tissue deformation at all stages of the radiotherapy (line 43-45), results of soft-tissue deformation should be shown.

Is it possible to improve the interpretation of the equations (2)-(5)? e.g. visualization 
It took me some time to recall the knowledge of homogeneous transformation in order to understand and verify the meaning of the equations.


DISCUSSION
Q 29
Does the Discussion address the research questions posed in the Introduction?
Yes

Q 30
Does the Discussion interpret the results in light of previous knowledge?
Yes

Q 31
Are the conclusions justified?
Yes

Q 32
Other comments on the discussion or the conclusions.

line 242: "the US probe placement difference is 8.64 ± 4.86 mm in translation and 1.79 ± 1.45 degrees in rotation. This measurement may be clinically significant, ...""
it is difficult to judge if this accuracy achievement is clinically significant. The authors explain this by a treatment plan case where a beam is passed within 10mm of the probe. So, what if the plan requirement is within "5mm"?
So maybe the control performance should be compared with existing stage-of-art achievement. 



S4. ETHICAL STANDARDS
ETHICAL STANDARDS
Q 33
Has the work been conducted in conformity with the ethical standards of the field?
Yes
No
Not Applicable
Q 34
For research involving human subjects or animals, do the author(s) identify the committee approving the studies and provide confirmation that all studies conform to the relevant regulatory standards?


Not Applicable
CLINICAL TRIALS
Q 35
Has the clinical trial been registered in a public trials registry?


Not Applicable
BIOSECURITY STANDARDS
Q 36
Does the manuscript describe experiments using a select agent or toxin?


Not Applicable
Q 37
Is it possible that this manuscript contains a National Science Advisory Board for Biosecurity (NSABB)-defined experiment of concern?


Not Applicable
S5. COMPLEMENTARY DATA
COMPLEMENTARY DATA
Q 38
Does the manuscript include any complementary data that should be deposited to an online repository or database (including nucleotide/amino acid sequences, crystallographic or NMR data, microarray data, etc)?


Not Applicable
Q 39
For any complementary data submitted to an online repository or database, do the author(s) provide the accession number?


Not Applicable
S6. OTHER COMMENTS
Q 40
Please add here any further comments on this manuscript.

comments on the figures
The results are promising, but the paper is still not publishable because some important ingredients is missing.

    
Figure 1: please use different annotation pointing color. Black is not a good choice.
     
Figure 2: 
     - please describe the functions of dash arrows.
     - please indicate the planning is done by expert and delivery is done by none expert
       
       
Figure 6:
     - please indicate which frames are fixed and which frames are moving 


*** Finished review - accepted <2016-07-05 Tue 21:00>
* IROS

** DONE M Grammatikopoulou, K Leibrandt, and G. Z. Yang, Motor Channelling for Safe and Effective Dynamic Constraints in Minimally Invasive Surgery
   CLOSED: [2016-05-09 Mon 13:44] SCHEDULED: <2016-05-07 Sat> DEADLINE: <2016-05-09 Mon>
   - State "DONE"       from "INPROGRESS" [2016-05-09 Mon 13:44]
      
*** General info
    :PROPERTIES:
    :Directory: file:~/Work/Review/IROS_2016
    :Title: Motor Channelling for Safe and Effective Dynamic Constraints in Minimally Invasive Surgery
    :Authors: Maria Grammatikopoulou, Konrad Leibrandt, and Guang-Zhong Yang, Fellow, IEEE
    :END:

*** Review report


**** Motivation
     Active constraints have been employed in several researches to provide force feedback functionality in order to enhance precision and safety during minimally invasive surgery (MIS). This paper aims to solve several technical challenges in the active constraints framework and to incorporate several features to achieve motor channelling, which provides navigation and haptic feedback to operators in master-slave surgical setups.

**** Methodology
     This paper proposes to integrate the guidance active constraints (GACs) and forbidden region active constraints (FRACs) to simultaneously enable tool navigation assistance along predefined paths and tool restriction. As a result of the integration, smooth and continuous force-torque rendering is achieved by avoiding switching between attractive and repulsive forces. To achieve bounded rendering forces, a simplified frictional force model from reference [17] is employed to dissipate kinetic energy. The motion of the target anatomy is compensated such that the velocity of the slave manipulator is synchronized with that of the contact point (or the point being contacted) on the target anatomy surface. The contact point motion is estimated by online the signal reconstruction technique called least-squares spectral analysis (LSSA). 
     
**** Novelty
     The novelty of this paper is not clearly stated. 
It is stated that there is no a unified control strategy that integrate both GACs and (FRACs). 
However, it has already been done in some literature (please give suggestion here).
The novelty is weak because it is apparently an integration of existing algorithms.

**** Results
     The proposed motor chanelling control scheme was validated using the daVinci Research Kit in simulating surface scanning for in situ medical imaging and vessel manipulation for microvascular anastomosis in Totally Endoscopic Robotic Coronary Artery Bypass (TECAB). Results show that the penetration of the anatomy was reduced in the surface scanning task and the distance between the tool and the dynamics phantom surface was reduced in the vessel manipulation task.

**** More detailed comments 
     The paper is well-organized and well-written, with appropriate equations, figures and especially the high quality video to clearly elaborate the proposed method and results. 

     "Another challenge of active constraints ... instabilities to the robotic control system." is written in the introduction. Please clearly state that what is the corresponding challenge in the preceding paragraph. Is it about the merge of GACs and FRACs? Or is it about the identification of user's intentions? In this paper identifying user's intention is not installed. Instead the user's intentions are "respected" as stated in section II B. 

     About the proposed force-torque profile in Fig. 2, is there possibility that wrong direction of force will be exerted near the constraint boundary? Consider the case where the surface does not align with the constraints boundary due to measurement or estimation error but locates in zone (2) moving towards zone (1). According to the proposed force-torque profile an attractive force to the constraint boundary will give damage to the tissue. The proposed profile may need modification in such case. 
     It is also better to indicate the direction of force exerted on the manipulator in each zone.

     About the estimation of the motion prediction in section III B, how to determine the number of dominant frequencies $N$ needed in eq. (16) and how many sample $M$ is required? It would be better to demonstrate the estimation result with aperiodic signal. For instance, the results demonstrated in Yuen et al. "Robotic Motion Compensation for Beating Heart Intracardiac Surgery", IJRR, 2009, which is the extension of the reference [14].












* IEEE Sensors Journal

** DONE Y Noh, H Liu, S Sareh, D S Chathuranga, H Wurdemann, K Rhode, K Althoefer, Image-based Optical Miniaturized Three-Axis Force Sensor for Cardiac Catheterization
   CLOSED: [2016-08-03 Wed 13:14] DEADLINE: <2016-07-22 Fri>
   - State "DONE"       from "TODO"       [2016-08-03 Wed 13:14]
*** General info
    :PROPERTIES:
    :Directory: file:~/Work/Review//IEEE_Sensor_Journal
    :link: [[file:~/Work/Review/IEEE_Sensor_Journal/Image-based%20Optical%20Miniaturized%20Three-Axis%20Force%20Sensor%20for%20Cardiac%20Catheterization.pdf::%25PDF-1.5][.pdf]]
    :Title: Image-based Optical Miniaturized Three-Axis Force Sensor for Cardiac Catheterization
    :Authors: Yohan Noh, Hongbin Liu, Sina Sareh, Damith Suresh Chathuranga, Helge Wurdemann, Kawal Rhode, Kaspar Althoefer
    :END:

*** Review report (The score sheet)

Review
Please expand and give details in Comments to the Author

 
A. Suitability of Topic
1. Is the topic appropriate for publication in these transactions?

 Yes


2. Is the topic important to colleagues working in the field?

 Yes


 
B. Content
1. Is the paper technically sound? If no, why not?

 Yes

  
2. Is the coverage of the topic sufficiently comprehensive and balanced?

 Yes

3. How would you describe the technical depth of the paper?

 Appropriate for the generally knowledgeable individual Working in the Field or a Related Field

4. How would you rate the technical novelty of the paper?


 Somewhat novel


 
C. Presentation
1. How would you rate the overall organization of the paper?

 Satisfactory


2. Are the title and abstract satisfactory?

 Yes

  
3. Is the length of the paper appropriate? If not, recommend how the length of the paper should be amended, including a possible target length for the final manuscript.

 Yes

  
4. Are symbols, terms, and concepts adequately defined?

 Yes

5. How do you rate the English usage?

 Satisfactory

6. Rate the Bibliography?

 Satisfactory

 
D. Overall rating
1. How would you rate the technical contents of the paper? 	


 good
	

2. How would you rate the novelty of the paper? 	


 sufficiently novel
	

3. How would you rate the "literary" presentation of the paper? 	

 totally accessible
	

4. How would you rate the appropriateness of this paper for publication in this IEEE Transactions? 	


 good match
	

 
Would you recommend this paper for a Best Paper Award?

	

No

 

Recommendation
	

Publish Unaltered
	

Would you be willing to review a revision of this manuscript?
	

Yes
	

Comments

Confidential Comments to the Associate Editor

I recommend this paper to be published in the IEEE Sensors Journal. 
This paper presents a force sensor based on fiber-optic technology, specifically for the application to cardiac electrophysiology treatment.
This paper is very well-written, where the objective, methods and results are clearly presented with high-quality figures. The novelty is on the miniaturization of the design to attain sensitive force measurement using fiber-optic technology, which is a promising technology for the development of MR-compatible sensory devices. 

Comments to the Author

Please include all comments to be sent to the author in this section. If comments are in a file, please type "see attached file."


This paper presents a force sensor based on fiber-optic technology, specifically for the application to cardiac electrophysiology treatment. The presented sensor measures forces in three orthogonal axes. There is a mirror inside the sensor to reflect light from an optical fiber to 3 other optical fibers. A digital camera is installed at the other end of the fibers. When force is applied to the deformable structure of the sensor, the light intensity received at the camera changes. The image is processed in real time to reduce noise using a Kalman filter. A calibration method is proposed for the force estimation, where the relationship between the 3-axis forces and the light intensity is approximated by a linear equation with so called the decoupling stiffness matrix. The result is promising, although the estimation error is still not very satisfactory. 

This paper is very well-written, where the objective, methods and results are clearly presented with high-quality figures. The novelty is on the miniaturization of the design to attain sensitive force measurement using fiber-optic technology, which is a promising technology for the development of MR-compatible sensory devices. The only weak point of this paper is the large estimation error. Due to the nonlinearity of the measured data, the use of linear approximation is, of course, less suitable. To this end, adopting nonlinear regression techniques such as SVM may improve the estimation performance in a simple way. 

     
*** Other reviewers' comments and authors' response

List of changes and response to reviewers

We would like to thank the reviewers for their helpful comments. We have updated the manuscript in line with these comments and highlighted the changes in red in the manuscript and in the responses below.

Reviewer 1

Comments:
This paper presents a novel miniaturized 3-axis force sensor using optic-fiber technology. The sensor composes of 3D printed deformable structure, in which 4 optical fibers are embedded at one end, and a mirror is installed at one end. The force applied on the tip of deformable structure can be measured by detecting the reflected light image from the mirror. A digital camera is integrated at the other end of the fiber bundles to retrieve such images, and image processing algorithm is also proposed to compute the force in real time. The paper is very well written. The part of introduction provides a good overview why such 3-axis tactile sensing is of importance to RF ablation in cardiac electrophysiology (EP), particularly for MRI-guided one. The content is clear with detailed explanation and illustration of the design and fabrication process. Comparison between the estimated force and the ground truth is also conducted, and the experimental results are promising. The work presented is impressive and convincing in general. The authors are expected to improve the manuscript by taking account for the following concerns:

Sensor material property:

1. Any hysteresis occurs in the 3D printed deformable structure? e.g. measurement difference between applying and releasing force on the structure

Answer: Thank you for this comment. In principle, hysteresis property is influenced by the characteristics of the material properties. In the future research, we will consider to fabricate the sensor structure from titanium which has very low hysteresis, e.g. titanium. To make this clearer, we have added the following paragraph to the discussion (highlighted in yellow):
In 6), the sensor structure is made out of a UV curable acrylic plastic (VisiJet®EX200) manufactured by a rapid prototyping machine (Projet 3000, 3D SYSTEM Co., Ltd), with relatively large hysteresis values. The hysteresis influences the sensor’s linearity and, hence, negatively impacts the accuracy of calibration matrix, resulting in sensor value estimation errors.

2. Although the optical fiber and the signal are not sensitive to the temperature change, the printed deformable part probably does. The air gap, if any, inside the tip between the mirror and optical fibers may cause variation.

Answer: we agree that the change of temperature may cause the printed part small displacement, therefore affect the sensor readings. In the future, we will make further investigations on the effect of the temperature change to the distance between mirror and optical fibers using different structural materials (highlighted in green):
In addition, the change of temperature may produce small displacements in the sensing structure and, therefore, affect the sensor readings. The use of MR-compatible materials such as titanium and cobalt-chromium in future designs can potentially reduce the error due to hysteresis and temperature change.

3. Is it feasible to integrate the proposed sensor with the current standard EP catheter? If not, how far could it be? What is the corresponding technical challenges?

Answer: Thanks. To address this comment we have added the following paragraph to the discussion (highlighted in sky blue):
The conventional catheters are around 7-7.5 French (2.31-2.475 mm) in diameter. In extreme case of the ablation, catheters are around 8-10 French (2.64-3.3mm) thick. Hence, in order to integrate our sensor development approach into the catheters (including EP and ablation Catheters) and secure some space to pass electric cables through, it is essential to miniaturize the overall size of the sensor structure. This can be done through reducing the diameter of the optical fiber bundle; the size of a bundle of the multi-cores can be further miniaturized by using a 0.125 mm optical fiber bundle which is available off the shelf. The diameter of the catheter tip could be further reduced through optimization of the material properties of the sensing structure. In the future work, we will use MR-compatible materials such as titanium and cobalt-chromium to minimize the catheter’s tip size to around 7-7.5 French (2.31-2.475 mm).

Future work:
4. Would a high-quality CMOS camera be useful to offer images with less light intensity noise? Is the image processing technique capable to reduce such noise with higher image input rate?

Answer: Many thanks for this point. We have added the following sentences to the discussion section to address it (highlighted in purple):
Using a high-quality CMOS camera or providing a higher image input rate to the image processing approach can potentially reduce the light intensity noise, leading to a reduced force estimation error. We will investigate this further in our future research. However, there will be always a trade-off between the image quality and the image input rate.

5. While Kalman filter is demonstrated to estimate/reduce noise error, another adaptive approach is also recommended with the aim to model/process the noise variable for better estimation/reduction.

Answer: We would like to thank to recommendation of the reviewer. In our future study, we will improve the filtering algorithm with the aim of modelling/processing the noise variable for better estimation, so that reducing the noise effectively (highlighted in Cyan):
Furthermore, we will improve the filtering algorithm with aim of modelling/processing the noise variable for better estimation/reduction to reduce the noise effectively.
Experiment and validation:

6. Additional validation is suggested to investigate the sensing error in combinations of the three axes, rather than just along a single axis at once only.

Answer: We would like to thank to recommendation of the reviewer. We will consider your recommendation for our future work and have added the following sentences to the discussion to further clarify on this point (highlighted in red):
This should be mentioned that the sensing error was validated along a single axis at once only. The future work will investigate the sensor error in combination of the three axes.

Reviewer 2

Comments:
1. This research work targets the development of a triaxial force sensor with fiber-optics technology, in order to achieve miniaturization of the tip and hence applicability in surgical procedures with particular respect to cardiac ones.
The developed technology appears to be sound and the rationale towards miniaturization of the sensor (though not guaranteeing very high precision) is clear.
I have only a suggested discussion point to be addressed by the authors in the revised paper.
The sensing principle based on a mirror appears to be highly sensitive to shear forces because such tangential forces alter the angle of the mirror plane. Conversely, normal forces do not cause modification in such angle and hence the transduction is due to change in the distance between the mirror and the lower plate. Due to this, I had a doubt that the calibration matrix K could have been ill-conditioned, and I calculated the conditioning number (“cond” function in Matlab), obtaining about 2 which is acceptable (though not excellent).
So, I encourage the authors to discuss those aspects in the revised paper, linking in a more direct manner the FEM analysis of Fig. 7, the calibration matrix (Equation 9) and the proposed revised design in Fig. 17. The ingredients are there, but the dots have to be connected along the paper for the sake of proper discussion.

Answer: We would like to thank to recommendation of the reviewer and added the following sentences to the discussion section to clarify this point (highlighted in dark yellow):
The matrix calibrated experimentally as shown in equation (8) and (9) could be potentially ill-conditioned, so to avoid such drawback, in the future, we will carry out FEM analysis to obtain an initial theoretical calibration matrix under controlled condition. This process will also allow the structure to be adjusted to optimize the condition number of the matrix. The calibration matrix will be then fine-tuned using experimental data.

2. In Section V, please complement the dimension in “French” with measurement units of the International System.

Answer: Thanks for this comment which has been addresses in the text according to your recommendation.

3. Written English language is very good. Only some minor typos, or some sentences not being fluid, shall be corrected in the revised paper. Examples are:
- “catheter catheterization”
- “makes the sensor is free”
- “allows the sensor immune to”

Answer: Thanks for this comment which has been addressed in the text. 
