* Notes
** DONE preparation of lecture notes - MECH 3418  
   CLOSED: [2017-02-07 Tue 17:55] SCHEDULED: <2017-01-13 Fri>
   - State "DONE"       from "TODO"       [2017-02-07 Tue 17:55]
   - State "DONE"       from "TODO"       [2017-01-06 Fri 20:49]
   - 15 lecture hours for dynamics
   - current notes in
     - [[file:~/Work/HKU/lecture/MECH3418/][file:~/Work/HKU/lecture/MECH3418/]]
     - Mech3418_LectureNote_2016_v4.pptx
   - https://www.dropbox.com/s/ce2t3o28iodksd0/Mech3418_LectureNote_2016_v4.pptx?dl=0

*** schedule records
   - <2017-01-05 Thu 14:00-17:00>
   - <2017-01-04 Wed 14:00-17:00>
   - <2017-01-03 Tue 11:00-15:00>

** DONE preparation of lecture notes - MECH4404
   CLOSED: [2017-02-07 Tue 17:55] SCHEDULED: <2017-01-13 Fri>

   - State "DONE"       from "TODO"       [2017-02-07 Tue 17:55]
   - 1. Linear control system design (13 hours)
     - (Frequency response methods, polar plot, Nyquist stability criterion, Bode plot, gain-phase relationship, gain and phase margin, minimum & nonminimum phase systems, time-d​elay system.)
   - 2. Computer control system (13 hours)
     - 2(a) Data acquisition using on-line computer, A/D and D/A converters, data logging using micro-computers; z-transform, inverse z-transfom; sampling theory; pulse transfer function, closed-loop transfer function, discrete-time stability analysis; (6 hours)

   - reference
     - Prof. James Lam's notes (kwkwok)
       [[file:~/Work/HKU/lectures/MECH4404/ref/AutomaticControl%201.pdf][AutomaticControl 1.pdf]]
       [[file:~/Work/HKU/lectures/MECH4404/ref/AutomaticControl%202a.pdf][AutomaticControl 2a.pdf]]
     - previous notes 
       - MECH2407
	 https://www.dropbox.com/s/yag0v9u5lwd9hpo/Mech2407_2016.pptx?dl=0
*** schedule records
    - <2017-01-09 Mon 15:30-16:30>
    - <2017-01-04 Wed 18:00-22:00>
** dinner with the Dean of Engineering
   - <2016-12-02 Fri>
   - Morton Steak House, Sheraton Hotel
** DONE prepare task for a prospective phd candidate
   CLOSED: [2016-10-04 Tue 18:15] SCHEDULED: <2016-10-04 Tue>
   - State "DONE"       from "TODO"       [2016-10-04 Tue 18:15]
   - kawai's TRO paper
     - reference from kawai's email:
       >> 发件人: "Ka-Wai Kwok" <kwokkw@hku.hk>
       >> 发送时间: 2014年7月11日 星期五
       >> 收件人: "郭子彦" <guoziyan13@tsinghua.org.cn>
       >> 抄送: "Brian Kit Hang Lee" <brian1029hk@gmail.com>, "Yue Chen" <ychen@uga.edu>
       >> 主题: about the PQ formulation
       >>
       >> Hi Ziyan,
       >>
       >> My TRO paper is attached, demonstrating the formulation of Proximity
       >> Queries. Just reading the Section III.A.2 (starting from "In this study,
       >> points and segment..."), basically, you are expected to understand how
       >> the shortest distance between a point and segment (Fig. 3a) is
       >> calculated via the steps 1-5 (equations 1-6 ).
       >>
       >> Once you get the idea, please inform us, then Brian will tell you what
       >> to do next.
       >>
       >> Thanks,
       >> Ka-Wai
       >>
       >> -- 
       >> B.Eng, MPhil (CU, HK), DIC, PhD (Imperial, UK)
       >> Croucher Research Fellow
       >> at University of Georgia and Harvard Medical School
       >> Assistant Professor
       >> at Mechanical Engineering, The University of Hong Kong
       >> Email: kwokkw@hku.hk / kkwok@uga.edu
       >> Web: http://www.doc.ic.ac.uk/~kkwok/

*** email draft
Dear Prof. Lam,

This is Denny from Dr. Kwok's group.

According to Dr. Kwok's opinion, in order to let the prospective phd candidate understand more about robotics in medical application.
A task is arranged for the prospective Phd candidate Ms. Zhao Chang.

Please find the attached paper (Dr. Kwok's TRO paper). Her task is to study the method in section III A and write a MATLAB program to implement the PQ method. 
She is expected to understand how the shortest distance between a point and segment (Fig. 3a) is calculated. Of course understanding the whole paper would be appreciated. We will later send her some testing data for her program.

Thank you.

Best,
Denny

*** kawai's additional email about the programing task
Dear Prof. Lam,

Appreciate your kind referral. Here is my detailed instruction in regards of the programming task:

As found in the TRO paper, in Section III, there is a proximity query (PQ) algorithm proposed to effectively calculate the shortest distance between two geometries, namely a vertex point and a segment that is defined by two adjacent contours. Following the equations from (1) to (9), along with the pseudocode stated in the paper, the candidate is expected to write a C/C++ programme to:

1) identify if the vertex point is being inside or outside a series of continuous segments;
2) compute the shortest distance from the vertex point to the series of segments;
3) validate your written programme with a graphic diagram, indicating shortest distance between the 3D grid points and the series of segments, e.g. https://www.dropbox.com/s/o0kqtcobi8uoxwo/PQ_diagram.avi?dl=0

If the candidate finds any difficulty, pls suggest him/her to contact my colleagues Denny Fu <dennyfu@hku.hk> and Brian Lee <briankhl@connect.hku.hk>

Thanks,
Ka-Wai


* students
[[file:students/xiaomei.org][Xiaomei]]

[[file:students/ziyan.org][Ziyan]]

[[file:students/ziyang.org][Ziyang]]

[[file:students/brian.org][Brian]]

[[file:students/martin.org][Martin]]

[[file:students/tim.org][Tim]]

[[file:students/chimlee.org][Chimlee]]

[[file:students/marco.org][Marco]]

[[file:students/jacky.org][Jacky]]

* website
  - project by project
    - one para
  - personal description
    - better to have a personal website
    - 

* thesis format 
** 1 research objective and motivation short
** 2 literature review , technical gap , motivation (30 pages)
** 3 simulation
** 4 experimental 

* Lectures

* Seminars

** DONE Modern Control: making optimal decisions online - Prof. Jan M. Maciejowski, University of Cambridge
   CLOSED: [2016-11-28 Mon 19:34] SCHEDULED: <2016-11-28 Mon 18:00-19:00>
   - State "DONE"       from "TODO"       [2016-11-28 Mon 19:34]
   Lecture Theatre C, Chow Yei Ching Building, HKU

   - [[file:~/Work/HKU/Seminars/Maciejowski_HKU_28Nov2016/][file:~/Work/HKU/Seminars/Maciejowski_HKU_28Nov2016/]]
** DONE Computer Aided Surgery and Surgical Robotics - Professor Ichiro Sakuma, The University of Tokyo
   CLOSED: [2016-04-29 Fri 10:57] SCHEDULED: <2016-04-29 Fri 09:00>
Title:           Computer Aided Surgery and Surgical Robotics

Speaker:     Professor Ichiro Sakuma
Vice Dean, School of Engineering
Director, Medical Device Development and Regulation Research Center
Professor, Department of Bioengineering
The University of Tokyo, Tokyo, Japan
 
Date:           April 29, 2016 (Friday)
 
Time:          9:00 a.m.
 
Venue:        HW 7-37, Haking Wong Building, HKU
 
Minimally invasive therapy such as endoscopic surgery and catheter based intervention are being spread in many surgical intervention fields. Thus engineering assistance is important to realize safe and effective minimally invasive therapy. Computer Assisted Surgical guidance such as surgical navigation is one of key technologies. On the other hand, it is expected that application of robotic technology to minimally invasive surgery will provide the following functions:
1.  Precise manipulation of biological tissues and surgical instruments in narrow and confined surgical field.
2.  Precise and accurate localization of therapeutic devices using various pre and intra-operative medical information.
 
In the first mode of application, more compact system is required. At the same time integration with various energy devices such as ultrasonically activated scalpel, bipolar coagulator, and high intensity focused ultrasound. At the same time, intra-operative guidance utilizing various pre and intra operative information is also required.
 
In the second mode of application, image guided robotic system for RF ablation, laser ablation, intensity modified radiation therapy, and high intensity focused ultrasound. In this type of robot, various pre-and intraoperative information including functional information is used to navigate the therapeutic devices to the target lesion.
 
In both applications, preoperative clinical information, in particular three dimensional medical imaging data are widely used. Anatomical information including lesion location are used for surgical navigation and surgical robot control. However, preoperative information does reflect current situation of the patient. For example deformation of soft tissue leads to errors in surgical navigation. Thus use of intra-operative information is required to augment preoperative information or to modify preoperative information. Miniaturized sensor technologies are also important in realizing advanced surgical assist systems. There are inherent limitations in quality of intra-operative information because of clinical constraints that are not found in preoperative data acquisition. Data fusion of pre-and intra-operative information through intelligent signal processing is indispensable.
 
For advancement of minimally invasive therapies, various information technologies as well as robotic/mechatronic technologies should be integrated to realize intended functions of surgical assist systems.
 
 
   
* Lab Demo

** DONE Lab demo - VIP visit
   CLOSED: [2016-12-19 Mon 09:59] SCHEDULED: <2016-12-16 Fri 15:45-17:00>
   - State "DONE"       from "TODO"       [2016-12-19 Mon 09:59]
   - Lenovo seniors, HKU vice president, etc..
   - catheter robot
** DONE ITC visit
   CLOSED: [2016-08-31 Wed 10:46] SCHEDULED: <2016-08-13 Sat 15:00>
   - State "DONE"       from ""           [2016-08-31 Wed 10:46]

*** Atlas lab or at office
** DONE Prof. Kazuhiro Kosuge's visit
   CLOSED: [2016-04-28 Thu 16:35] SCHEDULED: <2016-04-28 Thu 16:00>
