* General info
  :PROPERTIES:
  :Directory: file:~/Work/HKU/MRcompatible_platform/
  :END:
  
* notes

** TERMINOLOGY USED FOR IMPLANTS AND DEVICES RELATIVE TO MRI TESTING 

"OLD" TERMINOLOGY

The terminology applied to implants and devices relative to the MRI environment has evolved over the years. In 1997, the Food and Drug Administration, Center for Devices and Radiological Health, proposed definitions for the terms “MR Safe” and “MR Compatible” (1). These terms are defined as follows:

MR Safe -the device, when used in the MRI environment, has been demonstrated to present no additional risk to the patient or other individual, but may affect the quality of the diagnostic information. The MRI conditions in which the device was tested should be specified in conjunction with the term MR safe since a device which is safe under one set of conditions may not be found to be so under more extreme MRI conditions.

MR Compatible -a device shall be considered "MR compatible" if it is MR safe and the device, when used in the MRI environment, has been demonstrated to neither significantly affect the quality of the diagnostic information nor have its operations affected by the MR system. The MRI conditions in which the device was tested should be specified in conjunction with the term MR safe since a device which is safe under one set of conditions may not be found to be so under more extreme MR conditions.

Using this terminology, MRI testing of an implant or object involved assessments of magnetic field interactions, heating, and, in some cases, induced electrical currents while MR compatibility testing required all of these as well as characterization of artifacts. In addition, it may have been necessary to evaluate the impact of various MRI conditions on the functional or operational aspects of an implant or device (2).

CURRENT TERMINOLOGY

Over the years, manufacturers generally used the terms “MR safe” and “MR compatible” to label medical devices. However, in time it became apparent that these terms were confusing and were often used interchangeably or incorrectly (3). Therefore, in an effort to clarify the terminology and, more importantly, because the misuse of these terms could result in serious accidents for patients and other individuals, the MR task group of the American Society for Testing and Materials (ASTM) International developed a new set of terms with associated icons (4). The new terms, MR Safe, MR Conditional, and MR Unsafe are defined by the ASTM document, as follows.

MR Safe - an item that poses no known hazards in all MRI environments. Using the new terminology, “MR safe” items include non-conducting, non-metallic, non-magnetic items such as a plastic Petri dish. An item may be determined to be MR Safe by providing a scientifically based rationale rather than test data.

MR Conditional - an item that has been demonstrated to pose no known hazards in a specified MRI environment with specified conditions of use. Field conditions that define the MRI environment include static magnetic field strength, spatial gradient, dB/dt (time varying magnetic fields), radio frequency (RF) fields, and specific absorption rate (SAR). Additional conditions, including specific configurations of the item (e.g., the routing of leads used for a neurostimulation system), may be required.

For MR Conditional items, the item labeling includes results of testing sufficient to characterize the behavior of the item in the MRI environment. In particular, testing for items that may be placed in the MRI environment should address magnetically induced displacement force and torque, and RF heating. Other possible safety issues include but are not limited to, thermal injury, induced currents/voltages, electromagnetic compatibility, neurostimulation, acoustic noise, interaction among devices, and the safe functioning of the item and the safe operation of the MR system. Any parameter that affects the safety of the item should be listed and any condition that is known to produce an unsafe condition must be described.

MR Unsafe - an item that is known to pose hazards in all MRI environments. MR Unsafe items include magnetic items such as a pair of ferromagnetic scissors.

In addition to the new terms, the ASTM International document introduced corresponding icons, consistent with international standards for colors and shapes of safety signs. The icons are intended for use on items that may be brought into or near the MRI environment as well as in product labeling. The icons may be reproduced in color or in black and white, however the use of color is encouraged because of the added visibility.

The “MR Safe” icon consists of the letters ‘MR’ in green in a white square with a green border, or the letters ‘MR’ in white within a green square. The “MR Conditional” icon consists of the letters ‘MR’ in black inside a yellow triangle with a black border. The “MR Unsafe” icon consists of the letters ‘MR’ in black on a white field inside a red circle with a diagonal red band. For MR Conditional items, the item labeling must include results of testing sufficient to characterize the behavior of the item in the MRI environment.

Use of Terminology

The new terminology is intended help elucidate matters related to biomedical implants and devices in order to ensure the safe use of MRI technology. Importantly, it should be noted that this new terminology is not being applied retrospectively to implants and devices that previously received Food and Drug (FDA) approved labeling using the terms “MR safe” or “MR compatible” (i.e., in general, this applies to those objects tested prior to December, 2005). Accordingly, this should be understood to avoid undue confusion regarding the matter of labeling for “older” vs. “newer” implants.


* meeting

** TODO progress meeting
   SCHEDULED: <2016-06-15 Wed 15:00 +1w>
   - State "DONE"       from "TODO"       [2016-05-25 Wed 18:00]
   - State "DONE"       from "TODO"       [2016-05-18 Wed 18:00]
   - State "DONE"       from "TODO"       [2016-05-11 Wed 15:00]
   - State "DONE"       from "TODO"       [2016-05-04 Wed 17:00]
   - State "DONE"       from "TODO"       [2016-04-27 Thu 22:00]
   :PROPERTIES:
   :LAST_REPEAT: [2016-06-17 Fri 12:12]
   :END:

* tasks
** Dynamics modeling
   details are located below
*** TODO free body diagram
*** DONE combine equaitons and find necessary constraint equations
    CLOSED: [2016-05-06 Fri 11:14]
    - State "DONE"       from "TODO"       [2016-05-06 Fri 11:14]
*** TODO check friction model between gear and shaft (sliding friction)
*** TODO check friction model between gear and shaft (sliding friction)
*** TODO verification

** Paper
*** TODO draft paper for a journal
    outline is located below
    

*** INPROGRESS submit paper to RA Magazine Special Issue
    DEADLINE: <2016-08-01 Mon>
**** RAM submission info
http://www.ieee-ras.org/publications/ram/ram-special-issues/special-issues-on-surgical-robot-challenge

http://www.ieee.org/publications_standards/publications/authors/authors_journals.html

1. Preparing Your Manuscript

Submitted papers must be written in good understandable English. It is not the job of reviewers, associate editors or editor-in-chief to correct English spelling and grammar, and poorly written papers stand a much lower chance of being accepted. Authors wishing for assistance in this regard may consider using the IEEE proof editing service (fee based).

The submitted paper is submitted as a PDF file for review. There is no format or template requirement and you may use any tool at all (LaTeX, Word etc.) to prepare the PDF file. You might like to use the IEEE PDF checker to ensure that your file is compliant, and some hints on creating compliant PDF files using LaTeX. The IEEE Author Digital Tool Box has many helpful links including tools for correct reference formats.

A technical feature (regular or special issue) should meet the following requirements:

    No more than 9 magazine pages, so aim for no more than 4500 words of text
    No more than 10 equations
    No more than 20 references, unless it is a survey article
    No more than 10 figures
    Include at least one high quality color photograph of the robotic system
    Figures, tables, schematics, plots are very welcome
    PLEASE NOTE: figures need to be submitted in high-resolution, high-quality format such as JPEG, TIFF, EPS, etc. PDF files are not supported.

Be aware that mandatory page charges of USD 250 apply for every published page beyond 8 pages. If your paper has multimedia material then this should be prepared according to the guidelines and submitted at the same time as your PDF file.

If you have not previously submitted a paper to the magazine, you are strongly encouraged to peruse recent issues to familiarize yourself with the style and technical level of typical articles.


*** DONE Hamlyn symposium robotic challenge 2-pages paper
    
**** Project title

**** Abstract

***** revised
Magnetic resonance imaging (MRI) techniques allows electrophysiologists to intra-operatively assess the ablation procedure during cardiovascular electrophysiology (EP); However, it is still challenging to carry out effective catheterization under MRI environment. We present a MRI-conditional catheter robotic system that integrates intra-operative MRI techniques, real-time visual feedback and effective control interface for catheter manipulation. Subject proved that the presented robotic system could enhance the performance of simulated ablation tasks.


***** Ziyan's original
Cardiac electrophysiology (EP) intervention is an effective treatment to arrhythmias. This project presents an MRI-conditional catheter robotic system that integrates intra-operative MRI, MR-based tracking units and enhanced visual guidance with catheter manipulation. The proposed system differs fundamentally from existing remotely controlled EP systems, of which the robotic manipulation is still challenging due to the very limited image guidance. This is the first system that provides a means of integrating intra-op MR imaging and tracking to improve the performance of tele-operated robotic catheterization.
**** Introdution


***** revised
In cardiac EP intervention, a long catheter (>1m) is delivered to the heart chamber; Radiofrequency ablation (RFA) is performed on lesion tissue to isolate the abnormal eletrophysiological signals. The safety and effectiveness of EP intervention can be enhanced by introducing high quality intra-operative visual feedback of cardiac conditions and MR-compatible robotic platform for effective catheterization. Currently, neither any existing commercial nor research prototype of robotic catheterization platform is MR-conditional/safe. We present a MRI-conditional catheter robotic system for effective catheter manipulation that makes use of intra-operative MRI techniques, real-time visual feedback and an advanced kinematics control method.

***** Ziyan's original
In cardiac EP intervention, a long catheter (>1m) has to be delivered to the heart chamber, in which radiofrequency ablation (RFA) is performed on lesion tissue to isolate the abnormal eletrophysiological signals. Numerous patient trials under late gadolinium enhancement T2-weighted MRI have been conducted, which demonstrated safer and more effective EP intervention by monitoring the RFA under MRI. However, the ferromagnetic materials and conductive components in most catheter robots and steerable catheterization systems are forbidden from the use of MRI scanner due to its tremendously strong magnetic field generated. Furthermore, maneuvering of such a long and flexible catheter inside the cardiac chamber is still a challenging task even for the latest advances in the robotic-assisted platforms. Currently, neither any existing commercial nor research prototype of robotic catheterization platform is MR-conditional/safe. There is no well-established robot-human interface capable of continuously registering targets locations based on intra-operative MR images, and guiding the effective manipulation of the long, thin, flexible catheter.


**** Methods

***** Effective MRI-compatible robotic platform: 
We construct a master-slave robotic platform made of MRI-safe, non-ferromagnetic materials for catheterization. Hydraulic transmission with water is adopted to guarantee zero EM interference with the MRI. The master actuators drive the slave actuators, which are isolated 10 m away in the MRI scanner room, providing steering, rolling, translation and fine advancement of a catheter mounted on the slave unit. To achieve effective actuation, we design the actuators with minimum backlash effect and install rolling diaphragms to reduce friction.

***** Real time, intra-operative visualization and position feedback for catheter navigation:
Based on intra-operative MR images, we construct and update a real-time 3D cardiac roadmap. We also employ a micro coil on the catheter tip that enables real-time (> 30 Hz), low latency (<3ms) and accurate (fine spatial resolution 0.6×0.6×0.6mm3) position tracking of the catheter. According to the position feedback, we attach a virtual camera at the a tip of the catheter to provide a virtual view for navigation.

***** User-friendly control interface with visual-motor alignment: 
User can manipulate the catheter by providing desired displacement in the virtual view via a motion input device. We develop a control method based on model-free online estimation of the kinematics relationship between the control input and the catheter tip position, achieving visual-motor alignment between the virtual camera attached to the catheter tip and the virtual.

***** Ziyan's original
Robot motion driven by MR-safe actuation unit: 
The actuator is fabricated by 3D printing, except for the rubber rolling diaphragm. As it is actuated by hydraulic power, the whole unit is MR-safe and remains minimized imaging disturbance in MR environment. The actuator consists of two identical hydraulic piston-actuators, a gear, two long flexible tubes (>10m) and a hydraulic pump. Each piston-actuator consists of a piston, a rolling diaphragm and a cylinder. The two tubes and the hydraulic pump connect the two piston-actuators with fixed amount of pressurized fluid filled inside. The rolling diaphragms act as flexible seals. The two piston-actuators and the gear are assembled such that the gear transmits translational motion of one piston to other piston in opposite direction. When the hydraulic pump forces the pressurized fluid from one cylinder to another by a piston inside, the change of the fluid volume in one cylinder induces pressure on the wall of the rolling diaphragm and pushes the piston out. Simultaneously, the other piston is push into the other cylinder by the force transmitted from the gear and the atmospheric pressure due to the decrease of fluid inside the cylinder. As a result, the pistons provide bidirectional translation and the gear provides bidirectional rotation.

Robot navigation of catheter using MR-based tracking unit: A tracking unit consist of a micro coil which could serve as an MRI-based signal marker and enable the real-time, frequent and continuous sampling of instrument positional tracking with respect to (w.r.t.) the image coordinates. While all the existing prototypes require (manual) selection of landmarks on MR images, e.g. fiducial marker, optical positional tracker. This small coil unit can enable virtual augmentation of instrument configuration on the MR imaging model precisely. It features with high rate position sampling (at >30 Hz) with low latency (<3ms) in fine spatial resolution of 0.6×0.6×0.6mm3). 

Human-robot control interface: We have developed a kinematic-model-free control framework capable of online estimating the motion mapping from the robot actuation to the tip displacement. This update is achieved by the means of a stochastic method that solely depends on previous measurements, namely the tracked position of the catheter tip. Subject test has shown significant improvement with this presented enhanced hand-eye coordination.

**** Results

***** MRI-compatibility: 
- Negligible EM interference was verified by placing the operating robot closely to a commercial MRI phantom cylinder (#452213095955, CadMed+, USA), which was located at the isocenter of the scanner.

***** Ziyan's original
MRI-compatibility: Experimental validation with robot running under MRI have been conducted. The robot was placed closely to a commercial MRI phantom cylinder (#452213095955, CadMed+, USA), which was located at the isocenter of the scanner.

Subject test: Subject tests (10, age ranging from 20-35) were carried out for evaluation, where the pulmonary vein isolation ablation tasks were simulated using the robotic experimental setup. Each subject performed the same task under two different conditions: 1) Only the fly-through view (Fig. 1a) was provided without the proposed control approach. 2) Fly-through view and the virtual camera view (Fig. 1b) were provided, where the proposed visual-motor alignment was employed. Each had to perform RF ablation on pre-defined lesions within 5 minutes. The RF ablation at the catheter tip was activated by a foot pedal.

***** Subject test:
- Subject (10 people(surgeons), age ranging from 20-35) tests of simulated RF ablation tasks using the presented robotic system were carried. 
- It was observed that the visual-motor alignment control interface improved the accuracy (detailed data needed) of the task.
**** Discussion

***** revised
To the best of our knowledge, this is the first robotic systems for image-guided robot-assisted catheterization that integrates intra-operative MRI, real-time visual and position feedback and visual-motor alignment.
It i) enhances the catheter manipulation accuracy to desired surgical region, thus decreasing the chances of recurrence (e.g. currently 30% in atrial fibrillation and 50% in ventricular tachycardia after electrophysiology procedure), 
compensating the cost of using MRI and reducing the overall expenditure; 
ii) improves the safety of catheter navigation, thereby decreasing the rates of undesired damage; 
iii) eases catheter manipulation, thus facilitating the shorter learning curve for surgeons and better treatment for more complex cases. 
For the cardiac EP procedure, it is anticipated that our invention will significantly reduce the chance of post-recurrence of arrhythmia, which cannot be achieved by the current state-of-the-art robot EP catheter system. 

***** Ziyan's original
The effective maneuvering of a long and flexible catheter (about 1.5m) to the desired target points under highly dynamic environment still remains a great challenge. While the current 3D roadmap used for catheter manipulation guidance is static and computed from MRI. This is the first system that provides a means of integrating intra-operative MR imaging and tracking to improve the performance of tele-operated robotic catheterization. The contributions of this system are considered to be: precise MR-safe actuators incorporated in the robotic catheter manipulator; a real-time tracking system with MR-based tracking coils embedded at the tip of catheter, updating the position and shape of catheter by magnetic resonance imaging (MRI); a human-robot control interface with frequently-updated 3D roadmap, offering the intuitive instrument navigation.




***** context in patent application
Through the use of our presented catheter robot featured with MR-based position feedback units integrated with the catheter, we could
- provide a precise and real-time visual feedback to the operator during the catheter navigation under the MRI. 
- Sharing the same MR-tracking coordinates with the MR images can guarantee correct alignment of the virtual catheter configuration relative to the cardiac imaging models, thereby benefiting to various kinds of cardiovascular catheter intervetion. 
- Combined with the robotic manipulation of the catheter, 
- not only could the ablation progress be monitored by MRI, but it also enables the operator to re-target the insufficiently ablated lesions readily through the tele-operated manipulation of the catheter in the control room. 


Currently, neither any existing commercial robotic catheterization platform, nor any research prototype providing full manipulation of 
catheter, could be safely operated in MRI environment. There is also no well-established robot-human interface capable of continuously update surgical roadmap and catheter location based on MR images. 
- This system is the first catheter robot to be integrated with MRI-compatible actuation, MR-based tracking system, and the 3D surgical roadmap registered with intra-operative MR images. 
- It represents a major step in achieving several goals: i) enhancing the catheter manipulation and access to desired surgical region, thus decreasing the chances of recurrence (e.g. currently 30% in atrial fibrillation and 50% in ventricular tachycardia after electrophysiology procedure), 
compensating the cost of using MRI and reducing the overall expenditure; 
ii) improving the safety of catheter navigation, thereby decreasing the rates of undesired damage; 
iii) enhancing the catheter control, thus facilitating the shorter learning curve for surgeons and better treatment for more complex cases. 



This system is the first catheter robot to be integrated with MRI-compatible actuation, MR-tracking system, and the 3D surgical roadmap registered with intra-operative MR images. The successfully developed components of this system could be further implemented in other robot-assisted interventions, particularly those using MRI navigation on rapidly physiological-changed tissues. Our study may serve as a benchmark for the design and integration of MR-conditional robotic devices


**** References
- S.Nazarian, A. Kolandaivelu, M. M. Zviman, G. R. Meininger, R. Kato, R. C. Susil, A. Roguin, T. L. Dickfeld, H. Ashikaga, H. Calkins, R. D. Berger, D. A. Bluemke, A. C. Lardo, and H. R. Halperin, "Feasibility of real-time magnetic resonance imaging for catheter guidance in electrophysiology studies," Circulation, vol. 118, pp. 223--229, 2008
- E. J. Schmidt, R. P. Mallozzi, A. Thiagalingam, G. Holmvang, A. d'Avila, R. Guhde, R. Darrow, G. S. Slavin, M. M. Fung, J. Dando, L. Foley, C. L. Dumoulin, and V. Y. Reddy, "Electroanatomic Mapping and Radiofrequency Ablation of Porcine Left Atria and Atrioventricular Nodes Using Magnetic Resonance Catheter Tracking," Circulation-Arrhythmia and Electrophysiology, vol. 2, pp. 695-+, Dec 2009
- D. C. Peters, J. Hsing, K. V. Kissinger, B. Goddu, R. Nezafat, J. E. Taclas, M. E. Josephson, J. V. Wylie, and W. J. Manning, "T2-Weighted Imaging of the Left Atrium Acutely After Pulmonary Vein Isolation Demonstrates Wall Thickening and Edema," ISMRM Proceedings, 2009.
- M. Shurrab, R. Schilling, E. Gang, E. M. Khan, and E. Crystal, "Robotics in invasive cardiac electrophysiology," Expert Rev Med Devices, vol. 11, pp. 375-81, Jul 2014.

**** Figure


* Dynamic modeling
*** elements for modeling
**** motor gear connected to the stepper motor power source
**** piston 1
     connected to the motor gear **** water 1
     water inside upper pipeline
**** spring-damper 1
     between piston 1 and water 1
**** spring-damper 2
     between water 1 and piston 2
**** piston 2
     connected to the gear end effector
**** gear end effector 
     connected to the end effector
**** piston 3
     connected to the gear end effector
**** spring-damper 3
     between piston 3 and water 2
**** water 2
     water inside lower pipeline
**** spring-damper 4
     between water 2 and piston 4
**** piston 4
     connected to the motor gear *** symbol notations
    
    | <30>                           | <20>                 | <10>       | <30>                           | <15>            |
    | Description                    | symbols              | physical parameters (P)/kinematics parameters (K)/force variable (F) | how to get                     | component       |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | motor gear inertia             | I_m                  | P          | experimment                    | motor gear      |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | motor gear radius              | r_m                  | P          | design                         | motor gear      |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | motor gear angular displacement | \theta_m (cw \+)     | K          | system input/output            | motor gear      |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | torque by stepper motor        | \tau_m               | F          | system input                   | motor gear      |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | frictional torque at motor gear joint | \hat \tau_m          | F          | \mu_m,f_R,r_m                  | motor gear      |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | frictional coefficient at motor gear joint | \mu_m                | P          | experiment                     | motor gear      |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | reaction forces of the moment couple at the two contact points | f_m                  | F          | internal                       | motor gear      |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | pressure force from water      | f_wp                 | F          | f_R                            |                 |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | reaction force at joint        | f_R                  | F          | f_wp                           | motor gear      |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | displacement of piston 1       | x_1 (right \+)       | K          | \theta_m                       | piston 1        |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | mass of piston 1               | m_m                  | P          | design                         | piston 1        |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | spring constant                | k                    | P          | k=B\frac{A}{L}                 | water 1         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | damping coefficient of water   | d                    | P          | experiment                     | water 1         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | bulk constant of water         | B                    | P          | design (literature)            | water 1         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | cross section area of pipeline 1 | A                    | P          | design                         | pipeline 1      |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | length of pipeline 1           | L                    | P          | design                         | pipeline  1     |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | displacement of water 1        | x_{w1}               | K          | internal                       | water 1         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | mass of water          1       | m_w                  | P          | design                         | water 1         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | friction inside pipeline       | \hat f_{w1}          | F          | \hat f_{w1} = H_{f1} \rho g A  | water 1         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | frictional weight of pipeline  | H_{f1}               |            | H_{f1} = \frac{\bar f L ({\dot x_{w1}})^2}{2gd}$ | water 1         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | frictional constant of pipeline | \bar f               | P          | \bar f = \frac{64}{Re}         | water 1         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | Reynolds number                | Re                   | P          | design (literature)            | water 1         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | displacement of piston 2       | x_2 (right \+)       | K          | \theta_e                       | piston 2        |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | mass of piston 2               | m_e                  | P          | design                         | piston 2        |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | inertia of effector gear       | I_e                  | P          | design                         | effector gear   |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | radius of effector gear        | r_e                  | P          | design                         | effector gear   |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | resulting moment               | \tau_e               | F          | \tau_e = f_e r_e               | effector gear   |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | resulting couple               | f_e                  | F          | \tau_e = f_e r_e               | effector gear   |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | reaction force at joint        | f_{Re}               | F          | f_{Re} = 2 f_{wp}              | effector gear   |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | frictional torque              | \hat \tau            | F          | \mu_e , f_{Re}, r_e            | effector gear   |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | angular displacement of effector gear | \theta_e             | K          | system output                  | effector gear   |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | displacement of piston 3       | x_3 (left \+)        | K          | \theta_e                       | piston 3        |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | displacement of water 2        | x_{w2}               | K          | internal                       | water 2         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | mass of water 2                | m_w                  | P          | design                         | water 2         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | friction inside pipeline       | \hat f_{w2}          | F          | H_{f2} = \frac{\bar f L ({\dot x_{w2}})^2}{2gd}$ | water 2         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | frictional weight of pipeline  | H_{f2}               | F          | H_{f2} = \frac{\bar f L ({\dot x_{w2}})^2}{2gd}$ | water 2         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | displacement of piston 4       | x_4 (left \+)        | K          | \theta_m                       | piston 4        |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | mass of piston 4               | m_m                  | P          | design                         | piston 4        |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|

    

*** free body diagrams 

*** combine equations and Find necessary constraint equations
    |               |                                                                                                                                                                                             |                   |                     |
    | rigid body    | equations of motion                                                                                                                                                                         | unknown variables | number of equations |
    |---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------|
    | motor gear    | \tau_m - \hat \tau_m = I_m(\ddot \theta_m)                                                                                                                                                  |                   |                     |
    |               | \hat \tau_m = \mu_m abs(f_R) r_m                                                                                                                                                            |                   |                     |
    |               | f_R = 2f_{wp}                                                                                                                                                                               |                   |                     |
    |               | \tau_m = f_m r_m                                                                                                                                                                            |                   |                     |
    |               |                                                                                                                                                                                             |                   |                     |
    |               | \tau_m - 2 \mu_m r_m abs(f_{wp})  = I_m (\ddot \theta_m)                                                                                                                                    | \f_{wp}           |                     |
    |               |                                                                                                                                                                                             | (f_m,\tau_m)      |                     |
    |---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------|
    | piston 1      | f_m - k(x_1 - x_{w1}) - d({\dot x}_1 - {\dot x}_{w1}) = m_m {\ddot x_1}                                                                                                                     |                   |                     |
    |               | x_1 = \theta_m r_m                                                                                                                                                                          |                   |                     |
    |               |                                                                                                                                                                                             |                   |                     |
    |               | \frac{\tau_m}{r_m} - k(\theta_m r_m - x_{w1}) - d( {\dot \theta}_m r_m - {\dot x}_{w1}) = r_m m_m {\ddot \theta}_m                                                                          | x_{w1}            |                     |
    |               |                                                                                                                                                                                             | (f_m)             |                     |
    |---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------|
    | water 1       | k(x_1-x_{w1}) + d({\dot x}_1 - {\dot x}_{w1}) - k(x_{w1}-x_2) - d({\dot x}_{w1} - {\dot x}_2) - \hat f_{w1} = m_w {\ddot x}_{w1}                                                            |                   |                     |
    |               | \hat f_{w1} = H_{f1} \rho g A                                                                                                                                                               |                   |                     |
    |               | H_{f1} = \frac{\bar f L ({\dot x_{w1}})^2}{2gd}                                                                                                                                             |                   |                     |
    |               | \bar f = \frac{64}{Re}                                                                                                                                                                      |                   |                     |
    |               | x_1 = \theta_m r_m                                                                                                                                                                          |                   |                     |
    |               | {\dot x}_1 = r_m {\dot \theta}_m                                                                                                                                                            |                   |                     |
    |               | x_2 = \theta_e r_e                                                                                                                                                                          |                   |                     |
    |               | {\dot x}_2 = r_e {\dot \theta}_e                                                                                                                                                            |                   |                     |
    |               |                                                                                                                                                                                             |                   |                     |
    |               | r_m k(\theta_m) + r_m d({\dot \theta_m}) - 2 k(x_{w1}) - 2 d({\dot x}_{w1})  + r_e k(\theta_e) + r_e d({\dot \theta}_e) - \frac{32 \rho A L ({\dot x_{w1}})^2 }{Re d}  = m_w {\ddot x}_{w1} |                   |                     |
    |---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------|
    | piston 2      | - f_e + k(x_{w1}) - k(x_2) + d({\dot x}_{w1}) - d({\dot x}_2) = m_e {\ddot x}_2                                                                                                             |                   |                     |
    |               |                                                                                                                                                                                             |                   |                     |
    |               | - f_e + k(x_{w1}) - r_e k(\theta_e) + d({\dot x}_{w1}) - r_e d({\dot \theta}_e) = r_e m_e {\ddot \theta}_e                                                                                  |                   |                     |
    |---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------|
    | effector gear | \tau_e - \hat \tau_e = I_e({\ddot \theta_e})                                                                                                                                                |                   |                     |
    |               | \hat \tau_e = \mu_e abs(f_{Re}) r_e                                                                                                                                                         |                   |                     |
    |               | f_{Re} = 2f_{wp}                                                                                                                                                                            |                   |                     |
    |               | \tau_e = f_e r_e                                                                                                                                                                            |                   |                     |
    |               |                                                                                                                                                                                             |                   |                     |
    |               | f_e r_e - \mu_e abs(2f_{wp}) r_e = I_e (\ddot \theta_m)                                                                                                                                     |                   |                     |
    |---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------|
    | piston 3      | - f_e - k(x_{3}) + k(x_{w2}) - d({\dot x}_3) + d({\dot x}_{w2}) = m_e {\ddot x}_3                                                                                                           |                   |                     |
    |               | x_3 = x2 = \theta_e r_e                                                                                                                                                                     |                   |                     |
    |               |                                                                                                                                                                                             |                   |                     |
    |               | - f_e - r_e k(\theta_e) + k(x_{w2}) - r_e d({\dot \theta}_e) + d({\dot x}_{w2}) = r_e m_e {\ddot \theta}_e                                                                                  |                   |                     |
    |---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------|
    | water 2       | k(x_3-x_{w2}) + d({\dot x}_3 - {\dot x}_{w2}) - k(x_{w2}-x_4) - d({\dot x}_{w2} - {\dot x}_4) - \hat f_{w2} = m_w {\ddot x}_{w2}                                                            |                   |                     |
    |               | \hat f_{w2} = H_{f2} \rho g A                                                                                                                                                               |                   |                     |
    |               | H_{f2} = \frac{\bar f L ({\dot x_{w2}})^2}{2gd}                                                                                                                                             |                   |                     |
    |               | \bar f = \frac{64}{Re}                                                                                                                                                                      |                   |                     |
    |               | x_4 = x_1 = \theta_m r_m                                                                                                                                                                    |                   |                     |
    |               |                                                                                                                                                                                             |                   |                     |
    |               | r_e k(\theta_e) + r_e d({\dot \theta}_e) - 2k(x_{w2}) - 2d({\dot x}_{w2}) + r_m k(\theta_m) + r_m d({\dot \theta}_m) - \frac{32 \rho A L ({\dot x_{w2}})^2 }{Re d}  = m_w {\ddot x}_{w2}    |                   |                     |
    |---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------|
    | piston 4      | f_m + k(x_{w2}) - k(x_4) + d({\dot x}_{w2}) - d({\dot x}_4) = m_m {\ddot x}_4                                                                                                               |                   |                     |
    |               | \tau_m = f_m r_m                                                                                                                                                                            |                   |                     |
    |               |                                                                                                                                                                                             |                   |                     |
    |               | \frac{\tau_m}{r_m} + k(x_{w2}) - r_m k(\theta_m) + d({\dot x}_{w2}) - r_m d({\dot \theta}_m) = r_m m_m {\ddot \theta}_m                                                                     |                   |                     |
    |---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------|




|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---|
| f_e r_e - 2 \mu_e r_e abs(f_{wp}) = I_e (\ddot \theta_e)                                                                                                                                          |   |
| \tau_m - 2 \mu_m r_m abs(f_{wp})  = I_m (\ddot \theta_m)                                                                                                                                          |   |
| \frac{\tau_m}{r_m} + k(x_{w2}) - r_m k(\theta_m) + d({\dot x}_{w2}) - r_m d({\dot \theta}_m) = r_m m_m {\ddot \theta}_m                                                                           |   |
| \frac{\tau_m}{r_m} - k(\theta_m r_m - x_{w1}) - d( {\dot \theta}_m r_m - {\dot x}_{w1}) = r_m m_m {\ddot \theta}_m                                                                                |   |
| - f_e + k(x_{w1}) - r_e k(\theta_e) + d({\dot x}_{w1}) - r_e d({\dot \theta}_e) = r_e m_e {\ddot \theta}_e                                                                                        |   |
| - f_e - r_e k(\theta_e) + k(x_{w2}) - r_e d({\dot \theta}_e) + d({\dot x}_{w2}) = r_e m_e {\ddot \theta}_e                                                                                        |   |
| r_m k(\theta_m) + r_m d({\dot \theta_m}) - 2 k(x_{w1}) - 2 d({\dot x}_{w1})  + r_e k(\theta_e) + r_e d({\dot \theta}_e) - \frac{32 \rho A L ({\dot x_{w1}})^2 }{Re \cdot d}  = m_w {\ddot x}_{w1} |   |
| r_e k(\theta_e) + r_e d({\dot \theta}_e) - 2k(x_{w2}) - 2d({\dot x}_{w2}) + r_m k(\theta_m) + r_m d({\dot \theta}_m) - \frac{32 \rho A L ({\dot x_{w2}})^2 }{Re \cdot d}  = m_w {\ddot x}_{w2}    |   |
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---|
| f_e r_e - 2 \mu_e r_e abs(f_{wp}) = I_e (\ddot \theta_e)                                                                                                                                          |   |
| \tau_m - 2 \mu_m r_m abs(f_{wp})  = I_m (\ddot \theta_m)                                                                                                                                          |   |
| k(x_{w1}-x_{w2}) + d({\dot x}_{w1}-{\dot x}_{w2}) = 0                                                                                                                                             |   |
| k(x_{w1}-x_{w2}) + d({\dot x}_{w1}-{\dot x}_{w2}) = 0                                                                                                                                             |   |
| -> x_{w1} = x_{w2} = x_w                                                                                                                                                                          |   |
|                                                                                                                                                                                                   |   |
| r_m k(\theta_m) + r_m d({\dot \theta_m}) - 2k(x_{w1}) - 2d({\dot x}_{w1}) + r_e k(\theta_e) + r_e d({\dot \theta}_e) - \frac{32 \rho A L ({\dot x_{w1}})^2 }{Re \cdot d}  = m_w {\ddot x}_{w1}    |   |
| r_e k(\theta_e) + r_e d({\dot \theta}_e) - 2k(x_{w2}) - 2d({\dot x}_{w2}) + r_m k(\theta_m) + r_m d({\dot \theta}_m) - \frac{32 \rho A L ({\dot x_{w2}})^2 }{Re \cdot d}  = m_w {\ddot x}_{w2}    |   |
| -> r_m k(\theta_m) + r_m d({\dot \theta_m}) + r_e k(\theta_e) + r_e d({\dot \theta}_e) - 2k(x_{w}) - 2d({\dot x}_w) - \frac{32 \rho A L ({\dot x_{w}})^2}{Re \cdot d} = m_w {\ddot x}_w           |   |
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---|
| I_e (\ddot \theta_e) + 2 \mu_e r_e abs(f_{wp}) - f_e r_e = 0                                                                                                                                      |   |
| I_m (\ddot \theta_m) + 2 \mu_m r_m abs(f_{wp}) - \tau_m = 0                                                                                                                                       |   |
| m_w {\ddot x}_w + \frac{32 \rho A L ({\dot x_{w}})^2}{Re \cdot d} + 2d({\dot x}_w) + 2k(x_{w}) - r_m d({\dot \theta_m}) - r_m k(\theta_m) - r_e k(\theta_e) - r_e d({\dot \theta}_e)  = 0         |   |
| - f_e = - k(x_{w1}) + r_e k(\theta_e) - d({\dot x}_{w1}) + r_e d({\dot \theta}_e) + r_e m_e {\ddot \theta}_e                                                                                      |   |
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---|
| I_m (\ddot \theta_m) + 2 \mu_m r_m abs(f_{wp}) - \tau_m = 0                                                                                                                                       |   |
| m_w {\ddot x}_w + \frac{32 \rho A L ({\dot x_{w}})^2}{Re \cdot d} + 2d({\dot x}_w) + 2k(x_{w}) - r_m d({\dot \theta_m}) - r_m k(\theta_m) - r_e k(\theta_e) - r_e d({\dot \theta}_e)  = 0         |   |
| (I_e + (r_e)^2 m_e) (\ddot \theta_e) + (r_e)^2 d({\dot \theta}_e) + (r_e)^2 k(\theta_e) - r_e d({\dot x}_{w}) - r_e k(x_{w}) + 2 \mu_e r_e abs(f_{wp})  = 0                                       |   |
|                                                                                                                                                                                                   |   |

| \ddot \theta_m | \ddot x_w | \ddot \theta_e    | \dot \theta_m | \dot x_w | \dot \theta_e | (\dot x_w)^2                   | \theta_m | x_w    | \theta_e  | u                       |
|----------------+-----------+-------------------+---------------+----------+---------------+--------------------------------+----------+--------+-----------+-------------------------|
| I_m            |           |                   |               |          |               |                                |          |        |           | 2 \mu_m r_m abs(f_{wp}) |
|                | m_w       |                   | -r_m d        | 2 d      | -r_e d        | \frac{32 \rho A L}{Re \cdot d} | -r_m k   | 2 k    | -r_e k    |                         |
|                |           | I_e + (r_e)^2 m_e |               | -r_e d   | (r_e)^2 d     |                                |          | -r_e k | (r_e)^2 k | 2 \mu_e r_e abs(f_{wp)  |
|                |           |                   |               |          |               |                                |          |        |           |                         |

\begin{pmatrix}
I_m & 0 & 0\\
0 & m_w & 0\\
0 & 0 & I_e + (r_e)^2 m_e
\end{pmatrix}
\begin{pmatrix}
\ddot \theta_m\\
\ddot x_w\\
\ddot \theta_e
\end{pmatrix}
+ 
\begin{pmatrix}
0 & 0 & 0\\
-r_m d & 2 d & -r_e d\\
0 & -r_e d & (r_e)^2 d
\end{pmatrix}
\begin{pmatrix}
\dot \theta_m\\
\dot x_w\\
\dot \theta_e
\end{pmatrix}
+ 
\begin{pmatrix}
0 & 0 & 0\\
0 & \frac{32 \rho A L}{Re \cdot d} & 0\\
0 & 0 & 0
\end{pmatrix}
\begin{pmatrix}
(\dot \theta_m)^2\\
(\dot x_w)^2\\
(\dot \theta_e)^2
\end{pmatrix}
+ 
\begin{pmatrix}
0 & 0 & 0\\
-r_m k & 2 k & -r_e k\\
0 & -r_e k & (r_e)^2 k
\end{pmatrix}
\begin{pmatrix}
 \theta_m\\
 x_w\\
 \theta_e
\end{pmatrix}
+ 
\begin{pmatrix}
2 \mu_m r_m abs(f_{wp})\\
0\\
 2 \mu_e r_e abs(f_{wp})
\end{pmatrix}
=0

*** check friction model between gear and shaft (sliding friction)
*** verification


* paper draft for a journal
** Title
   Design of a Robotic Platform for MRI-guided Cardiac Electrophysiology (EP)
** Introdution
*** Cardiac electrophysiology is an effective surgical treatment for diagnosis and treatment of heart
**** What is Cardiac Electrophysiology  (Definition)
     - In EP, electrophysiologists insert a 1.5m catheter from femoral vein to the heart chamber where radiofrequency ablation (RFA) is conducted via the catheter tip on the lesion tissue to isolate the abnormal electrophysiological signals that cause arrhythmias
**** Current methods using robotic platform/procedure and associated problems: learning curve, cost, preparation time, accuracy, efficiency 
     - In conventional EP, fluoroscopy and ultrasound are adopted to visualize the catheter configuration inside the heart chamber.
**** Deduce to the need of MRI-guided
     - However, the visualization can only provide rough information inside the heart chamber for RFA.
*** MRI techniques can facilitate EP, however, there is still no MR-compatible platform for EP
**** Why catheterization has to be done inside MRI
     - Magnetic resonance imaging (MRI) offers excellent images contrast for cardiovascular soft tissue for construction of clear 3D cardiac roadmap [3,4], which enables intra-operative (intra-op) visualization of RFA-induced physiological changes, thus allowing electrophysiologists to promptly determine whether the treatment of particular lesions is complete or requires further ablation.
     - T2-weighted MRI [5,6] can also readily visualize the edema [6] and scar tissue [7] from successful or incomplete RFA
**** Current progress of MR-compatible platform, list some examples of catheter robot.
     - Sensei Robotic system [12] is a well-known commercial platform for intra-cardiac EP intervention
     - Hansen Sensei X, Amigo Remote Catheter System, Stereotaxis Niobe are industry-leading EP robots
     - All the above robots are MR-incompatible
     - Currently, no MR-compatible commercial robotic platform for EP is available
     - [31] is actuated by non-ferromagnetic,  ultrasonic motors driven by electric current, providing only two DOFs of catheter. However, because the motors are placed close to the scanner, the driving and encoding signals would induce electromagnetic (EM) noise to MRI.
     - Ultrasonic motors reduce of SNR ratio, though can be treated by installing amplifier and carefully shield electronics at the expense of system cost [Su2012]
     - Recently, a MR-compatible pneumatic stepper motor has been developed [39], showing   better performance than existing ones in [57-59], however, the operation speed is still too slow for driving catheter advancement or rotation.
     - "Pneumatic actuators are MR-compatible and do not cause SNR reduction, but they do require a complicated installation that involves locating a control unit, power supplies, amplifiers and valves external to the MRI shielded room (Patriciu et al., 2007; Li et al., 2011; Tokuda et al., 2012). Furthermore, the pneumatic transmission lines lower the bandwidth and, in combination with the spatial con- straints of the MRI bore, complicate robot design (Song et al., 2011).” [Vartholomeos2013]
**** [What makes development/applications of MR-compatible robots difficult]
     - Complex EM-shielded enclosure is required to surround on all sides of the motor drivers
     - It is also technically difficult to filter the motor control signals at high frequency, but without degrading the motor operation [33].
**** [Deduce to the need of implementation MR-compatible actuators for EP]
     - Actuators driven by other non-electromagnetical mechanism such as pressured air flow are attracting attention for development of MR-compatible robotic platform [34]

*** Hydraulic mechanism can provide MR-compatible, efficient and precise actuation for EP.
**** [Any used for medical application? ]
**** [What is rolling diaphragm (RD) and its characteristics ]
     - Frictionless
**** [Any other MR-compatible actuation mechanism? Why they are not chosen in this research?]
*** We design and fabricate the first MR-compatible, efficient robot for cardiac EP
**** State clearly main features of our design that facilitate cardiac catheterization 
- Rolling diaphragms are actuated by pressurized clear air (at 30-60 psi) supplied by the medical piped gas systems guarantees zero EM interference with the MRI
- Fast and precise manipulation of the advancement, steering and rotation of catheter can be achieved
  
** Clinical Motivation /MRI-Guided EP
    - (may be combined with the introductin section)
*** Cardiac EP for heart arrhythmia and ablation is the one demanding for dexterous control of catheter for tissue ablation
- Show data support obtained from American Heart Association (AHA) and Center for Disease Control (CHC)
*** The basic operation of EP is described as follows
- [Fig: illustrating the basic operation of EP, and the catheter configuration inside the anatomy]
- [Emphasize particular procedure and associated problems/difficulties]
- [Insertion done by junior surgeon]
*** A MR-guided catheterization can facilitate diagnosis and treatment
- How?
- Fig: showing the ablation features visualized on late-gadolinium MR images
*** Deduce to the need of our design
    
** The MR-compatible Robotic Platform
A MR-compatible, high performance robot has been developed for EP operation. Fig. shows the appearance of the robot. The robot is used to manipulate a catheter tip that locates near to the target heart tissue. During an EP operation, a surgeon use a controller to operate the catheter (Fig. ). In order to achieve effective manipulation of a catheter during a MRI-guided EP, the robot is developed to fulfil the following requirements:
+ The robot must be solely made of MR-compatible material.
+ The robot can give advancement, steering and rotation of a catheter that mounted on the robot during EP operation.
+ The robot is capable of response fast enough to the surgeon’s control inputs with negligible backlash.
+ The actuators have to provide precise displacement with sufficient output torque.
+ The size of the robot must not be too bulky and compactly assembled.

*** MR-compatible hydraulic actuator
**** The core of the MR-compatible platform is an efficient hydraulic actuator capable of providing precise bidirectional rotation or translation actuation depicted in Fig. .  
The actuator consists of two identical hydraulic piston-actuators, a gear, two long flexible tubes (>10m) and a hydraulic pump. 
Each piston-actuator consists of a piston, a rolling diaphragm and a cylinder. The two tubes and the hydraulic pump connect the two piston-actuators with fixed amount of pressurized fluid filled inside. 
The rolling diaphragms act as flexible seals. The two piston-actuators and the gear are assembled such that the gear transmits translational motion of one piston to other piston in opposite direction. 
When the hydraulic pump forces the pressurized fluid from one cylinder to another by a piston inside, the change of the fluid volume in one cylinder induces pressure on the wall of the rolling diaphragm and pushes the piston out. 
Simultaneously, the other piston is push into the other cylinder by the force transmitted from the gear and the atmospheric pressure due to the decrease of fluid inside the cylinder. 
As a result, the pistons provide bidirectional translation and the gear provides bidirectional rotation.
**** All the components except the hydraulic pump, which is isolated in a zero-EM-interference room, are made of MR-compatible and medical safe materials.
**** The proposed design together with the use of pressurized fluid can prevent backlash at the gear.
The gear and the piston shafts are not seamlessly contacted. Backlash refers to the phenomenon when the piston leaves contact with the gear such that motion cannot be transmitted. 
The pressurized fluid inside the two cylinders always provides force to push the two pistons out. 
Consequently, the teeth of the piston are forced to seamlessly contact with the teeth of the gear, thereby preventing backlash (Fig. ).
- (Existing bidirectional actuator designs such as [] usually has only one shaft and thus backlash is inevitable (Fig. ).)
**** The proposed design effectively converts the change of fluid volume inside the cylinders to the translational motion of the piston, based on the characteristics of negligible backlash and all the piston, rolling diaphragms and the gear are seamlessly assembled. 
Also, the coplanarity of the gear and the two piston shafts helps to effectively transmit the translational motion from one piston shaft to another. 
Moreover, the rolling diaphragms provide negligible friction between the pistons and the inner walls of the cylinders [] such that the energy loss during operation can be reduced.  
Although energy loss and response delay will likely occur because the volume of the pressurized fluid and the volume of the long flexible tubes will possibly be altered during operation, in practice and as will be shown in section XXX, the response is negligible that the piston react once the surgeon gives control input.
**** There are cases that require larger range of rotation.
For instance, the rotation of catheter may need more than 360 degree to produce a 360 degree sweeping motion of the tip inside the heart chamber, because torsion may occur in the long (>1.5m) catheter. 
However, the range of the rotation of the gear is limited by the stroke length and the diameter of the rolling diaphragms, because the gear is placed between the two piston shafts, as illustrated in Fig. . 
**** Two types of assembly are designed for different requirement of range of rotation of the gear.
Figure depicts the two designs in which the two cylinders are assembled in parallel-shape and in V-shape. 
In the following context, we refer them as the P-type actuator and the V-type actuator, respectively. 
The V-type actuator has larger range of rotation than that of the P-type because a smaller gear can be installed and thus produces larger range of rotation of the gear.
There is a trade-off between the maximum range of rotation and the resolution. 
Under the same-sized gear teeth and the same change of fluid volume inside the cylinder, the V-type actuator has larger range of rotation but also coarse resolution, because small gear has larger gear ratio. 
– (Although the V-shape assembly also has limitation of maximum piston shaft length.)
- (geometric equation relating the )
**** Assume that all the elastic effect of the rolling diaphragm is negligible such that the change of the fluid volume inside one of the cylinder of the hydraulic actuator $\Delta V_c$  is related to the displacement of the piston shaft $\Delta h$  by:
    \Delta V_c = \pi r^2_c \Delta h		(1)
where $r_c$ is the inner radius of the cylinder. 
In ideal case where the fluid is incompressible and the volume of inside the long flexible tube is constant, $\Delta V_c$ is solely induced by the change of volume inside the hydraclic pump $\Delta V_p \propto \Delta l$ which is proportional to the displacement of the piston inside hydraulic pump $\Delta l$. 
Therefore, the displacement of the piston shaft $\Delta h$ of the actuator is also proportional to $\Delta l$ :
	    \Delta V_c = \pi r^2_c \Delta h
\implies    \Delta h \propto \Delta l	
	    \Delta h = k_t \Delta l			(2)
where $k_t$ is the input-output ratio (I-O ratio) of the piston shaft. 
For the case without backlash at the gear, the angular change of the gear $\Delta \theta$ is proportional to the displacement of the piston shaft $\Delta h$ and thus also proportional to $\Delta l$:
	    \Delta \theta \propto \Delta l		
\implies    \Delta \theta = k_g \Delta l		(3)
where $k_g$ is the I-O  ratio of the gear.
- (The proportionality in (2) and (3) vanishes if the fluid volume is not constant or backlash occurs.)
- (need more complicated model including fluid dynamics to explain the time delay?)
**** [The expected characteristics/advantages:, stroke and accuracy]
- fast response
- output torque

*** The MR-compatible robotic platform
**** The proposed hydraulic actuators are compactly assembled in a MR-compatible robotic platform depicted in Fig. , which provides effective steering (bending), fine advancement, rotation and coarse advancement of a catheter mounted on it. 
The design technical specifications of our current prototype are summarized in Table 1.
**** The steering and the advancement of the catheter are provided by two P-type actuators as depicted in Fig. . 
The platform tightly holds the steering wheel of the catheter and the catheter handle such that the gears of the two P-type actuators directly actuate the catheter with fine resolution and without backlash.
**** The rotation and the coarse advancement of the catheter are provided by two V-type hydraulic actuators as depicted in Fig. .
The V-type actuator is used instead of the P-type actuator because catheter may need larger range of rotation as mentioned before. 
The V-type actuators provide both the rotation and the coarse advancement via intermediate gears to magnify the range of motion and thus have coarser resolution than the steering and advancement and may encounter the problem of backlash.
- (How the specific requirements for EP are matched?)
- [Table of design parameters: dimension, components, DoF requirement, ranges of motion, resolution (or input-output ratios of each DOF), material name et al]

** Control interface (combine with B?)
*** Fig. depicts the schematic diagram for carrying out EP by the MR-compatible robotic platform.
- [Schematic diagram: including connections between motor drivers, valves, mcu, MRI scanner room, control rooms, etc…]
- [which components are in the MRI-scanner room and the control room?]
- [Fig: figure of the controller]
- [Description of how the EP is carried out by the user using the robot:]
  - [Surgeon uses controller to control the platform for cardiac ablation, according to the (real-time) MRI which reflects catheterization in 3D roadmap]
  - [the controller input is sent to the microprocessor in the control room to actuate robotic platform]

** Experimental Evalulations
*** To examine the applicability of the proposed design for EP, the robotic platform depicted in Fig. was constructed
- [Fig. of real robot, long flexible tubes, cylinder pump]
- Actuation experiments were conducted to evaluate the actuation performance in terms of time delay, precision (related to backlash) and operation speed, output torque
- MR-compatibility tests were also carried out to investigate the effects to MRI.

*** MR-compatibility test
- Image artifacts
- SNR analysis
- [Fig: depicting the zero-artifact using 1-2 significant MRI sequences]
- (actuation inside MRI scanner?)

*** Performance analysis
Specification
- resolution, speed, I/O ratios 
   depending on the resolution of the cylinder and I/O ratio
- output torque
- range of motion


**** Step response
- rise time, overshoot, settling time, time constant


**** Frequency response
- time delay
- bode plot

**** hysterysis and backlash


**** workspace analysis with catheter

** Discussion
*** Highlight the significant novelties - 1st MR-compatible robotic platform for EP
*** Definition/justification of our proposed performance indices, such as time consuming, efficiency
*** Contribution of this work. How it could be extended to other clinical applications?

** Conclusion
*** The first MR-compatible robot for EP
    - Efficient and effective actuation of rotation, advancement and bending
    - Other main features
    - ...
*** Future work
    - Extensible to other clinical applications/surgeries
    - Difficulty even using robot, and pave a way to our future work in regards of model-free catheter control
 
      

* paper draft for RAM
  :PROPERTIES:
  :Directory: file:~/Work/HKU/MRcompatible_platform/RAM
  :END:
  
  - try to pick out the most important message at every page
** Title
   Enabling Techniques for MRI-guided and Robot-assisted Intracardiac Catheterization

** Abstract - the 1st paragraph (100 words)

- one short paragraph
  - motivation/advantages using MRI in MIS
    - aim of this paper
      - motivate the use of MRI in robot-assisted MIS 
      - exploit MRI in robot-assisted MIS
      - how to incorporate MRI in robot-assisted MIS
      - present a MR-compatible robotic platform for Cardiac Electrophysiological (EP) that was demonstrated in the Surgical Robot Challenge

** Introduction - MRI-guided robot-assisted MIS (800 words)

- What is MIS and its advantages
  - brief description of MIS
  - small wound, faster recovery
  - requires high precision of tool manipulation within a relatively small, confined workspace
  - most surgeons currently conduct MIS based on pre-op MRI, intra-op 2D, rough images
    - depend on the experience of surgeons
  - example: EP in cardiac catheterization, deep brain stimulation (DBS) in neurosurgery

- what is MRI and the advantage of intra-operative MRI
  - brief description of intra-operative (Late gadolinium enhancement) T2-weighted MRI 
    - 
  - MRI provide better quality (intra-operative) images
    - better quality and high contrast images of soft tissue
    - monitoring the physiological and pathological change of region of interest during MIS
    - construction of roadmap for specific surgical goals
      - e.g. registering lesion targets on MR-images for EP treatment
      - e.g. in DBS treatment, planning of placing an electrode accurately at the subthalamic nucleus (STN) in the deep brain under stereotactic guidance.
  - example in EP:
    - enable intra-operative assessment of ablation location and progress
      - construction of cardiac roadmap [aliot2009ehra/hrs, nazarian2008feasibility]: registering lesion targets on MR-images for EP treatment
      - t2-weighted cardiac MRI [schmidt2009electroanatomic, peters2009t2]
      - edema [peters2009t2weighted] and scar tissue [ren2007apotential]
  - example in DBS:
    - fMRI/DT-MRI reveals critical structure related to the deep brain nuclei, the corticospinal tract, red nucleus and third nerve nucleus for planning of placing an electrode accurately at the subthalamic nucleus (STN) under stereotactic guidance [XXX].
    - 

- Technical difficulties of incorporating MRI in MIS
  - requires fast image processing 
    - image processing is computationally intensive: difficult to carry out fast enough to provide intra-operative image
    - realignment of exact, deformed physiological features to pre-planned roadmap
    - rigid image co-registration [ishihara2007mrievaluation] between the pre-and intra-op images would help compensate the 6D-offset due to patient positioning and motion, but rapid morphological changes cause inaccuracies.
    - non-rigid 3D image registrations [relan2011personalitzation, archip2007nonrigid] have been used in the conventional EP, but mostly applied only once after the EAM for improved integration between map and the pre-op roadmap
    - processing of non-rigid registrations is normally computationally intensive (>5sec)
  - requires special actuation method
    - tele-manipulate the surgical tools via robotic platform so that surgeons do not need to expose to high magnetic field 
    - conventional actuation method is usually not MR-compatible
  - requires sensors that can work inside MRI scanner
    - positional feedback
    - force feedback
  

- last paragraph sums up and connects to the next section
  -          


** Enabling techniques 

   Multidisciplinary advanced techniques make MRI-guided robot-assisted intracardiac catheterization possible. This section introduces timely technologies that enable 1) acquistion of high quality MR images intra-operatively; 2) robots to work in close proximity to the MRI scanner for precise and effective catheterization; and 3) positional feedback of the catheter under the MR environment. 


{The proposed system for MRI-guided cardiac catheterization involves timely research issues, aiming to: 1) provide fast intra-operative (intra-op) updates of the cardiac EP roadmap based on MR images; 2) enable precise and dexterous manipulation which is driven by MR-conditional actuators; 3) implement close-loop robot control with real-time MR-tracking system. Three key components corresponding to the above issues will be introduced as follows, which are also integrated in the system. kw}
{Developing robotic systems for MRI-guided robot-assisted intracardiac catheterization involves multidisciplinary researches of engineering. In particular, 1) intra-operative update of high quality cardiac images based on MR images, 2) MR-compatible actuation mechanism for precise and effective maneuver of catheter and 3) accurate and real-time tracking of catheter under MRI system. This section introduces timely techniques about these fundamental components}

*** Intra-operative image processing

Intra-operative MRI technologies open up new possibilities in the realm of image guided intervention. MRI images can be acquired quickly (~100ms) with low latency [XXX]; Thus, surgeons can monitor detailed tissue morphology changes and the location of scars and edema in the specific area of interest from clear and high resolution MR images during surgery. In particular, the MRI images are intra-operatively combined with pre-operative data, such as planned trajectory, segmentation margins and surgical plans for the surgeon’s easy reference. However, misalignments between the intra-operative (intra-op) images and the pre-operative (pre-op) exists due to motion or external disturbance, introducing uncertainty to the surgeons.

**** Image registration
To achieve MRI-guided robot-assisted cardiac interventions, these misalignments must be solved automatically. Non-rigid image registration can re-align the images by computing continuous mappings between the pre- and intra-operative images; Such mappings can provide enhanced interventional guidance by re-aligning the pre-operative data with the intra-operative images. There are two approaches to register the pre-operative data into the intra-operative images: feature-based registration and intensity-based registration [xxx]. The former registration scheme relies on automatically-detected landmarks in the image to compute the correspondence; whilst the latter scheme computes the pixel-wise corresponds between images. 

Intra-operative image registration is a challenging task – the robustness and accuracy of feature-based registration schemes are severely impaired by the increased noise and artifacts in rt-MRI images; yet intensity-based image registration schemes are well-known to be computationally intensive due to numerous pixel-wise operations and 3D convolution involved in the process. Typical computation time for Diffeomorphic Demons [XXX], a widely used non-rigid image registration algorithm, requires >25 minutes to compute register a 3D image using state-of-the-art CPU running in single thread. 

**** Advanced computation architecture for fast image processing
Employing hardware computation accelerators and parallel computation techniques can speed up the image registration process. In particular, utilizing scalable accelerators can exploit spatial parallelism to improve the performance, where 3D MR images can be tessellated into smaller segments before loading into the device memory for parallel computation. Graphical processing units (GPUs) are one of the well-known hardware accelerators. Multi-threaded architecture consisting of numerous GPUs can process multiple blocks of data at the same time. Nonetheless, the memory bandwidth of GPUs imposes a computation bottleneck. Field-programmable gate arrays (FPGAs), another hardware accelerators allowing parallel computation, can resolve the memory bottleneck by exploiting temporal parallelism on top of spatial parallelism [xxx]; Memory transfer between memory and the dataflow engines can be minimized by customizing a pipeline dataflow. Furthermore, FPGAs allow the use of customized data format, resulting in a trade-offs between accuracy and speed. 



- intra-operative image registration
  - Image registration is the process of transforming different sets of data into one coordinate system. (from wiki)
  - data from multiple images, different sensors, times, depths, or viewpoints. (from wiki)
  - terminology: non-rigid image registration
    - especially to cope with deformation of object
      - deformation due to e.g. breathing, anatomical changes (e.g. brain shift)
  - intra-operative image registration: look for continuous mapping between pre-operative (pre-op) and intra-operative (intra-op) image
  - update high resolution pre-op image with rapidly acquired intra-op image
  - DD, transform/ operation in Lie’s group, continues and smooth manifold, all mathematic operations (e.g. composition rather than simple addition) become much more complicated
  - fig: merging high quality pre-op image and intra-op image

- objectives/advantages of intra-operative imaging
  - intra-operatively
  - describing continuous morphological changes of soft tissues 
  - instantly reveal effect of surgical actions
  - fused into and update roadmap 
  - smoothen the repeated workflow of surgical tool path planning 

- intensity-based (IB) and feature-based (FB) approach
  - IB: based on optical-flow, requires higher computation cost, less sensitive to image artifact
  - FB: based on feature correspondence, faster and simpler computation, larger error in matching the feature correspondence
  - thus IB is preferable if the fast enough computation is available

- High-performance computational architecture, enabling technology for fast image processing during surgery
  - GPU-based, higher floating computation throughput than multi-core CPU, highly parallelized design (hundreds of processing unit)
    - A 3D MR image comprising a large number of voxels can be “split” into smaller segments and processed on a multi-threaded architecture consisted of hundreds of stream processors
    - previous study demonstrated order of magnitude speed-up as compared to CPU
    - The growing trend of computation power is much faster than CPU    
  - FPGA-based computation, focus the design of dataflow program and pipelining
    - flexible architecture that optimization of dataflow and pipeline
    - customizable data format, enable trade-off between accuracy and performance
    - overcome memory bandwidth constraint of GPU, minimize memory transfer into/from processor 
    - enable parallelization and scalability
    - deterministic computation time
    - gradient computation as an example:
      - one output can be generated at every clock cycle
      - figure
  - explain the computation mechanism with fig
    - pros and cons 
  - several existing methods
    - pros and cons 

- Diffeomorphic demons registration
  - original demons approach [wang2005validation]
  - our previous work [kwok2014fpgabased,kwok2014mribased]
    - register RF ablation targets on cardiac roadmap for electrophysiology (EP)
    - < 3mm registration error
    - based on local intensity gradient
  - Diffeomorphic demons registration [vercauteren2007nonparametric,vercauteren2009diffeomorphic]
    - not only does it ensure preserving the topology of large deforming tissue structure, but it also allows for smooth forward and inverse transformation
    - thus guaranteeing tighter, more accurate alignment of ablation landmards and electro-anatomic mapping (EAM) contact points with the EP roadmap [vercauteren2009diffeomorphic]
    - both pre-op and intra-op image sets will have to be interpolated in a common region of Cartesian girds to calculate the intensity differences for processing the diffeomorphic demons; this induces larger number of pixel/voxels perations, amount of inlinked or non-coalesced memory access to be provessed.
    - state-of-art using GPU can achieve only 4-5 second computation [muyanozcelik2008fast,gu2010implementation]
  - matching/searching spectral correspondence to handle large deformation [lombaert2013spectral]
    - e.g. taking global scope of brain image
    - it is the state-of-art using CPUs that can achieve only 25 to 45 min


Algorithm 1: General Diffeomorphic Demons Framework
1. Input: Fixed image  and moving Image 
2. repeat until converge:
3. Compute update field  based on  and 
4. Apply fluid-like regularization 
5. Update velocity field  
6. Apply diffusion-like regularization 
7. Output: Transformation  from  to 


- virtual 3D environment construction
  - examples with figs




*** Actuation in MRI environment

Robot's operations should have negligible effect to the MR images and should be unaffected by the electric and magnetic fields of the MR system. In robot-assisted catheterization, a catheter is mounted on a robot, which is located near the isocenter of the MRI scanner. Therefore, ferromagnetic materials that might cause image artifacts should be avoided, and conductive materials should be adopted with caution because the magnetic field homogeneity might induce eddy currents or might be disrupted. Traditional electric motors should be precluded in the vicinity of the isocenter. Three types of motors are commonly used for actuating robots that work in MRI environments: 1) Piezoelectric or ultrasonic motors, 2) pneumatic motors, and 3) hydraulic motors.


**** Piezoelectric/ultrasonic motors
Piezoelectric and ultrasonic motors feature high power-efficiency, compactness and high dynamic accuracy, thus are suitable for actuating robots that work in close proximity to the MR system. They are driven by oscillations of piezoelectric crystals. Ultrasonic motors have been successfully applied in a MR-compatible surgical robot [chinzei2000mr]. In an advanced design adopting piezoelectric motors [su2015piezoelectrically], direct digital synthesizers were used in order to attenuate electromagnetic (EM) interference, while the signal-to-noise ratio (SNR) loss was less than 15%. Nevertheless, the presence of electric current supplied from the external electrical source inevitably infringes the safety standard of MR environment [stoianovici2014mrisafe]. To attenuate EM interference, complex EM-shielding enclosure is necessary, which degrades the motor compactness and increase design difficulties. These drawbacks have naturally shifted the research focuses towards intrinsically MR-safe actuators driven by other energy sources. For instance, pneumatic and hydraulic motors.

	
**** Pneumatic motors
Pneumatic motors are capable of operating in an MR environment, even inside the scanner, without adversely affecting MR image quality. The first MR-safe pneumatic stepper motor was presented in [stoianovici2007anew]; It comprised 25 MR-safe components and could output high-torque rotation of maximum 650 mNm with 0.83 MPa air input pressure. However, its structure was complex and cost was relatively high due to the complicated fabrication and difficult sterilization. In our previous work [guo2016novel] (Fig. 3), a compact and yet simple pneumatic motor has been developed; It consists of only seven, 3D-printed components that are solely made of MR-safe homogeneous materials. 

Pneumatic motors get several advantages over the hydraulic ones: Medical gas is readily available and innocuous so that leakage problem could be of less concern; The low-viscosity and low-weight characteristics cause introduce negligible friction and mass to the robot. However, pneumatic motors are typically bulky and are not energy-efficient. Tackling the vibrations and noise in pneumatic actuation are still challenging.






Fig. 3   (a) The pneumatic motor [guo2016novel] consists of seven components that are 3D-printed using MR-safe materials. (b) The pneumatic motor after assembly. (c) It can offer high speed and power. Linear correlation between power and speed holds below 60 RPM. 

**** Hydraulic motors
Hydraulic transmission uses nearly incompressible fluid as transmission media, offering more steady transmission and quicker response, compared to the pneumatic transmission. It also allows master-slave design (Fig. 4a); The master unit, which is usually driven by electric components such as pumps and cylinders, can be placed in the control room. The slave unit works near MRI scanner, where the actuation is transmitted from the master unit via long hydraulic pipelines through the wave guide. Such separation ensures negligible EM interference to the MR images, and allows the design of the slave unit be more compact. Recently, a novel hydraulic motor has been invented [whitney2014alowfriction] and is promising to be implemented in MRI-guided robots; It adopted rolling diaphragms to avoid sliding friction that occurs between piston and O-ring in traditional sealing (Fig. 4b and Fig. 4c), thus enhancing transmission efficiency. 
However, fluid leakage is a potential problem to safety. Filling the pressurized fluid also increases difficulty of setting up the robot.
 

Fig. 4 (a) A conceptual diagram of hydraulic transmission using master-slave design for MR-compatible robot. (b) Sealing using O-rings has sliding friction inside the cylinders, whereas (c) sealing using rolling-diaphragms does not.




**** draft notes
- Existing actuation mechanism of robots that work near the isocenter of the MRI system can be classified to 1) electric motor, including ultrasonic and piezoelectric motors; 2) Electromagnetic (EM) -powered motor; and 3) fluid motor, including pneumatic and hydraulic motors.


- The second key component of this robot is the MRI-compatible actuation unit.
  - MRI-compatibility brings out the requirements on: i) MR-safety; ii) preservation of image quality; iii) operation without being affected by the electric and magnetic fields of MRI scanner [2]. 
  - Regarding these criteria, ferromagnetic materials should be avoided in MRI-compatible actuators due to the image artifacts and distortion induced. The use of non-ferromagnetic metals, e.g. aluminum, titanium, plastic and composite materials, is permissible. It is worth noting that conductive materials placed closely to the isocenter will potentially induce eddy currents and disrupt the field homogeneity. As a result of the limited choices in materials and power supply, traditional actuators (e.g. direct current electric motor) should be precluded in the vicinity of isocenter. 
  - Currently, there are three types of actuators adopted in MRI-guided robot, 1) electric motor, including ultrasonic and piezoelectric motors; 2) Electromagnetic (EM) -powered motor; and 3) fluid motor, including pneumatic and hydraulic motors.




- Piezoelectric
  - Piezoelectric motor is one of the most common actuation methods in MRI-guided robot.
  - Chinzei et al. designed an MR-compatible surgical assist robot operating under open MRI, which is driven by ultrasonic motors [4].
  - Piezoelectric motor features with high power-efficiency, compactness and high-fidelity dynamic accuracy.
  - Piezoelectric crystal is MR-conditional, but its driving electric current will unavoidably induce EM interferences (EMI) and yield noise in the electronic signals, leading to severe loss of signal to noise ratio (SNR) in MR images.
  - To ensure the safe operation of such motors inside MRI room, high requirements have to be fulfilled on proper location and complex EM-shielding. 
  - Su et al. [6] proposed an advanced design on piezoelectric motor by using direct digital synthesizers in order to attenuate EMI, while the SNR reduction could be eliminated within 15%. 
  - using direct digital synthesizers [shang2015piezoelectrically,hao2012amriguided] in order to attenuate EM interference that will cause the image artifact (piezoelectric)
  - Even though the signal-to-noise ratio (SNR) is promising with <15% reduction, complex EM-shielded enclosure is required to surround on all sides of the motor drivers, thus degrading the motor compactness [hao2012amriguided,bannan2015development].
  - The presence of electric current supplied from the external electrical source inevitably infringes the new standard of MR-safety [stoianovici2014mrisafe].
These drawbacks have naturally shifted the research focuses towards intrinsically MR-safe actuators driven by other energy sources, e.g. pressured fluid flow [8]. 


- magnetic-driven (move to future work?)
    - [vartholomeos2011mripowered]
    - Dupont et al. [7] designed an EM-motor that could be actuated by static magnetic field of the MRI scanner. However, the steady performance of this motor will still get influenced by the magnetic field of scanner. 






- pneumatic
  - Compact actuation units allowing the robotic manipulation taking place inside the MRI bore is required for providing highly precise and reliable targeting by the intra-op imaging. 
  - To this end, various pneumatic/hydraulic actuators [9,10,11,12] have been designed, which are capable of operating in an MR environment, even inside the scanner, without adversely affecting MR image quality.
  - Stoianovici et al [9] developed the first MR-safe pneumatic stepper motor. However, its structure is complex and cost is relatively high due to the complicated fabrication and difficult sterilization.
  - We have developed an MR-safe pneumatic motor that features with its compactness and simplicity. It consists of only seven components, which are all fabricated in homogeneous material by 3D printing. This motor is driven by the air supply that is commonly available in hospital rooms. And the related electronics and valves could be all placed in control room without affecting the imaging quality, controlling and transmitting the mechanical power by three air tubes going through the wave guide. Self-locking is another noticeable characteristics of this motor, allowing the high-steady positioning in surgical robot. The first prototype has been reported in [13] and the corresponding performance test results are as shown in Fig. X. To implement this motor into the robot, a gearbox will be further incorporated to meet the different actuation requirements. 
  - In the fluid transmission, pneumatic motors get several advantages over the hydraulic ones. For example, the working fluid is readily available and innocuous so that leakage problem will not be a concern. And thanks to the low-viscosity and low-weight of the air, extra friction and mass to the robot could be ignorable. However, pneumatic motors are typically bulky and with low energy-efficiency. The vibration and noise due to the air dynamics during the transmission is challenging to eliminate as well.






- Hydraulic
  - Such that in some applications, hydraulic motors will be an alternative to offer efficient and steady transmission. 
  - To meet these challenges, a novel hydraulic motor has been invented [14] and is promising to be implemented in MRI-guided robots. This is a passive fluid transmission based on a pair of rolling-diaphragm cylinders, which are placed symmetrically and connected by a hydraulic tube. Different from the traditional sealing, e.g. tight-sealing by O-ring, these cylinders are sealed by rolling diaphragms (as shown in Fig. X). It avoids the sliding friction of traditional sealing, hence the rolling-diaphragm actuator is capable of providing low-friction, smooth transmission over the entire stroke. Fluid pressure could be preloaded for bidirectional operation and quicker response. 
  - The disadvantages of hydraulic motor are: i) fluid leakage is always a problem in hydraulic transmission, adding constraints in system setup and its mobility. ii) the strength of rolling diaphragm could limit the maximum transmission force. iii) fluid dynamics will still have influences on the transmission response.






- In addition to imaging issues, enhanced stability and adequate flexibility of robot-assisted surgical platform also poses increasing demand on intra-op MRI navigation.
- Considering the operation on delicate tissue, the robot system must has high accuracy and can be finely controlled, in other words, backlash should be minimized and it should be able to remain locked in its original position if any power failure or emergency stop happens.
- The workspace is tightly constrained inside the scanner bore. These all bring up the strict demands on compacted mechanical design of the robot. 
- Sterilization should also be taken into consideration, especially for the design of end effector.
- Actuators driven by oscillation of piezoelectric materials, such as ultrasonic motor, have been extensively applied (e.g. [XXX]) to be tailor-made for interventional MRI applications because of its high-fidelity dynamic accuracy. 

- Recent advanced designs was proposed to operate the piezoelectric motor electronics using direct digital synthesizers [XXX] in order to attenuate EM interference that will cause the image artifact. Even though the signal-to-noise ratio (SNR) is promising with <15% reduction, complex EM-shielded enclosure is required to surround on all sides of the motor drivers, thus degrading the motor compactness [XXX]. 
- The presence of electric current supplied from the external electrical source inevitably infringes the new standard of MR-safety [XXX]. 
- These disadvantages have naturally shifted the research focuses towards intrinsically MR-safe actuators driven by other energy sources, e.g. pressured fluid flow, instead of EM power [XXX]. 
- Compact actuation units allowing the robotic manipulation taking place inside the MRI bore is required for providing highly precise and reliable targeting of lesions located by the intra-op imaging. 
- To this end, various pneumatic/hydraulic actuators [XXX] have been designed, which are capable of operating in an MR environment, even inside the scanner, without adversely affecting MR image quality.

- a robotic platform that allows surgeons tele-manipulate surgical tools which are located in the MRI-scanner room
  - should have negligible effect to the MR image quality. 
  - must has high accuracy and can be finely controlled
    - e.g. backlash should be minimized and it should be able to remain locked in its original position if any power failure or emergency stop happens.
  - The workspace is tightly constrained inside the scanner bore. These all bring up the strict demands on compacted mechanical design of the robot.
  - Sterilization should also be taken into consideration
  - 

- recent advanced MR-compatible actuation methods 
  
    - 
  - magnetic-driven (move to future work?)
    - [vartholomeos2011mripowered]
    - pros and cons

- pneumatic actuation
  - pros and cons
  - several examples

- Hydraulic actuation
  - O-ring vs rolling diaphragm
  - pros and cons


*** Hardware for tracking in MRI 

Catheter tracking is a central requirement for MRI-guided robot-assisted catheterization for monitoring the progression of a catheter in MRI system. It enables determination of the catheter's position and orientation, and promptly assessment of the efficacy of a therapy such as radiofrequency (RF) ablation for the MR images. Positional feedback also allows implementation of close-loop control algorithms to enhance robot control accuracy and devising advanced intuitive control interface. The hardware technologies for catheter tracking in MRI can be classified into 1) active tracking, 2) passive tracking and 3) semi-active tracking three categories [duerk2002abriefreview], which are introduced as follows.


**** Passive tracking 
Passive tracking make use of directly interaction between the catheter and the MRI system or tissue for allow visualization. 
A catheter is coated or filled with either contrast agents (e.g. T1-shortening agent 4-6 vol % Gd-DTPA) that enhances MR signal or paramagnetic material (e.g. dysprosium oxide) that causes MR field inhomogeneity to the surrounding matter. 
Visualization is achieved using properly designed triggering signal called MR sequence that are programmable in the MR scan software.




The local MR effects depend on the shape of the catheter, the catheter orientation to the magnetic field, and 

In [patil2009automatic], a sequence called projection-reconstruction imaging with echo-dephasing (PRIDE) has been proposed for passive tracking positioning, in which ≤ 4.5mm positional error of paramagnetic marker materials wrapped around a MR-compatible guidewire can be obtained within 20 ms (50 Hz). 
Passive tracking does not have the heating risk as in active tracking and is applicable in different MR field strengths. However, it requires more complicated sequence and more computation time to process susceptibility artifacts in the high-resolution images for fast and accurate localization; The instrument coordinates are not registered with passive tracking methods [fabio2015magnetic], manually updating the imaging plane is usually necessary [frericks2009magnetic]. It may also encounter difficulties to track multiple catheters that are in close proximity to each other.
 
**** Active tracking 
Active tracking utilizes electronic circuits that actively control/affect magnetic field inhomogeneity for visualization and localization of the catheter in MRI.
Small tracking coils are attached to the tip of a catheter. They are connected to a receiver electronic system via coaxial cables to measure or disturb the magnetic field inhomogeneity. 

Localization of the coils can be achieved within a few milliseconds, thus enabling high-frame rate of tracking. Precise measurement of position can be achieved utilizing coils that have high sensitivity to local field inhomogeneity [glowinski1997catheter]; Recently, 3D localization resolution 0.6 X 0.6 X 0.6 mm3 can be attained with 40 Hz tracking frequency [wang2015realtime].
Active tracking has several advantages (Table 1).  It has higher spatial and temporal resolution 3D information than passive tracking. Compared with semi-active tracking, it could provide high resolution tracking without affecting the image quality. One of the main issues in active tracking is the heating issues due to the standing wave induced by the reflection of resonant radiofrequency (RF) waves; The standing wave also causes storage of electrical energy within the conducting structure that may cause potential safety hazards [konings2000heating]. The electronic component may also induce electromagnetic (EM) interference that causes artifacts in the MR images.

**** Semi-active tracking
In semi-active tracking, small coils are utilized in isolated circuits that resonate with particular MR frequencies. There are no direct capacitive electrical connections to the MRI system. Instead, wireless inductive coupling between tracking coils and the MRI system is used. Using properly programmed MR sequence that detunes/triggers the isolated resonant circuit, visualization of the semi-active device in the MR image can be achieved. An optical fiber was used in [weiss2004invivo] as the wireless inductive coupling along a catheter, where the laser signal source triggered by a MR sequence was transmitted to illuminate a photodiode, which was placed parallel to a coil in a resonant circuit at the catheter tip; Real-time imaging (30fps) of a in vivo test using a radial steady-state free-precession sequence was demonstrated.
Benefiting from the wireless inductive coupling, semi-active devices avoid the potential development of standing waves along electrical connections found in active tracking. Nevertheless, the mechanical assembly and miniaturization of semi-active is still a challenging task [galassi2015fast]. 

 Table 1


|                      | Advantages                                                          | Disadvantages                                                                                                       |
|----------------------+---------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------|
| Active Tracking      | 1. Generation of high spatial and temporal resolution 3D information. 2. Allow automatic tracking and slice plane following | A long wire is used to connect the RF coil to the external circuits, which may lead to conduction hear dissipation. |
| Passive Tracking     | 1. Simple, safe, and able to operate under different field strengths. 2. Easier miniaturization of devices | Time consuming and the tracking cannot be switched on/off                                                           |
| Semi-active Tracking | 1. Potential for automatic tracking and slice plane following. 2. No wire connection between coils and MR machine
   | Relative large size of the coil is needed to ensure adequate signal intensity                                       |


   









Having positional feedback of interventional devices is essential in MRI-guided robot-assisted MIS; 
It not only allows implementation of feedback control method that attains more accurate tool manipulation, 
but also enables development of more intuitive control interface and closes the surgeon-robot loop.
This section highlights the hardware technologies of that enable intra-operative tracking under MRI. 

- it is important to feedback the surgical tools' 3D positions that are defined in the same coordinate frame as the MR image's coordinate frame
  - the sensory feedback allows implementation of feedback control method
    - for more accurate manipulation of surgical tools
    - implementation of intuitive control-interface
    - to close the surgeon-robot loop
  - explain why the same coordinate frame should be used
    - advantage in the image registration process
- Intra-operative imaging is possible by SSFP, parallel imaging techniques  
  - Due to the continued development of MR hardware for faster image acquisition and reconstruction, along with developments such as steady state free precession (SSFP) and parallel imaging techniques, real-time MR imaging is now a clinical reality[raman2005realtime, wacker2005mrguided].

- shorter and more open magnet designs, from research to preclinical method and a few clinical applications
  - With the trend toward shorter and more open magnet designs, endovascular MR-guided interventions have evolved from a research tool to a preclinical method over the last decade with a few applications that have entered the clinical arena [razavi2003cardiac].
- 
- In MR-guided intravascular interventions (e.g., embolization or stent placement), the interventional radiologist benefits from automatic and continuous updates of the imaging slice position, since during the procedure the catheter tip is always visible. Unfortunately, tip tracking requires information only from several selected points on the catheter.


In active tracking, small coils are attached to an interventional device, for example, at the tip of a catheter. Tracking coils are connected to a receiver electronic system via coaxial cables to measure MR gradient field [dumoulin1993realtime,duerk2002abriefreview]. Localization of the coils can be achieved within a few milliseconds [bock2006afaraday], thus enabling high-frame rate of tracking. Precise measurement of position can be achieved utilizing coils that have high sensitivity to local field inhomogeneity; Recently, 3D localization of resolution 0.6 X 0.6 X 0.6 mm3 can be attained with 40 Hz tracking frequency [wang2015realtime].
One of the main issues in active tracking is the heating issues, due to the standing wave induced by the reflection of resonant radiofrequency (RF) waves; The standing wave also causes storage of electrical energy within the conducting structure that may cause potential safety hazards [ladd1998active,konings2000heating,nitz2001on]. It has been reported that nitinol-made guidewires was up to 74 degree Celsius [konings2000heating]. The electronic component may also induce electromagnetic (EM) interference that causes artifacts in the MR images.
However, active tracking also has several advantages compared with the passive traacking and semi-active tracking. 
Need several advantages of active tracking



- active tracking
  - e.g. [wang2015realtime]
  - structure
    - fig example [wacker2004thecatheter]
    - small radiofrequency (RF) coils attached to the instrument; the coils connect with a receiver system via coaxial cables [dumoulin1993realtime,duerk2002abriefreview]
    - The routing of the coaxial cables is required from the coil to the receiver interface [sarioglu2015anoptically] to measure MR gradient field.

    - the size and length of the cables have to be minimized for reduction of any EM interference
    - coil-to-channel electronic interface also has to be specifically designed for particular types of scanners only
    - particularly challenging while operating larger numbers (>8) of active coil.
    - a catheter coil design is proposed that performs active catheter tip tracking and visualization of the distal end with a only single coaxial cable [zuehlsdorff2004mr].
    - Often, a single coil at the tip of the instrument is used for instrument tracking, which is then 
    - In intravascular tracking catheters, the blood surrounding the microcoil provides the MR signal; however, in air-filled cavities no residual MR signal is available and the microcoil needs to be equipped with an independent signal source [erhart1998tissue]. Tracking thus differs from other high-resolution imaging applications, where a small local coil is used acquire images of the tissue adjacent to the airways [gilderdale2003aninductively]. Signal sources using liquid-filled capsules or water-based gels were found to rapidly dry out over several days [sandhu2007asolid], in particular, when very small reservoirs with a diameter of only several millimeters were used. Since medical devices often need to be stored for several months or even years (shelf life), liquid signal reservoirs in microcoils are impracticable for clinical use.
    - Recently, image artifacts caused by the semisolid rubber material of breathing tubes and hoses in short- echo-time (TE) MR images were found [kugel2001artifacts], which suggest that these materials might also be useful as MR signal sources [umathum2008rubber] for device tracking in air-filled cavities. In this work[stefan2010active], a novel tracking method for active micro- coils in air-filled cavities is presented. The tracking method uses a biocompatible and clinically approved rubber as MR signal source in a microcoil at the tip of a catheter. A dedicated pulse sequence and postprocessing algorithm are presented that utilize the unique MR prop- erties of the rubber material to distinguish its signal from that of the surrounding tissue [rahmer2008catheter]. The coil position data were visualized using either a roadmapping tech- nique or a real-time implementation with active device tracking and automatic slice positioning [bock2004mrguided]. Both catheter and pulse sequence were tested in phantom and animal experiments.

  - working principle
    - localization of the coil is achieved in few millisecnds through acquisition of 1D projections along all three spatial directions (X,Y and Z)
    - since the sensitivity of the micro-coils is confined to small region, projections obtained show a peak corresponding to its position
    - The reveived coil signal is highly localized [galassi2015fast] and can be readily differentiated from the other coils' signal
    - thus enabling high-frame rate of tracking (≥40Hz)
    - the instrument tip position is detected within 20 ms [zuehlsdorff2004mr].
    - 
    - localized with a fast gradient echo acquisition of three orthogonal projections.
    - utilizes locally sensitive transmit/receive coils for either localization [ackerman1986rapid,dumoulin1993realtime] or visualization [ocali1997intravascular] or is based on the visualization of current related local field inhomogeneities produced in a small loop [glowinski1997catheter]
    - Small direct currents have been sent through wire loops mounted on a catheter to create a switchable field distortion (1). Receiver coils incorporated in the catheter lumen have been used for profiling in order to visualize the entire length of the catheter (1,6,7). Furthermore, cath- eters have been equipped with microcoils for active tip tracking (8 –10). The location of these tracking coils can be determined rapidly by means of a projection technique, and the position information in turn can be used to define the position of the imaging slice.

  - not only for device tracking but also for vessel wall imaging or functional studies [hurst1992intravascular,quick1999singleloop,hofmann2005human].

  - potential radiofrequency (RF) heating issues
    - due to standing waves along the conducting cables still represent one of the major and most prominent potential safety hazards with active tracking.
    - The standing waves lead to storage of electrical energy, which may be transmitted into the human body.
    - With nitinol guidewires temperatures of up to 740C has been reported [konings2000heating].

  - active device localization can be achieved via radio-frequency (RF) micro-coils (MR-Tracking) or gradient field measurements, which can generate unambiguous and precise (< 1 mm) 3D location information for multiple micro-coils within a few milliseconds [dumoulin1993realtime,bock2006afaraday,scheffler2004navigation].
    - However, active tracking is challenging for MR-guided brachytherapy because: (a) the metallic stylet within the catheter leads to B0 and RF (B1) magnetic field inhomogeneities, which are exacerbated by the close proximity of 10-20 needles;
    - (b) RF currents induced in the surface of metallic stylet can distort imaging and cause heating.

  - Active devices use direct electrical connection to the MR system or an external power source and are usually grouped into four categories:
    - devices which change the signal locally by affecting the field homogeneity using DC current in wires traversing the catheter [glowinski1997catheter]
    - devices (typically small reso- nant coils) which localize the tip of the catheter on a previously acquired roadmap using three orthogonal projections [leung1995realtime,wildermuth1997mr,ladd1998visualization,ladd1998active,ladd2000interventional]
    - devices which allow visualization of the length of the catheter, like the loopless antenna [ocali1997intravascular,lardo2000visualization,bottomley2000cardiovascular]
    - devices that can be used to track the position of the catheter and image locally [zhang2000active,zhang2001amultielement]. 


In contrast to active tracking, passive tracking does not require electronic components such as cables and receivers circuits.
Utilizing either contrast agents (e.g. 4-6 vol % Gd-DTPA) as T1-shortening agents that enhances MR signal [unal1998arapid,unal2006mrvisible] or paramagnetic material (e.g. dysprosium oxide) that causes MR field inhomogeneities to the surrounding matter [schenck1996therole], and properly designed triggering signal called MR sequence that are programmable in the MR scan software, visualization of the contrast agents or the paramagnetic material in the MRI can be achieved. Position of the instrument is subsequently obtained from the resulting MR image. 
In [patil2009automatic], the MR sequence PRIDE (projection-reconstruction imaging with echo-dephasing) has been proposed for passive tracking positioning, in which ≤ 4.5mm positional error of paramagnetic marker materials wrapped around a MR-compatible guidewire can be obtained within 20 ms (50 Hz). 
Passive tracking does not have the heating risk and is applicable in different MR field strengths.
However, it requires more complicated sequence and more computation time to process susceptibility artifact in the high-resolution images for fast and acurate localization; The instrument coordinates are not registered with passive tracking methods [fabio2015magnetic], manually updating the imaging plance is usally necessary [frericks2009magnetic]. It may also encounter difficulties to track multiple instruments in close proximity to each other, such as multiple catheters in endovasular catheterization procedure [kapur20123t, fabio2015magnetic].



- passive tracking
  - structure
    - the interventional device is made to be visible on the MR image itself and does not require any additional harware or image post- processing and hence the name.
    - utilizing contrast agents --  T1-shortening agents (See Fig. 1.5).
      - fig - [unal2006mrvisible,bakker1996visualization]
      - such as 4-6 vol % Gd- DTPA
      - fills within the interventional device (for e.g. catheter) or coat on the devices surface [unal2006mrvisible].
      - handling of the agent-filled or coated instruments remains problematic.
	- the insertion of guidewire is not possible since the catheter lumen is filled with contrast agent.
    - using paramagnetic materials such as dysprosium oxide [bakker1996visualization] or stainless steel materials [mekle2006apolymerbased]

  - working principle
    - one using contrast agents (T1-shortening agents) (such as 4-6 vol % Gd- DTPA) that increases the MR signal [unal1998arapid, unal2006mrvisible].
      - By utilizing strong T1-weighted sequence, tracking of the device can be achieved with positive contrast [unal1998arapid, omary2000mrguided]
    - The paramagnetic markers or materials cause significant field inhomogeneities when placed in a uniform main magnetic field B0, due to its local susceptibility differences with respect to surrounding tissues [schenck1996therole].
      - field inhomogeneity has a dual effect of local frequency shifts and local gradient perturbations.
      - This source of field inhomogeneity has been exploited as a form of image contrast for passive visualization and tracking of the interventional devices as well as super-paramagnetic iron oxide (SPIO)-labeled cells.
      - Traditionally the visualization of these paramagnetic materials is based on increase in T2∗ decay that they cause entailing a negative contrast (signal loss) with respect to background in a resultant image (Fig.1.6).
	- fig from [bakker1996visualization]
	- Gradient-echo sequences are the current de-facto standard to visualize these T2∗-based effects [rubin1990magnetic,kochli1994vascular,bakker1996visualization], since the magnetic field inhomogeneities have strong impact on signal properties of these type of sequences [reichenbach1997theory].
	- Unfortunately, due to confounding background signals it is often difficult to distinguish signal loss due to paramagnetic materials from other unwanted inhomogeneities such as, air/tissue interfaces etc.
      - Therefore, MRI techniques that generate positive contrast that are localized within the immediate surroundings of the paramagnetic materials while suppressing the background signals have been proposed.
	- The concurrent state-of-the-art positive contrast techniques can be broadly classified into three categories based upon their method of identifying paramagnetic materials:
	  - those using local frequency shifts in the on-resonance frequency [mekle2006apolymerbased, stuber2007positive, cunningham2005positive]
	    - either based on temporally inefficient spin-echo type of sequences incorporating specially designed RF pulses [cunningham2005positive] or are susceptible to main magnetic field inhomogeneities [stuber2007positive].
	    - Mekle et.al proposed a fast passive tracking ap- proach based on special properties of bSSFP sequence at low flip angles giving rise to positive contrast within the close vicinity of the marker due to off-resonance effect [mekle2006apolymerbased]
	  - those exploiting the local gradient compensation by the imaging gradients [seppenwoolde2003passive]
	    - based on deliberate modification of slice select gradients that dephases background signals whereas marker-related local gradients compensate for the dephasing gradients to produce locally a positive contrast [seppenwoolde2007whitemarker] and is commonly known as “White Marker Phenomenon” (See Fig. 1.8).
	  - those mapping the susceptibility-induced gradients as a post-processing step [vonken2008positive, dahnke2008susceptibility].
      - Most of the research carried out to date on passive visual- ization has been with spoiled gradient echo sequences. The recently introduced steady-state free precession (SSFP) sequences provide high blood signal intensity [thiele2001functional] and good signal-to-noise and have become the sequence of choice for dynamic imaging of the heart and great vessels. Preliminary work by Martin et al. [martin2003steady] demonstrated the potential benefits of using SSFP imaging to visualize endovascular devices.
	    
  - Contrary to active tracking, passive techniques do not suffer from RF heating problems.
  - unlike semi-active devices passive devices do not require any mechanical scanner connection.
  - passively visualizing the magnetic susceptibility image artifact created by the metallic stylet [kapur20123t].
    - Metal itself does not generate MR signals and the presence of metal can result in severe distortion to the static magnetic field (B0) around it because of the large susceptibility differences with surrounding tissues.
    - The signal voids created by the metal in MR images are used as a negative contrast to identify the device, but the accurate location and size of the device is difficult to determine because the susceptibility artifact on MR images depends on the shape and material properties, the device’s orientation relative to B0, and pulse sequence parameters [muller2004numerical].
    - High-resolution image-based passive tracking methods are typically time-consuming (0.5-2 tracking frames per minute) and may also compromise the contrast- to-noise ratio of anatomic images.
    - Furthermore, this approach becomes more difficult in MR-guided brachytherapy, where the individual paths of multiple catheters need to be tracked, since catheters are close to each other (<10 mm apart) or cross paths during insertion.
    - Various positive contrast techniques have been proposed to image paramagnetic metallic objects, but these approaches offer limited benefit over negative contrast methods [seevinck2011highly,dahnke2008susceptibility,cunningham2005positive,mani2006gradient,seppenwoolde2003passive].

  - Passive devices interact directly with the imaging system or surrounding tissues to allow visualiza- tion of the catheter.
    - In the work of Bakker et al. [bakker1996visualization,bakker1997mrguided], dysprosium rings were placed on conventional catheters to create an area of signal loss. The ring design allowed the markers to be visualized regardless of the catheter orientation.
    - Alternatively, Gd-DTPA solutions (4 – 6%) can be used to obtain positive enhancement of the catheter [unal1998arapid,omary2000realtime]
    - In a similar study a dephasing gradient was added along the slice select direction to further increase the catheter/tissue contrast [korosec1996time].




Semi-active tracking utilizes small coils in isolated circuits that resonate to particular MR frequencies and has no direct capacitive electrical connections to the MRI system [duerk2002abriefreview]. Instead, wireless inductive coupling between the coils and the MRI system is used. Using properly programmed MR sequence that detunes/triggers the isolated resonant circuit, visualization of the semi-active device in the MR image can be achieved. In [weiss2004invivo], an optical fiber was used as the wireless inductive coupling along a catheter, where the laser signal source triggered by a MR sequence was transmitted to illuminate a photodiode, which was placed parallel to a coil in a resonant circuit at the catheter tip; Real-time imaging (30fps) of a in vivo test using a radial steady-state free-precession sequence was demonstrated.
Benefiting from the wireless inductive coupling, semi-active devices avoid the potential development of standing waves along electrical connections found in active tracking. Nevertheless, the mechanical assembly and miniaturization of semi-active is still a challenging task [galassi2015fast]. 





- semi-active tracking coils
  - structure
    - the coil does not have to connect with the scanner receiver channel, but only act as an radio-frequency (RF) receiver and inductor in an isolated LC circuit that resonates with MR frequency ~63.8MHz or 123.5MHz, respectively, for 1.5T or 3T scanner either [rube2014wireless]
    - may require tedious LC tuning process to match the resonant frequency within tolerance of ±1MHz [galassi2015fast]
    - utilize self-resonant RF circuits and have no direct electrical connection to the scanner.
    - incorporate miniature RF coils tuned to Larmor frequency of the scanner and encapsulates a small container filled with a solution having short T1 [kuehne2004catheter, hegde2006interactive].

  - 3D coordinates matching of just three coils is complicated [galassi2015fast]
  - miniaturization to include commercial MR-safe capacitors is very challenging
    - the criteria for high quality factor (Q>50) that is inversely proportional to the circuit electrical resistance
    - high resistance that may generate excessive heat

  - working principle
    - using a fast imaging sequence with low flip angles generates a positive contrast for the sample within the coil due to local gain of the B1 field [burl1996tuned, quick2005interventional], in combination with the relatively low signal from the background (see Fig. 1.4).
      - fig - [weiss2004invivo]
      - The MR sequence controls the detuning of the resonant circuit by means of software triggers, which are programmable in the MR scan software. Corresponding hardware triggers on the scanner interface are used to switch a laser diode, which illuminates the photodiode D at the catheter tip via an optical fiber. <- the figure caption
  - Since inductively coupled coils do not utlize extended long conducting structures, heating of the coils due to E-field coupling is avoided if the wavelength of the electric field in tissue is longer than the coil dimension.
  - might still lead to severely increased local specific absorption rate (SAR) values due to their resonant coupling to the B-field of the RF.
  - semi-active devices require a mechanical connection (for e.g. laser fiber) between the instrument and the scanner

  - Semiactive devices incorporate tuned coils, but have no direct connection to the scanner.
    - These devices can be incorporated into fiducial markers by surrounding a small cell containing a short T1 solution surrounded by tuned windings.
    - These semiactive devices can also be used to enhance externally applied RF pulses and hence produce a high-signal intensity using “flip-angle amplifi- cation” [burl1996tuned].
    - Recently, semiactive devices were used in pairs to produce a signal enhancement for any catheter orientation [kuehne2003pair].

- image registration for the three types of sensing - for manifying the advantage of using active tracking coil
  - active tracking coil
    - The positional information is used to actively align the position of the imaging slice.
    - velocity of the device has been used to automatically adjust the imaging parameters [wacker2004thecatheter].
    - It has also been demonstrated that position of the micro-coil can be detected between the acquisition of two real-time images (for e.g. using balanced SSFP (bSSFP), TrueFISP) and the information can be used to reposition the imaging slice [duerk1998remember, rasche1997catheter].
  - semi-active
  - passive

- Three main heating mechanisms can occur: from eddy currents, induction loops, and resonating RF waves along a conducting device. The first two mechanisms do not involve storage of electrical energy. [marc2004visualization]
  - Heating due to eddy currents rarely exceeds a few degrees [shellock1994magnetic,schenck1997safety]
  - induction loops, for example, formed by monitoring equipment leads, have been known to cause burns [knopp1996unusual,shellock1996burns].
  - In the third mechanism, a resonant RF wave is reflected at the endpoints of the con- ducting structure, thus creating a standing wave and storage of electrical energy [ladd1998active,konings2000heating,nitz2001on]. This is an important problem in conducting guide wires and active catheters. With a nitinol guide wire, temperatures of up to 74°C have been observed [konings2000heating].



- list some other existing sensors if possible
  - e.g. forces sensor
    - some examples in the literature and their working principles
      - optical Fiber Bragg Grating (FBG)-based sensing unit to measure force [chen-mriconditional]
      - 
    - pros and cons




      

** An experimental platform
1)	An MR-conditional catheter robot 
 We have developed a catheter robot for MRI-guided intra-cardiac EP interventions. The catheter robot (Fig. 4) that consists of chiefly two parts: a master part that situates in control room and a slave part that locates in MRI scanner. Driven by individual electric stepper motors, the master part in control room drives the slave part and consequently the catheter in MRI room, via hydraulic transmission along pipelines (~10 meter) through waveguide. The robot adopts 4 pairs of hydraulic master-slave design of actuation unit that as illustrated in Fig. 3(a). While the electric motor at the master side driving the master actuation units, the slave one will replicate the motion simultaneously. 
To suppress the interference to the MR images, only MR-safe and non-ferromagnetic materials are adopted in the robot. The main structural components were fabricated by 3D-printing technique with acrylic compounds material (VeroWhitePlus/VeroClear, Stratasys, USA). Those key components related to power transmission such as gears are machined from nylon. In addition, some other materials are used in the robot as well, such as PolyVinyl Chloride (PVC), Polyetherimide (PEI) and rubber. An MRI-compatibility test has been conducted, in which the robot was running inside a 1.5T MRI scanner (SIGNA, General Electric Company, USA) and placed near a commercial MRI phantom (J8931, J.M. Specialty Parts, USA) at the isocenter of the scanner (Fig. 5a). No observable artifact was found in MR images under different robot operation scenarios (Fig. 5b). 
	By adopting 4 independent actuation units with rolling diaphragm, the robot can achieve motions of bending, rotation, coarse insertion and fine insertion (Fig. 4). Bending and rotation are two typical operations of a clinically used steerable catheter. For insertion motion, two actuation units serve separately for coarse and fine insertion. While the actuation unit for coarse insertion is connected to manipulator platform by timing belt, the unit for fine insertion is by gear directly. The coarse insertion enables a relatively long movement range for catheter tip to enter into left atrium, which improve the flexibility of the robot. While it still keeps the feature of high-accuracy and quick-response in this DoF by fine insertion.
This robot is designed to be compatible with different types of clinically used catheters. To tightly hold a catheter with a particular shape, the part for anchoring is specifically designed and readily fabricated by 3D-printing. Currently, the robot is compatible with bi-directional and steerable EP catheters from Biosense Webster Inc. and St. Jude Medical. 
Because the catheter could be mounted or removed conveniently, its sterilization is simple and feasible. Moreover, in the front of the robot there is a stand to support a tube for guiding the catheter into the trocar. This stand is fabricated with acrylic compounds material by 3D-printing technology, which is also disposable and hence eases the sterilization.
Hysteresis can significantly affect the fidelity of the catheter robot. It can be caused by the backlash between gears and long transmission via flexible pipelines. For our robot adopting the master-slave designed in Fig. 3(a), the backlash between the gear teeth can be eliminated by means of the use of pressurized fluid; The rolling diaphragms provides frictionless sealing and hence enhance efficiency. We have examined the actuation performance of the bending DOF by measuring the rotation angles the master and slave actuation units. It is representative since it requires the highest torque to bend a clinically used catheter among the four DOFs. During the test, master actuation unit moved with slow and steady speed to avoid damping effect of the transmission media. The results shown in Fig. 6 indicates that the bending actuation is highly repeatable with small hysteresis (about 1.5 degree). 
 In our proposed clinical setup, the operator can tele-operate the catheter robot by using a 3D motion input device in control room (Fig. 4a). The input motion is augmented and stabilized in order to filter out the natural hand tremor. A visualization interface provides multi-modal navigation guidance for the operators, including real-time 3D rendered model of the EP roadmap, overlaid with the ablation catheter model tracked by MR-based localization. 

2)	Real-time active tracking coil 
Two micro RF coils are incorporated into a clinical-use cardiac catheter (Fig. 5, active tracking coil mounted to the tip of catheter), which can directly interact with the MR-scanner via a custom-built receiver interface and coaxial cables. 
A dedicated MR tracking sequence [16] was used to acquire the MR signal from the micro coils along the x, y, and z directions of the magnetic field gradient. To correct the inhomogeneities of the static magnetic field , both zero-phase-reference and Hadamard multiplexing methods were employed. The sequence is able to achieve a spatial resolution up to 0.6×0.6×0.6 mm3, and a sampling rate of up to 40 Hz.
While the two micro coils can provide rapid and accurate measurement of the catheter tip position, their relative displacements also reveal the tip orientation. (Fig. XX) These MR-based tracking data can be automatically aligned and registered into the MR image domain without any external sensors or patches (Fig. 7XX – Block diagram), so that the catheter position and cardiac image can share the same coordinate space. Thus, the potential tracking error due to co-registration between tracking system and image coordinate could be eliminated, facilitating precise placement of catheter at ablation target.
Another major advantage of the proposed system is that the tracking module can also be used in conjunction with intra-operative MR imaging, in which the MR-tracking is interleaved with an imaging sequence. It allows instantaneous visualization of the exact tissue morphology and also physiological change as a result of ablation (e.g. edema or scar) [20]. 

3)	Fast image registration using FPGA
Furthermore, these post-ablation lesions/landmarks selected from the intra-op images can be automatically re-aligned on the pre-planned EP roadmap by using our proposed fast image registration. It is achieved by estimating the deformation field between the pre-op and intra-op images by real-time Diffeomorphic Demons (DD) Registration. DD employs diffeomorphic transformation in the deformation model, ensuring invertibility, continuity and legitimacy of the deformation field [6]. However, the computation of DD involves a substantial number of convolution processes, which require repeated access of non-coalesced pixel values. Such access will compel a large amount of memory being continuously fetched to the device cache in runtime. 
In light of such memory bandwidth requirement, we have implemented DD on an FPGA (Xilinx® Virtex7-XC7V2000T). Memory access congestion is avoided by streaming the data into a dataflow pipeline, while other pixel values can be accessed via data exchange channels between the processing units [8]. Results (Fig. 8) show that the computation using FPGA is 25 times faster than state-of-the-art GPUs. The registration can be done within seconds, opening up the possibility of deploying intensity-based deformable registration in the clinical scenario. 


-	Mention video is available.





** Discussion and Conclusions (<800 words) 
Limitation of Current Approach
-- Currently, there is no existing commercial robotic platform is MR-conditional, that is also integrated with real-time MR image registration.
-- First attempt to an comprehensive MRI-compatible robotics system for EP catheterization 
-- intrinsically MR-compatible / without using any metallic material
-- We aim to create a new benchmark in three major aspects, which could accelerate the developing trending of MRI-guided assisted robotic system, opening a new dimension for many existing image-guided procedures.
-- i) The significant acceleration of the deformable registration using FPGA will facilitate fast, reliable guidance for interventions guided by various MRI settings. It will realise accurate alignment of pre-op data (e.g. planned trajectory, tumour margins) with the exact anatomical model in real time, providing augmented visualization of significant tissue changes in an automatic manner. Presently, such re-alignment have to be performed mentally by surgeons based on their subjective geometric perception;
-- ii) The design parameters of the proposed MR-conditional actuators could be readily adjusted in application of various robot-assisted interventions, ranging from breast biopsy, neurosurgery, prostate surgery to cardiac EP 
--- iii) The highly accurate and MR-based position tracking authentic feedback signal in image domain for advanced haptic guidance and control algorithm, including motion augmentation based on virtual fixture and 

3D printing: (Brian’s random idea??) Advancement in 3D printing technology: Allow fabrication for complicated / interlocking parts at one piece
-- but this parts can only be produced in separated parts and assembled manually by convention manufacturing technique. 
-- 3D printing can eliminate the need of additional sealing / assemble procedures imposed by conventional manufacturing technique

Clinical Impact
-- Surgeons usually conduct with a conservative approach, because they lack of reliable image feedback / benchmark of the ablation progress
Safety
-- Real-time MRI enable e.g. transmural and interconnected circumferential lesions
-- Prevent perforation by augmented manipulation / provide haptic feedback / active constraint / collision detection
-- Enhanced visualization also provide additional info for surgeons in decision making, 
-- decrease the rate of nerve damage, esophageal fistula creation, pulmonary-vein stenosis and stroke, the major risk of EP procedure

Efficiency
-- Combine such enhanced image guidance with stability of robotic manipulators
-- Visualize soft tissue and position tracking in image domain, enhanced navigation, shortened surgical time
-- Exact 3D model of tissue + reliable position tracking in image domain, enable autonomous path planning for shorter path / optimization on way points, reachability, ease of manipluation 
-- Tracking more autonomous and/or intuitive control-interface

Effectiveness
-- e.g. reduce the chances of post-procedural arrhythmia recurrence after heart ablation treatment
-- achieving better dexterity and control of catheter
---- facilitate better treatments for more complex arrhythmials such as persistent AF and VT, which are currently difficult to treat even with state-of-the-art robotic systems.

Cost
-- in long term compensate the high cost of MRI machine


Potential extension and future work

-- Catheterization involves dexterous manipulation of thin and flexible medical-grade instrument to pinpoint the target anatomy for biopsy, drug delivery or lesion ablation through the transluminal, intraluminal, intracavitary or intracranial surgical approach. Such surgical manipulation could be applied on cardiovascular intervention, prostate surgery, stereotactic neurosurgery or breast biopsy.

-- Neural robot? Similar actuation and sensing paradigm is readily transferable to others surgical procedure, such as Neural surgery (Needle insertion, DBS)
-- Control interface for visual-motor realignment? 
-- Close-loop control in operation space
-- Cardiac motion compensation?




** Acknowledgments

** References
- J. L. Ackerman, M. C. Offut, R. B. Buxton, and T. J. Brady, “Rapid 3D tracking of small RF coils.,” in Proceedings of the SMRM, (Montreal), p. 1131, 1986.
- C. Dumoulin, S. Souza, and R. Darrow, “Real-time position monitor- ing of invasive devices using magnetic resonance,” Magn Reson Med, vol. 29, p. 411–5, Mar. 1993.
- O. Ocali and E. Atalar, “Intravascular magnetic resonance imaging using a loopless catheter antenna,” Magn Reson Med, vol. 37, no. 1, p. 112–8, 1997.
- A. Glowinski, G. Adam, A. Bucker, J. Neuerburg, J. van Vaals, and R. Gunther, “Catheter visualization using locally induced, actively controlled field inhomogeneities,” Magn Reson Med, vol. 38, p. 253–8, Aug. 1997.
- S. Zuehlsdorff, R. Umathum, S. Volz, P. Hallscheidt, C. Fink, W. Semm- ler, and M. Bock, “MR coil design for simultaneous tip tracking and curvature delineation of a catheter,” Magn Reson Med, vol. 52, p. 214–8, July 2004
- F. Wacker, D. Elgort, C. Hillenbrand, J. Duerk, and J. Lewin, “The catheter-driven MRI scanner: a new approach to intravascular catheter tracking and imaging-parameter adjustment for interventional MRI,” AJR Am J Roentgenol, vol. 183, p. 391–5, Aug. 2004.
- J. L. Duerk, J. S. Lewin, M. Wendt, and C. Petersilge, “Remember true FISP? a high SNR, near 1-second imaging method for t2-like contrast in interventional MRI at .2 t,” Journal of Magnetic Resonance Imaging: JMRI, vol. 8, p. 203–208, Feb. 1998. PMID: 9500281.
- V. Rasche, D. Holz, J. Ko ̈hler, R. Proksa, and P. Ro ̈schmann, “Catheter tracking using continuous radial MRI,” Magnetic Resonance in Medicine, vol. 37, pp. 963–968, June 1997. PMID: 9178250.
- G. C. Hurst, J. Hua, J. L. Duerk, and A. M. Cohen, “Intravascular (catheter) NMR receiver probe: preliminary design analysis and appli- cation to canine iliofemoral imaging,” Magnetic Resonance in Medicine: Official Journal of the Society of Magnetic Resonance in Medicine / Society of Magnetic Resonance in Medicine, vol. 24, pp. 343–357, Apr. 1992. PMID: 1569872.
- H. H. Quick, M. E. Ladd, G. G. Zimmermann-Paul, P. Erhart, E. Hof- mann, G. K. von Schulthess, and J. F. Debatin, “Single-loop coil concepts for intravascular magnetic resonance imaging,” Magnetic Reso- nance in Medicine: Official Journal of the Society of Magnetic Res- onance in Medicine / Society of Magnetic Resonance in Medicine, vol. 41, pp. 751–758, Apr. 1999. PMID: 10332851.
- L. V. Hofmann, R. P. Liddell, J. Eng, B. A. Wasserman, A. Arepally, D. S. Lee, and D. A. Bluemke, “Human peripheral arteries: feasibility of transvenous intravascular MR imaging of the arterial wall,” Radiology, vol. 235, pp. 617–622, May 2005. PMID: 15858101.
- M. Konings, L. Bartels, H. Smits, and C. Bakker, “Heating around intravascular guidewires by resonating RF waves,” J Magn Reson Imaging, vol. 12, p. 79–85, July 2000.
- T. Kuehne, S. Weiss, F. Brinkert, J. Weil, S. Yilmaz, B. Schmitt, P. Ew- ert, P. Lange, and M. Gutberlet, “Catheter visualization with resonant markers at MR imaging-guided deployment of endovascular stents in swine,” Radiology, vol. 233, p. 774–80, Dec. 2004.
- S. Hegde, M. Miquel, R. Boubertakh, D. Gilderdale, V. Muthurangu, S. Keevil, I. Young, D. Hill, and R. Razavi, “Interactive MR imaging and tracking of catheters with multiple tuned fiducial markers,” J Vasc Interv Radiol, vol. 17, p. 1175–9, July 2006.
- M. Burl, G. Coutts, and I. Young, “Tuned fiducial markers to iden- tify body locations with minimal perturbation of tissue magnetization,” Magn Reson Med, vol. 36, p. 491–3, Sept. 1996.
- H. H. Quick, M. O. Zenge, H. Kuehl, G. Kaiser, S. Aker, S. Massing, S. Bosk, and M. E. Ladd, “Interventional magnetic resonance angiog- raphy with no strings attached: wireless active catheter visualization,” Magnetic Resonance in Medicine: Official Journal of the Society of Magnetic Resonance in Medicine / Society of Magnetic Resonance in Medicine, vol. 53, pp. 446–455, Feb. 2005. PMID: 15678524.
- S. Weiss, T. Kuehne, F. Brinkert, G. Krombach, M. Katoh, T. Scha- effter, R. W. Guenther, and A. Buecker, “In vivo safe catheter visualiza- tion and slice tracking using an optically detunable resonant marker,” Magnetic Resonance in Medicine: Official Journal of the Society of Magnetic Resonance in Medicine / Society of Magnetic Resonance in Medicine, vol. 52, pp. 860–868, Oct. 2004. PMID: 15389956.
- O. Unal, F. Korosec, R. Frayne, C. Strother, and C. Mistretta, “A rapid 2D time-resolved variable-rate k-space sampling MR technique for passive catheter tracking during endovascular procedures,” Magn Reson Med, vol. 40, p. 356–62, Sept. 1998.
- O. Unal, J. Li, W. Cheng, H. Yu, and C. M. Strother, “MR-visible coatings for endovascular device visualization,” Journal of Magnetic Resonance Imaging: JMRI, vol. 23, pp. 763–769, May 2006. PMID: 16555229.
- D. Rubin, A. Ratner, and S. Young, “Magnetic susceptibility effects and their application in the development of new ferromagnetic catheters for magnetic resonance imaging,” Invest Radiol, vol. 25, p. 1325–32, Dec. 1990.
- V. Kochli, G. McKinnon, E. Hofmann, and G. von Schulthess, “Vascu- lar interventions guided by ultrafast MR imaging: evaluation of differ- ent materials,” Magn Reson Med, vol. 31, p. 309–14, Mar. 1994.
- C. Bakker, R. Hoogeveen, J. Weber, J. van Vaals, M. Viergever, and W. Mali, “Visualization of dedicated catheters using fast scanning techniques with potential for MR-guided vascular interventions,” Magn Re- son Med, vol. 36, p. 816–20, Dec. 1996.
- R. Mekle, E. Hofmann, K. Scheffler, and D. Bilecen, “A polymer-based MR-compatible guidewire: a study to explore new prospects for in- terventional peripheral magnetic resonance angiography (ipMRA),” J Magn Reson Imaging, vol. 23, p. 145–55, Feb. 2006.
- R. A. Omary, R. Frayne, O. Unal, T. Warner, F. R. Korosec, C. A. Mistretta, C. M. Strother, and T. M. Grist, “MR-guided angioplasty of renal artery stenosis in a pig model: a feasibility study,” Journal of Vascular and Interventional Radiology: JVIR, vol. 11, pp. 373–381, Mar. 2000. PMID: 10735435.
- J. F. Schenck, “The role of magnetic susceptibility in magnetic resonance imaging: MRI magnetic compatibility of the first and second kinds,” Medical Physics, vol. 23, pp. 815–850, June 1996. PMID: 8798169.
- J. Reichenbach, R. Venkatesan, D. Yablonskiy, M. Thompson, S. Lai, and E. Haacke, “Theory and application of static field inhomogene- ity effects in gradient-echo imaging,” J Magn Reson Imaging, vol. 7, p. 266–79, Apr. 1997.
- M. Stuber, W. Gilson, M. Schar, D. Kedziorek, L. Hofmann, S. Shah, E. Vonken, J. Bulte, and D. Kraitchman, “Positive contrast visual- ization of iron oxide-labeled stem cells using inversion-recovery with ON-resonant water suppression (IRON),” Magn Reson Med, vol. 58, p. 1072–7, Nov. 2007.
- C. Cunningham, T. Arai, P. Yang, M. McConnell, J. Pauly, and S. Conolly, “Positive contrast magnetic resonance imaging of cells labeled with magnetic nanoparticles,” Magn Reson Med, vol. 53, p. 999–1005, May 2005.
- J. Seppenwoolde, M. Viergever, and C. Bakker, “Passive tracking ex- ploiting local signal conservation: the white marker phenomenon,” Magn Reson Med, vol. 50, p. 784–90, Oct. 2003.
- E. Vonken, M. Schar, and M. Stuber, “Positive contrast visualization of nitinol devices using susceptibility gradient mapping,” Magn Reson Med, vol. 60, p. 588–94, Sept. 2008.
- H. Dahnke, W. Liu, D. Herzka, J. Frank, and T. Schaeffter, “Susceptibility gradient mapping (SGM): a new postprocessing method for positive contrast generation applied to superparamagnetic iron oxide particle (SPIO)-labeled cells,” Magn Reson Med, vol. 60, p. 595–603, Sept. 2008.
- J. Seppenwoolde, K. Vincken, and C. Bakker, “White-marker imaging- Separating magnetic susceptibility effects from partial volume effects,” Magn Reson Med, July 2007.
- Kapur T, Egger J, Damato A, Schmidt EJ, Viswanathan AN. 3-T MR-guided brachytherapy for gynecologic malignancies. Magnetic resonance imaging. 2012; 30(9):1279–1290.
- Müller-Bierl B, Graf H, Lauer U, Steidle G, Schick F. Numerical modeling of needle tip artifacts in MR gradient echo imaging. Medical physics. 2004; 31(3):579–587.
- Seevinck PR, de Leeuw H, Bos C, Bakker CJ. Highly localized positive contrast of small paramagnetic objects using 3D center-out radial sampling with off-resonance reception. Magnetic resonance in medicine. 2011; 65(1):146–156. [PubMed: 20740656]
- Mani V, Briley-Saebo KC, Itskovich VV, Samber DD, Fayad ZA. Gradient echo acquisition for superparamagnetic particles with positive contrast (GRASP): sequence characterization in membrane and glass superparamagnetic iron oxide phantoms at 1.5 T and 3T. Magnetic resonance in medicine. 2006; 55(1):126–135. 
- Bock M, Umathum R, Sikora J, Brenner S, Aguor E, Semmler W. A Faraday effect position sensor for interventional magnetic resonance imaging. Physics in medicine and biology. 2006; 51(4):999. 
- Scheffler K, Korvink J. Navigation with Hall sensor device for interventional MRI. 2004:950.
- Leung DA, Debatin JF, Wildermuth S, Heske N, Dumoulin CL, Darrow RD, Hauser M, Davis CP, von Schulthess GK. Realtime biplanar needle tracking for interventional MR imaging procedures. Radiology 1995; 197:485– 488.
- Wildermuth S, Debatin JF, Leung DA, Dumoulin CL, Darrow RD, Uhlschmid G, Hofmann E, Thyregod J, von Schulthess GK. MR imaging-guided intravascular procedures: initial demonstration in a pig model. Radiology 1997;202:578–583.
- Ladd ME, Zimmermann GG, McKinnon GC, von Schulthess GK, Du- moulin CL, Darrow RD, Hofmann E, Debatin JF. Visualization of vas- cular guidewires using MR tracking. J Magn Reson Imag 1998;8:251– 253.
- Ladd ME, Zimmermann GG, Quick HH, Debatin JF, Boesiger P, von Schulthess GK, McKinnon GC. Active MR visualization of a vascular guidewire in vivo. J Magn Reson Imag 1998;8:220–225.
- Ladd ME, Quick HH, Debatin JF. Interventional MRA and intravascular imaging. J Magn Reson Imag 2000;12:534–546.
- Lardo AC, McVeigh ER, Jumrussirikul P, Berger RD, Calkins H, Lima J, Halperin HR. Visualization and temporal/spatial characterization of cardiac radiofrequency ablation lesions using magnetic resonance im- aging. Circulation 2000;102:698 –705.
- Bottomley PA, Atalar E, Lee RF, Shunk KA, Lardo A. Cardiovascular MRI probes for the outside in and for the inside out. MAGMA 2000; 11:49 –51.
- Zhang Q, Wendt M, Aschoff AJ, Zheng L, Lewin JS, Duerk JL. Active MR guidance of interventional devices with target-navigation. Magn Reson Med 2000;44:56–65.
- Zhang Q, Wendt M, Aschoff AJ, Lewin JS, Duerk JL. A multielement RF coil for MRI guidance of interventional devices. J Magn Reson Imag 2001;14:56 – 62.
- Kuehne T, Fahrig R, Butts K. Pair of resonant fiducial markers for localisation of endovascular catheters at all catheter orientations. J Magn Reson Imag 2003;17:620–624.
- Bakker CJ, Hoogeveen RM, Hurtak WF, van Vaals JJ, Viergever MA, Mali WP. MR-guided endovascular interventions: susceptibility-based catheter and near-real-time imaging technique. Radiology 1997;202: 273–276.
- Omary RA, Unal O, Koscielski DS, Frayne R, Korosec FR, Mistretta CA, Strother CM, Grist TM. Real-time MR imaging guided passive catheter tracking with use of gadolinium-filled catheters. J Vasc Interv Radiol 2000;11:1079 –1085.
- Korosec FR, Frayne R, Grist TM, Mistretta CA. Time-resolved contrast- enhanced 3D MR angiography. Magn Reson Med 1996;36:345–531.
- Marc E. Miquel, Sanjeet Hegde, Vivek Muthurangu, Benjamin J. Corcoran, Stephen F. Keevil, Derek L.G. Hill, and Reza S. Razavi, "Visualization and Tracking of an Inflatable Balloon Catheter Using SSFP in a Flow Phantom and in the Heart and Great Vessels of Patients," Magnetic Resonance in Medicine 51:988–995 (2004)
- Shellock FG, Kanal E. Magnetic resonance—bioeffects, safety, and patient management. New York: Raven Press; 1994.
- Schenck JF. Safety issues in the MR environment. In: Debatin JF, Adam G, editors. Interventional magnetic resonance imaging. Heldelberg: Springer; 1997.
- Knopp MV, Essig M, Dubus J, Zabel HJ, von Kaick G. Unusual burns of the lower extremities caused by a closed conducting loop in a patient at MR imaging. Radiology 1996;2000:572–575.
- Shellock FG, Kanal E. Burns associated with the use of monitoring equipment during MR procedures. J Magn Reson Imag 1996;6:271–272.
- Nitz RW, Oppelt A, Renz W, Manke C, Lenhart M, Link J. On the heating of linear conductive structures as guide wires and catheters in interventional MRI. J Magn Reson Imag 2001;13:105–114.
- V. K. Raman, P. V. Karmarkar, M. A. Guttman, A. J. Dick, D. C. Peters, C. Ozturk, B. S. S. Pessanha, R. B. Thompson, A. N. Raval, R. DeSilva, R. J. Aviles, E. Atalar, E. R. McVeigh, and R. J. Leder- man, “Real-time magnetic resonance-guided endovascular repair of ex- perimental abdominal aortic aneurysm in swine,” Journal of the Amer- ican College of Cardiology, vol. 45, p. 2069–2077, June 2005. PMID: 15963411.
- F. K. Wacker, C. M. Hillenbrand, J. L. Duerk, and J. S. Lewin, “MR- guided endovascular interventions: device visualization, tracking, nav- igation, clinical applications, and safety aspects,” Magnetic Resonance Imaging Clinics of North America, vol. 13, p. 431–439, Aug. 2005. PMID: 16084411.
- R. Razavi, D. Hill, S. Keevil, M. Miquel, V. Muthurangu, S. Hegde, K. Rhode, M. Barnett, J. van Vaals, D. Hawkes, and E. Baker, “Cardiac catheterisation guided by MRI in children and adults with congenital heart disease,” Lancet, vol. 362, p. 1877–82, Dec. 2003.
- Thiele H, Nagel E, Paetsch I, Schnackenburg B, Bornstedt A, Kouwenhoven M, Wahl A, Schuler G, Fleck E. Functional cardiac MR imaging with steady-state free precession (SSFP) significantly improves endocardial border delineation without contrast agents. J Magn Reson Imag 2001;14:362–367.
- Martin AJ, Weber OM, Saeed M, Roberts TPL. Steady-state imaging for visualization of endovascular interventions. Magn Reson Imag 2003; 50:434 – 438.
- Duerk JL, Wong EY, Lewin JS. A brief review of hardware for catheter tracking in magnetic resonance imaging. MAGMA 2002;13:199–208.
- Erhart P, Ladd ME, Steiner P, Heske N, Dumoulin CL, Debatin JF. Tissue-independent MR tracking of invasive devices with an internal signal source. Magn Reson Med 1998;39:279–284.
- Gilderdale DJ, Williams AD, Dave U, deSouza NM. An inductively- coupled, detachable receiver coil system for use with magnetic resonance compatible endoscopes. J Magn Reson Imaging 2003;18: 131–135.
- Sandhu G. A solid marker material for MRI with adjustable relaxa- tion properties. Proc Intl Soc Magn Reson Med 2007;15:3385.
- Kugel H, Steppan G, Zaro Weber O, Krug B. [Artifacts in MR Imaging due to ventilation tubes]. Rofo 2001;173:949–954.
- Umathum R. Rubber materials for active device tracking. Proc Intl Soc Magn Reson Med 2008;16:1208.
- Stefan Alt, Ann-Kathrin Homagk, Reiner Umathum, Wolfhard Semmler, and Michael Bock, "Active Microcoil Tracking in the Lungs Using a Semisolid Rubber as Signal Source," Magnetic Resonance in Medicine 64:271–279 (2010)
- Rahmer J. Catheter visualization using rubber bands and ultrashort TE imaging. Proc Intl Soc Magn Reson Med 2008;16:1207.
- Bock M, Volz S, Zuhlsdorff S, Umathum R, Fink C, Hallscheidt P, Seminmler W. MR-guided intravascular procedures: real-time param- eter control and automated slice positioning with active tracking coils. J Magn Reson Imaging 2004;19:580–589.
- Wei Wang, Charles L. Dumoulin, Akila N. Viswanathan, Zion T. H. Tse, Alireza Mehrtash, Wolfgang Loew, Isaiah Norton, Junichi Tokuda, Ravi T. Seethamraju, Tina Kapur, Antonio L. Damato, Robert A. Cormack, and Ehud J. Schmidt, "Real-time active MR-tracking of metallic stylets in MR-guided radiation therapy," Magn Reson Med. 2015 May ; 73(5): 1803–1811.
- S. Patil, O. Bieri, P. Jhooti, and K. Scheffle, "Automatic Slice Positioning (ASP) for Passive Real-Time Tracking of Interventional Devices Using Projection- Reconstruction Imaging with Echo-Dephasing (PRIDE)," Magnetic Resonance in Medicine 62:935–942 (2009)
- Fabio Settecase, Alastair J. Martin, Prasheel Lillaney, Aaron Losey, Steven W. Hetts, "Magnetic Resonance– Guided Passive Catheter Tracking for Endovascular Therapy," Magn Reson Imaging Clin N Am 23 (2015) 591–605
- Frericks BB, Elgort DR, Hillenbrand C, et al. Magnetic resonance imaging-guided renal artery stent placement in a swine model: comparison of two tracking techniques. Acta Radiologica 2009;50(1): 21–7.
- F Galassi, D Brujic, M Rea, N Lambert, N Desouza, M Ristic, "Fast and accurate localization of multiple RF markers for tracking in MRI-guided interventions," Magnetic Resonance Materials in Physics, Biology and Medicine, vol. 28, pp. 33–48, 2015





Corresponding to the three key techniques mentioned above, we have 1) investigated the performance of a FPGA-based image registration method, 2) developed and a catheter robot using MR-safe hydraulically-driven actuation units and 3) examined an active coil for real-time catheter tracking. Results are elaborated as follows.




- fast image registration
- a catheter robot
- active tracking coils
- 
