* General info
  :PROPERTIES:
  :Directory: file:~/Work/HKU/MRcompatible_platform/
  :END:
  
* notes
* meeting

** TODO progress meeting
   SCHEDULED: <2016-06-15 Wed 15:00 +1w>
   - State "DONE"       from "TODO"       [2016-05-25 Wed 18:00]
   - State "DONE"       from "TODO"       [2016-05-18 Wed 18:00]
   - State "DONE"       from "TODO"       [2016-05-11 Wed 15:00]
   - State "DONE"       from "TODO"       [2016-05-04 Wed 17:00]
   - State "DONE"       from "TODO"       [2016-04-27 Thu 22:00]
   :PROPERTIES:
   :LAST_REPEAT: [2016-06-17 Fri 12:12]
   :END:

* tasks
** Dynamics modeling
   details are located below
*** TODO free body diagram
*** DONE combine equaitons and find necessary constraint equations
    CLOSED: [2016-05-06 Fri 11:14]
    - State "DONE"       from "TODO"       [2016-05-06 Fri 11:14]
*** TODO check friction model between gear and shaft (sliding friction)
*** TODO check friction model between gear and shaft (sliding friction)
*** TODO verification

** Paper
*** TODO draft paper for a journal
    outline is located below
    

*** TODO submit paper to RA Magazine Special Issue
    DEADLINE: <2016-08-01 Mon>
**** RAM submission info
http://www.ieee-ras.org/publications/ram/ram-special-issues/special-issues-on-surgical-robot-challenge

http://www.ieee.org/publications_standards/publications/authors/authors_journals.html

1. Preparing Your Manuscript

Submitted papers must be written in good understandable English. It is not the job of reviewers, associate editors or editor-in-chief to correct English spelling and grammar, and poorly written papers stand a much lower chance of being accepted. Authors wishing for assistance in this regard may consider using the IEEE proof editing service (fee based).

The submitted paper is submitted as a PDF file for review. There is no format or template requirement and you may use any tool at all (LaTeX, Word etc.) to prepare the PDF file. You might like to use the IEEE PDF checker to ensure that your file is compliant, and some hints on creating compliant PDF files using LaTeX. The IEEE Author Digital Tool Box has many helpful links including tools for correct reference formats.

A technical feature (regular or special issue) should meet the following requirements:

    No more than 9 magazine pages, so aim for no more than 4500 words of text
    No more than 10 equations
    No more than 20 references, unless it is a survey article
    No more than 10 figures
    Include at least one high quality color photograph of the robotic system
    Figures, tables, schematics, plots are very welcome
    PLEASE NOTE: figures need to be submitted in high-resolution, high-quality format such as JPEG, TIFF, EPS, etc. PDF files are not supported.

Be aware that mandatory page charges of USD 250 apply for every published page beyond 8 pages. If your paper has multimedia material then this should be prepared according to the guidelines and submitted at the same time as your PDF file.

If you have not previously submitted a paper to the magazine, you are strongly encouraged to peruse recent issues to familiarize yourself with the style and technical level of typical articles.


* DONE Hamlyn symposium robotic challenge 2-pages paper
  CLOSED: [2016-06-01 Wed 19:34]
  - State "DONE"       from ""           [2016-06-01 Wed 19:34]

** Project title

** Abstract

*** revised
Magnetic resonance imaging (MRI) techniques allows electrophysiologists to intra-operatively assess the ablation procedure during cardiovascular electrophysiology (EP); However, it is still challenging to carry out effective catheterization under MRI environment. We present a MRI-conditional catheter robotic system that integrates intra-operative MRI techniques, real-time visual feedback and effective control interface for catheter manipulation. Subject proved that the presented robotic system could enhance the performance of simulated ablation tasks.


*** Ziyan's original
Cardiac electrophysiology (EP) intervention is an effective treatment to arrhythmias. This project presents an MRI-conditional catheter robotic system that integrates intra-operative MRI, MR-based tracking units and enhanced visual guidance with catheter manipulation. The proposed system differs fundamentally from existing remotely controlled EP systems, of which the robotic manipulation is still challenging due to the very limited image guidance. This is the first system that provides a means of integrating intra-op MR imaging and tracking to improve the performance of tele-operated robotic catheterization.
** Introdution


*** revised
In cardiac EP intervention, a long catheter (>1m) is delivered to the heart chamber; Radiofrequency ablation (RFA) is performed on lesion tissue to isolate the abnormal eletrophysiological signals. The safety and effectiveness of EP intervention can be enhanced by introducing high quality intra-operative visual feedback of cardiac conditions and MR-compatible robotic platform for effective catheterization. Currently, neither any existing commercial nor research prototype of robotic catheterization platform is MR-conditional/safe. We present a MRI-conditional catheter robotic system for effective catheter manipulation that makes use of intra-operative MRI techniques, real-time visual feedback and an advanced kinematics control method.

*** Ziyan's original
In cardiac EP intervention, a long catheter (>1m) has to be delivered to the heart chamber, in which radiofrequency ablation (RFA) is performed on lesion tissue to isolate the abnormal eletrophysiological signals. Numerous patient trials under late gadolinium enhancement T2-weighted MRI have been conducted, which demonstrated safer and more effective EP intervention by monitoring the RFA under MRI. However, the ferromagnetic materials and conductive components in most catheter robots and steerable catheterization systems are forbidden from the use of MRI scanner due to its tremendously strong magnetic field generated. Furthermore, maneuvering of such a long and flexible catheter inside the cardiac chamber is still a challenging task even for the latest advances in the robotic-assisted platforms. Currently, neither any existing commercial nor research prototype of robotic catheterization platform is MR-conditional/safe. There is no well-established robot-human interface capable of continuously registering targets locations based on intra-operative MR images, and guiding the effective manipulation of the long, thin, flexible catheter.


** Methods

*** Effective MRI-compatible robotic platform: 
We construct a master-slave robotic platform made of MRI-safe, non-ferromagnetic materials for catheterization. Hydraulic transmission with water is adopted to guarantee zero EM interference with the MRI. The master actuators drive the slave actuators, which are isolated 10 m away in the MRI scanner room, providing steering, rolling, translation and fine advancement of a catheter mounted on the slave unit. To achieve effective actuation, we design the actuators with minimum backlash effect and install rolling diaphragms to reduce friction.

*** Real time, intra-operative visualization and position feedback for catheter navigation:
Based on intra-operative MR images, we construct and update a real-time 3D cardiac roadmap. We also employ a micro coil on the catheter tip that enables real-time (> 30 Hz), low latency (<3ms) and accurate (fine spatial resolution 0.6×0.6×0.6mm3) position tracking of the catheter. According to the position feedback, we attach a virtual camera at the a tip of the catheter to provide a virtual view for navigation.

*** User-friendly control interface with visual-motor alignment: 
User can manipulate the catheter by providing desired displacement in the virtual view via a motion input device. We develop a control method based on model-free online estimation of the kinematics relationship between the control input and the catheter tip position, achieving visual-motor alignment between the virtual camera attached to the catheter tip and the virtual.

*** Ziyan's original
Robot motion driven by MR-safe actuation unit: 
The actuator is fabricated by 3D printing, except for the rubber rolling diaphragm. As it is actuated by hydraulic power, the whole unit is MR-safe and remains minimized imaging disturbance in MR environment. The actuator consists of two identical hydraulic piston-actuators, a gear, two long flexible tubes (>10m) and a hydraulic pump. Each piston-actuator consists of a piston, a rolling diaphragm and a cylinder. The two tubes and the hydraulic pump connect the two piston-actuators with fixed amount of pressurized fluid filled inside. The rolling diaphragms act as flexible seals. The two piston-actuators and the gear are assembled such that the gear transmits translational motion of one piston to other piston in opposite direction. When the hydraulic pump forces the pressurized fluid from one cylinder to another by a piston inside, the change of the fluid volume in one cylinder induces pressure on the wall of the rolling diaphragm and pushes the piston out. Simultaneously, the other piston is push into the other cylinder by the force transmitted from the gear and the atmospheric pressure due to the decrease of fluid inside the cylinder. As a result, the pistons provide bidirectional translation and the gear provides bidirectional rotation.

Robot navigation of catheter using MR-based tracking unit: A tracking unit consist of a micro coil which could serve as an MRI-based signal marker and enable the real-time, frequent and continuous sampling of instrument positional tracking with respect to (w.r.t.) the image coordinates. While all the existing prototypes require (manual) selection of landmarks on MR images, e.g. fiducial marker, optical positional tracker. This small coil unit can enable virtual augmentation of instrument configuration on the MR imaging model precisely. It features with high rate position sampling (at >30 Hz) with low latency (<3ms) in fine spatial resolution of 0.6×0.6×0.6mm3). 

Human-robot control interface: We have developed a kinematic-model-free control framework capable of online estimating the motion mapping from the robot actuation to the tip displacement. This update is achieved by the means of a stochastic method that solely depends on previous measurements, namely the tracked position of the catheter tip. Subject test has shown significant improvement with this presented enhanced hand-eye coordination.

** Results

*** MRI-compatibility: 
- Negligible EM interference was verified by placing the operating robot closely to a commercial MRI phantom cylinder (#452213095955, CadMed+, USA), which was located at the isocenter of the scanner.

*** Ziyan's original
MRI-compatibility: Experimental validation with robot running under MRI have been conducted. The robot was placed closely to a commercial MRI phantom cylinder (#452213095955, CadMed+, USA), which was located at the isocenter of the scanner.

Subject test: Subject tests (10, age ranging from 20-35) were carried out for evaluation, where the pulmonary vein isolation ablation tasks were simulated using the robotic experimental setup. Each subject performed the same task under two different conditions: 1) Only the fly-through view (Fig. 1a) was provided without the proposed control approach. 2) Fly-through view and the virtual camera view (Fig. 1b) were provided, where the proposed visual-motor alignment was employed. Each had to perform RF ablation on pre-defined lesions within 5 minutes. The RF ablation at the catheter tip was activated by a foot pedal.

*** Subject test:
- Subject (10 people(surgeons), age ranging from 20-35) tests of simulated RF ablation tasks using the presented robotic system were carried. 
- It was observed that the visual-motor alignment control interface improved the accuracy (detailed data needed) of the task.
** Discussion

*** revised
To the best of our knowledge, this is the first robotic systems for image-guided robot-assisted catheterization that integrates intra-operative MRI, real-time visual and position feedback and visual-motor alignment.
It i) enhances the catheter manipulation accuracy to desired surgical region, thus decreasing the chances of recurrence (e.g. currently 30% in atrial fibrillation and 50% in ventricular tachycardia after electrophysiology procedure), 
compensating the cost of using MRI and reducing the overall expenditure; 
ii) improves the safety of catheter navigation, thereby decreasing the rates of undesired damage; 
iii) eases catheter manipulation, thus facilitating the shorter learning curve for surgeons and better treatment for more complex cases. 
For the cardiac EP procedure, it is anticipated that our invention will significantly reduce the chance of post-recurrence of arrhythmia, which cannot be achieved by the current state-of-the-art robot EP catheter system. 

*** Ziyan's original
The effective maneuvering of a long and flexible catheter (about 1.5m) to the desired target points under highly dynamic environment still remains a great challenge. While the current 3D roadmap used for catheter manipulation guidance is static and computed from MRI. This is the first system that provides a means of integrating intra-operative MR imaging and tracking to improve the performance of tele-operated robotic catheterization. The contributions of this system are considered to be: precise MR-safe actuators incorporated in the robotic catheter manipulator; a real-time tracking system with MR-based tracking coils embedded at the tip of catheter, updating the position and shape of catheter by magnetic resonance imaging (MRI); a human-robot control interface with frequently-updated 3D roadmap, offering the intuitive instrument navigation.




*** context in patent application
Through the use of our presented catheter robot featured with MR-based position feedback units integrated with the catheter, we could
- provide a precise and real-time visual feedback to the operator during the catheter navigation under the MRI. 
- Sharing the same MR-tracking coordinates with the MR images can guarantee correct alignment of the virtual catheter configuration relative to the cardiac imaging models, thereby benefiting to various kinds of cardiovascular catheter intervetion. 
- Combined with the robotic manipulation of the catheter, 
- not only could the ablation progress be monitored by MRI, but it also enables the operator to re-target the insufficiently ablated lesions readily through the tele-operated manipulation of the catheter in the control room. 


Currently, neither any existing commercial robotic catheterization platform, nor any research prototype providing full manipulation of 
catheter, could be safely operated in MRI environment. There is also no well-established robot-human interface capable of continuously update surgical roadmap and catheter location based on MR images. 
- This system is the first catheter robot to be integrated with MRI-compatible actuation, MR-based tracking system, and the 3D surgical roadmap registered with intra-operative MR images. 
- It represents a major step in achieving several goals: i) enhancing the catheter manipulation and access to desired surgical region, thus decreasing the chances of recurrence (e.g. currently 30% in atrial fibrillation and 50% in ventricular tachycardia after electrophysiology procedure), 
compensating the cost of using MRI and reducing the overall expenditure; 
ii) improving the safety of catheter navigation, thereby decreasing the rates of undesired damage; 
iii) enhancing the catheter control, thus facilitating the shorter learning curve for surgeons and better treatment for more complex cases. 



This system is the first catheter robot to be integrated with MRI-compatible actuation, MR-tracking system, and the 3D surgical roadmap registered with intra-operative MR images. The successfully developed components of this system could be further implemented in other robot-assisted interventions, particularly those using MRI navigation on rapidly physiological-changed tissues. Our study may serve as a benchmark for the design and integration of MR-conditional robotic devices


** References
- S.Nazarian, A. Kolandaivelu, M. M. Zviman, G. R. Meininger, R. Kato, R. C. Susil, A. Roguin, T. L. Dickfeld, H. Ashikaga, H. Calkins, R. D. Berger, D. A. Bluemke, A. C. Lardo, and H. R. Halperin, "Feasibility of real-time magnetic resonance imaging for catheter guidance in electrophysiology studies," Circulation, vol. 118, pp. 223--229, 2008
- E. J. Schmidt, R. P. Mallozzi, A. Thiagalingam, G. Holmvang, A. d'Avila, R. Guhde, R. Darrow, G. S. Slavin, M. M. Fung, J. Dando, L. Foley, C. L. Dumoulin, and V. Y. Reddy, "Electroanatomic Mapping and Radiofrequency Ablation of Porcine Left Atria and Atrioventricular Nodes Using Magnetic Resonance Catheter Tracking," Circulation-Arrhythmia and Electrophysiology, vol. 2, pp. 695-+, Dec 2009
- D. C. Peters, J. Hsing, K. V. Kissinger, B. Goddu, R. Nezafat, J. E. Taclas, M. E. Josephson, J. V. Wylie, and W. J. Manning, "T2-Weighted Imaging of the Left Atrium Acutely After Pulmonary Vein Isolation Demonstrates Wall Thickening and Edema," ISMRM Proceedings, 2009.
- M. Shurrab, R. Schilling, E. Gang, E. M. Khan, and E. Crystal, "Robotics in invasive cardiac electrophysiology," Expert Rev Med Devices, vol. 11, pp. 375-81, Jul 2014.

** Figure


* Dynamic modeling
*** elements for modeling
**** motor gear connected to the stepper motor power source
**** piston 1
     connected to the motor gear **** water 1
     water inside upper pipeline
**** spring-damper 1
     between piston 1 and water 1
**** spring-damper 2
     between water 1 and piston 2
**** piston 2
     connected to the gear end effector
**** gear end effector 
     connected to the end effector
**** piston 3
     connected to the gear end effector
**** spring-damper 3
     between piston 3 and water 2
**** water 2
     water inside lower pipeline
**** spring-damper 4
     between water 2 and piston 4
**** piston 4
     connected to the motor gear *** symbol notations
    
    | <30>                           | <20>                 | <10>       | <30>                           | <15>            |
    | Description                    | symbols              | physical parameters (P)/kinematics parameters (K)/force variable (F) | how to get                     | component       |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | motor gear inertia             | I_m                  | P          | experimment                    | motor gear      |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | motor gear radius              | r_m                  | P          | design                         | motor gear      |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | motor gear angular displacement | \theta_m (cw \+)     | K          | system input/output            | motor gear      |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | torque by stepper motor        | \tau_m               | F          | system input                   | motor gear      |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | frictional torque at motor gear joint | \hat \tau_m          | F          | \mu_m,f_R,r_m                  | motor gear      |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | frictional coefficient at motor gear joint | \mu_m                | P          | experiment                     | motor gear      |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | reaction forces of the moment couple at the two contact points | f_m                  | F          | internal                       | motor gear      |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | pressure force from water      | f_wp                 | F          | f_R                            |                 |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | reaction force at joint        | f_R                  | F          | f_wp                           | motor gear      |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | displacement of piston 1       | x_1 (right \+)       | K          | \theta_m                       | piston 1        |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | mass of piston 1               | m_m                  | P          | design                         | piston 1        |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | spring constant                | k                    | P          | k=B\frac{A}{L}                 | water 1         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | damping coefficient of water   | d                    | P          | experiment                     | water 1         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | bulk constant of water         | B                    | P          | design (literature)            | water 1         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | cross section area of pipeline 1 | A                    | P          | design                         | pipeline 1      |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | length of pipeline 1           | L                    | P          | design                         | pipeline  1     |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | displacement of water 1        | x_{w1}               | K          | internal                       | water 1         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | mass of water          1       | m_w                  | P          | design                         | water 1         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | friction inside pipeline       | \hat f_{w1}          | F          | \hat f_{w1} = H_{f1} \rho g A  | water 1         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | frictional weight of pipeline  | H_{f1}               |            | H_{f1} = \frac{\bar f L ({\dot x_{w1}})^2}{2gd}$ | water 1         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | frictional constant of pipeline | \bar f               | P          | \bar f = \frac{64}{Re}         | water 1         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | Reynolds number                | Re                   | P          | design (literature)            | water 1         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | displacement of piston 2       | x_2 (right \+)       | K          | \theta_e                       | piston 2        |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | mass of piston 2               | m_e                  | P          | design                         | piston 2        |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | inertia of effector gear       | I_e                  | P          | design                         | effector gear   |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | radius of effector gear        | r_e                  | P          | design                         | effector gear   |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | resulting moment               | \tau_e               | F          | \tau_e = f_e r_e               | effector gear   |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | resulting couple               | f_e                  | F          | \tau_e = f_e r_e               | effector gear   |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | reaction force at joint        | f_{Re}               | F          | f_{Re} = 2 f_{wp}              | effector gear   |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | frictional torque              | \hat \tau            | F          | \mu_e , f_{Re}, r_e            | effector gear   |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | angular displacement of effector gear | \theta_e             | K          | system output                  | effector gear   |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | displacement of piston 3       | x_3 (left \+)        | K          | \theta_e                       | piston 3        |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | displacement of water 2        | x_{w2}               | K          | internal                       | water 2         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | mass of water 2                | m_w                  | P          | design                         | water 2         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | friction inside pipeline       | \hat f_{w2}          | F          | H_{f2} = \frac{\bar f L ({\dot x_{w2}})^2}{2gd}$ | water 2         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | frictional weight of pipeline  | H_{f2}               | F          | H_{f2} = \frac{\bar f L ({\dot x_{w2}})^2}{2gd}$ | water 2         |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | displacement of piston 4       | x_4 (left \+)        | K          | \theta_m                       | piston 4        |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|
    | mass of piston 4               | m_m                  | P          | design                         | piston 4        |
    |--------------------------------+----------------------+------------+--------------------------------+-----------------|

    

*** free body diagrams 

*** combine equations and Find necessary constraint equations
    |               |                                                                                                                                                                                             |                   |                     |
    | rigid body    | equations of motion                                                                                                                                                                         | unknown variables | number of equations |
    |---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------|
    | motor gear    | \tau_m - \hat \tau_m = I_m(\ddot \theta_m)                                                                                                                                                  |                   |                     |
    |               | \hat \tau_m = \mu_m abs(f_R) r_m                                                                                                                                                            |                   |                     |
    |               | f_R = 2f_{wp}                                                                                                                                                                               |                   |                     |
    |               | \tau_m = f_m r_m                                                                                                                                                                            |                   |                     |
    |               |                                                                                                                                                                                             |                   |                     |
    |               | \tau_m - 2 \mu_m r_m abs(f_{wp})  = I_m (\ddot \theta_m)                                                                                                                                    | \f_{wp}           |                     |
    |               |                                                                                                                                                                                             | (f_m,\tau_m)      |                     |
    |---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------|
    | piston 1      | f_m - k(x_1 - x_{w1}) - d({\dot x}_1 - {\dot x}_{w1}) = m_m {\ddot x_1}                                                                                                                     |                   |                     |
    |               | x_1 = \theta_m r_m                                                                                                                                                                          |                   |                     |
    |               |                                                                                                                                                                                             |                   |                     |
    |               | \frac{\tau_m}{r_m} - k(\theta_m r_m - x_{w1}) - d( {\dot \theta}_m r_m - {\dot x}_{w1}) = r_m m_m {\ddot \theta}_m                                                                          | x_{w1}            |                     |
    |               |                                                                                                                                                                                             | (f_m)             |                     |
    |---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------|
    | water 1       | k(x_1-x_{w1}) + d({\dot x}_1 - {\dot x}_{w1}) - k(x_{w1}-x_2) - d({\dot x}_{w1} - {\dot x}_2) - \hat f_{w1} = m_w {\ddot x}_{w1}                                                            |                   |                     |
    |               | \hat f_{w1} = H_{f1} \rho g A                                                                                                                                                               |                   |                     |
    |               | H_{f1} = \frac{\bar f L ({\dot x_{w1}})^2}{2gd}                                                                                                                                             |                   |                     |
    |               | \bar f = \frac{64}{Re}                                                                                                                                                                      |                   |                     |
    |               | x_1 = \theta_m r_m                                                                                                                                                                          |                   |                     |
    |               | {\dot x}_1 = r_m {\dot \theta}_m                                                                                                                                                            |                   |                     |
    |               | x_2 = \theta_e r_e                                                                                                                                                                          |                   |                     |
    |               | {\dot x}_2 = r_e {\dot \theta}_e                                                                                                                                                            |                   |                     |
    |               |                                                                                                                                                                                             |                   |                     |
    |               | r_m k(\theta_m) + r_m d({\dot \theta_m}) - 2 k(x_{w1}) - 2 d({\dot x}_{w1})  + r_e k(\theta_e) + r_e d({\dot \theta}_e) - \frac{32 \rho A L ({\dot x_{w1}})^2 }{Re d}  = m_w {\ddot x}_{w1} |                   |                     |
    |---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------|
    | piston 2      | - f_e + k(x_{w1}) - k(x_2) + d({\dot x}_{w1}) - d({\dot x}_2) = m_e {\ddot x}_2                                                                                                             |                   |                     |
    |               |                                                                                                                                                                                             |                   |                     |
    |               | - f_e + k(x_{w1}) - r_e k(\theta_e) + d({\dot x}_{w1}) - r_e d({\dot \theta}_e) = r_e m_e {\ddot \theta}_e                                                                                  |                   |                     |
    |---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------|
    | effector gear | \tau_e - \hat \tau_e = I_e({\ddot \theta_e})                                                                                                                                                |                   |                     |
    |               | \hat \tau_e = \mu_e abs(f_{Re}) r_e                                                                                                                                                         |                   |                     |
    |               | f_{Re} = 2f_{wp}                                                                                                                                                                            |                   |                     |
    |               | \tau_e = f_e r_e                                                                                                                                                                            |                   |                     |
    |               |                                                                                                                                                                                             |                   |                     |
    |               | f_e r_e - \mu_e abs(2f_{wp}) r_e = I_e (\ddot \theta_m)                                                                                                                                     |                   |                     |
    |---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------|
    | piston 3      | - f_e - k(x_{3}) + k(x_{w2}) - d({\dot x}_3) + d({\dot x}_{w2}) = m_e {\ddot x}_3                                                                                                           |                   |                     |
    |               | x_3 = x2 = \theta_e r_e                                                                                                                                                                     |                   |                     |
    |               |                                                                                                                                                                                             |                   |                     |
    |               | - f_e - r_e k(\theta_e) + k(x_{w2}) - r_e d({\dot \theta}_e) + d({\dot x}_{w2}) = r_e m_e {\ddot \theta}_e                                                                                  |                   |                     |
    |---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------|
    | water 2       | k(x_3-x_{w2}) + d({\dot x}_3 - {\dot x}_{w2}) - k(x_{w2}-x_4) - d({\dot x}_{w2} - {\dot x}_4) - \hat f_{w2} = m_w {\ddot x}_{w2}                                                            |                   |                     |
    |               | \hat f_{w2} = H_{f2} \rho g A                                                                                                                                                               |                   |                     |
    |               | H_{f2} = \frac{\bar f L ({\dot x_{w2}})^2}{2gd}                                                                                                                                             |                   |                     |
    |               | \bar f = \frac{64}{Re}                                                                                                                                                                      |                   |                     |
    |               | x_4 = x_1 = \theta_m r_m                                                                                                                                                                    |                   |                     |
    |               |                                                                                                                                                                                             |                   |                     |
    |               | r_e k(\theta_e) + r_e d({\dot \theta}_e) - 2k(x_{w2}) - 2d({\dot x}_{w2}) + r_m k(\theta_m) + r_m d({\dot \theta}_m) - \frac{32 \rho A L ({\dot x_{w2}})^2 }{Re d}  = m_w {\ddot x}_{w2}    |                   |                     |
    |---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------|
    | piston 4      | f_m + k(x_{w2}) - k(x_4) + d({\dot x}_{w2}) - d({\dot x}_4) = m_m {\ddot x}_4                                                                                                               |                   |                     |
    |               | \tau_m = f_m r_m                                                                                                                                                                            |                   |                     |
    |               |                                                                                                                                                                                             |                   |                     |
    |               | \frac{\tau_m}{r_m} + k(x_{w2}) - r_m k(\theta_m) + d({\dot x}_{w2}) - r_m d({\dot \theta}_m) = r_m m_m {\ddot \theta}_m                                                                     |                   |                     |
    |---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------|




|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---|
| f_e r_e - 2 \mu_e r_e abs(f_{wp}) = I_e (\ddot \theta_e)                                                                                                                                          |   |
| \tau_m - 2 \mu_m r_m abs(f_{wp})  = I_m (\ddot \theta_m)                                                                                                                                          |   |
| \frac{\tau_m}{r_m} + k(x_{w2}) - r_m k(\theta_m) + d({\dot x}_{w2}) - r_m d({\dot \theta}_m) = r_m m_m {\ddot \theta}_m                                                                           |   |
| \frac{\tau_m}{r_m} - k(\theta_m r_m - x_{w1}) - d( {\dot \theta}_m r_m - {\dot x}_{w1}) = r_m m_m {\ddot \theta}_m                                                                                |   |
| - f_e + k(x_{w1}) - r_e k(\theta_e) + d({\dot x}_{w1}) - r_e d({\dot \theta}_e) = r_e m_e {\ddot \theta}_e                                                                                        |   |
| - f_e - r_e k(\theta_e) + k(x_{w2}) - r_e d({\dot \theta}_e) + d({\dot x}_{w2}) = r_e m_e {\ddot \theta}_e                                                                                        |   |
| r_m k(\theta_m) + r_m d({\dot \theta_m}) - 2 k(x_{w1}) - 2 d({\dot x}_{w1})  + r_e k(\theta_e) + r_e d({\dot \theta}_e) - \frac{32 \rho A L ({\dot x_{w1}})^2 }{Re \cdot d}  = m_w {\ddot x}_{w1} |   |
| r_e k(\theta_e) + r_e d({\dot \theta}_e) - 2k(x_{w2}) - 2d({\dot x}_{w2}) + r_m k(\theta_m) + r_m d({\dot \theta}_m) - \frac{32 \rho A L ({\dot x_{w2}})^2 }{Re \cdot d}  = m_w {\ddot x}_{w2}    |   |
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---|
| f_e r_e - 2 \mu_e r_e abs(f_{wp}) = I_e (\ddot \theta_e)                                                                                                                                          |   |
| \tau_m - 2 \mu_m r_m abs(f_{wp})  = I_m (\ddot \theta_m)                                                                                                                                          |   |
| k(x_{w1}-x_{w2}) + d({\dot x}_{w1}-{\dot x}_{w2}) = 0                                                                                                                                             |   |
| k(x_{w1}-x_{w2}) + d({\dot x}_{w1}-{\dot x}_{w2}) = 0                                                                                                                                             |   |
| -> x_{w1} = x_{w2} = x_w                                                                                                                                                                          |   |
|                                                                                                                                                                                                   |   |
| r_m k(\theta_m) + r_m d({\dot \theta_m}) - 2k(x_{w1}) - 2d({\dot x}_{w1}) + r_e k(\theta_e) + r_e d({\dot \theta}_e) - \frac{32 \rho A L ({\dot x_{w1}})^2 }{Re \cdot d}  = m_w {\ddot x}_{w1}    |   |
| r_e k(\theta_e) + r_e d({\dot \theta}_e) - 2k(x_{w2}) - 2d({\dot x}_{w2}) + r_m k(\theta_m) + r_m d({\dot \theta}_m) - \frac{32 \rho A L ({\dot x_{w2}})^2 }{Re \cdot d}  = m_w {\ddot x}_{w2}    |   |
| -> r_m k(\theta_m) + r_m d({\dot \theta_m}) + r_e k(\theta_e) + r_e d({\dot \theta}_e) - 2k(x_{w}) - 2d({\dot x}_w) - \frac{32 \rho A L ({\dot x_{w}})^2}{Re \cdot d} = m_w {\ddot x}_w           |   |
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---|
| I_e (\ddot \theta_e) + 2 \mu_e r_e abs(f_{wp}) - f_e r_e = 0                                                                                                                                      |   |
| I_m (\ddot \theta_m) + 2 \mu_m r_m abs(f_{wp}) - \tau_m = 0                                                                                                                                       |   |
| m_w {\ddot x}_w + \frac{32 \rho A L ({\dot x_{w}})^2}{Re \cdot d} + 2d({\dot x}_w) + 2k(x_{w}) - r_m d({\dot \theta_m}) - r_m k(\theta_m) - r_e k(\theta_e) - r_e d({\dot \theta}_e)  = 0         |   |
| - f_e = - k(x_{w1}) + r_e k(\theta_e) - d({\dot x}_{w1}) + r_e d({\dot \theta}_e) + r_e m_e {\ddot \theta}_e                                                                                      |   |
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---|
| I_m (\ddot \theta_m) + 2 \mu_m r_m abs(f_{wp}) - \tau_m = 0                                                                                                                                       |   |
| m_w {\ddot x}_w + \frac{32 \rho A L ({\dot x_{w}})^2}{Re \cdot d} + 2d({\dot x}_w) + 2k(x_{w}) - r_m d({\dot \theta_m}) - r_m k(\theta_m) - r_e k(\theta_e) - r_e d({\dot \theta}_e)  = 0         |   |
| (I_e + (r_e)^2 m_e) (\ddot \theta_e) + (r_e)^2 d({\dot \theta}_e) + (r_e)^2 k(\theta_e) - r_e d({\dot x}_{w}) - r_e k(x_{w}) + 2 \mu_e r_e abs(f_{wp})  = 0                                       |   |
|                                                                                                                                                                                                   |   |

| \ddot \theta_m | \ddot x_w | \ddot \theta_e    | \dot \theta_m | \dot x_w | \dot \theta_e | (\dot x_w)^2                   | \theta_m | x_w    | \theta_e  | u                       |
|----------------+-----------+-------------------+---------------+----------+---------------+--------------------------------+----------+--------+-----------+-------------------------|
| I_m            |           |                   |               |          |               |                                |          |        |           | 2 \mu_m r_m abs(f_{wp}) |
|                | m_w       |                   | -r_m d        | 2 d      | -r_e d        | \frac{32 \rho A L}{Re \cdot d} | -r_m k   | 2 k    | -r_e k    |                         |
|                |           | I_e + (r_e)^2 m_e |               | -r_e d   | (r_e)^2 d     |                                |          | -r_e k | (r_e)^2 k | 2 \mu_e r_e abs(f_{wp)  |
|                |           |                   |               |          |               |                                |          |        |           |                         |

\begin{pmatrix}
I_m & 0 & 0\\
0 & m_w & 0\\
0 & 0 & I_e + (r_e)^2 m_e
\end{pmatrix}
\begin{pmatrix}
\ddot \theta_m\\
\ddot x_w\\
\ddot \theta_e
\end{pmatrix}
+ 
\begin{pmatrix}
0 & 0 & 0\\
-r_m d & 2 d & -r_e d\\
0 & -r_e d & (r_e)^2 d
\end{pmatrix}
\begin{pmatrix}
\dot \theta_m\\
\dot x_w\\
\dot \theta_e
\end{pmatrix}
+ 
\begin{pmatrix}
0 & 0 & 0\\
0 & \frac{32 \rho A L}{Re \cdot d} & 0\\
0 & 0 & 0
\end{pmatrix}
\begin{pmatrix}
(\dot \theta_m)^2\\
(\dot x_w)^2\\
(\dot \theta_e)^2
\end{pmatrix}
+ 
\begin{pmatrix}
0 & 0 & 0\\
-r_m k & 2 k & -r_e k\\
0 & -r_e k & (r_e)^2 k
\end{pmatrix}
\begin{pmatrix}
 \theta_m\\
 x_w\\
 \theta_e
\end{pmatrix}
+ 
\begin{pmatrix}
2 \mu_m r_m abs(f_{wp})\\
0\\
 2 \mu_e r_e abs(f_{wp})
\end{pmatrix}
=0

*** check friction model between gear and shaft (sliding friction)
*** verification


* paper draft for a journal
** Title
   Design of a Robotic Platform for MRI-guided Cardiac Electrophysiology (EP)
** Introdution
*** Cardiac electrophysiology is an effective surgical treatment for diagnosis and treatment of heart
**** What is Cardiac Electrophysiology  (Definition)
     - In EP, electrophysiologists insert a 1.5m catheter from femoral vein to the heart chamber where radiofrequency ablation (RFA) is conducted via the catheter tip on the lesion tissue to isolate the abnormal electrophysiological signals that cause arrhythmias
**** Current methods using robotic platform/procedure and associated problems: learning curve, cost, preparation time, accuracy, efficiency 
     - In conventional EP, fluoroscopy and ultrasound are adopted to visualize the catheter configuration inside the heart chamber.
**** Deduce to the need of MRI-guided
     - However, the visualization can only provide rough information inside the heart chamber for RFA.
*** MRI techniques can facilitate EP, however, there is still no MR-compatible platform for EP
**** Why catheterization has to be done inside MRI
     - Magnetic resonance imaging (MRI) offers excellent images contrast for cardiovascular soft tissue for construction of clear 3D cardiac roadmap [3,4], which enables intra-operative (intra-op) visualization of RFA-induced physiological changes, thus allowing electrophysiologists to promptly determine whether the treatment of particular lesions is complete or requires further ablation.
     - T2-weighted MRI [5,6] can also readily visualize the edema [6] and scar tissue [7] from successful or incomplete RFA
**** Current progress of MR-compatible platform, list some examples of catheter robot.
     - Sensei Robotic system [12] is a well-known commercial platform for intra-cardiac EP intervention
     - Hansen Sensei X, Amigo Remote Catheter System, Stereotaxis Niobe are industry-leading EP robots
     - All the above robots are MR-incompatible
     - Currently, no MR-compatible commercial robotic platform for EP is available
     - [31] is actuated by non-ferromagnetic,  ultrasonic motors driven by electric current, providing only two DOFs of catheter. However, because the motors are placed close to the scanner, the driving and encoding signals would induce electromagnetic (EM) noise to MRI.
     - Ultrasonic motors reduce of SNR ratio, though can be treated by installing amplifier and carefully shield electronics at the expense of system cost [Su2012]
     - Recently, a MR-compatible pneumatic stepper motor has been developed [39], showing   better performance than existing ones in [57-59], however, the operation speed is still too slow for driving catheter advancement or rotation.
     - "Pneumatic actuators are MR-compatible and do not cause SNR reduction, but they do require a complicated installation that involves locating a control unit, power supplies, amplifiers and valves external to the MRI shielded room (Patriciu et al., 2007; Li et al., 2011; Tokuda et al., 2012). Furthermore, the pneumatic transmission lines lower the bandwidth and, in combination with the spatial con- straints of the MRI bore, complicate robot design (Song et al., 2011).” [Vartholomeos2013]
**** [What makes development/applications of MR-compatible robots difficult]
     - Complex EM-shielded enclosure is required to surround on all sides of the motor drivers
     - It is also technically difficult to filter the motor control signals at high frequency, but without degrading the motor operation [33].
**** [Deduce to the need of implementation MR-compatible actuators for EP]
     - Actuators driven by other non-electromagnetical mechanism such as pressured air flow are attracting attention for development of MR-compatible robotic platform [34]

*** Hydraulic mechanism can provide MR-compatible, efficient and precise actuation for EP.
**** [Any used for medical application? ]
**** [What is rolling diaphragm (RD) and its characteristics ]
     - Frictionless
**** [Any other MR-compatible actuation mechanism? Why they are not chosen in this research?]
*** We design and fabricate the first MR-compatible, efficient robot for cardiac EP
**** State clearly main features of our design that facilitate cardiac catheterization 
- Rolling diaphragms are actuated by pressurized clear air (at 30-60 psi) supplied by the medical piped gas systems guarantees zero EM interference with the MRI
- Fast and precise manipulation of the advancement, steering and rotation of catheter can be achieved
  
** Clinical Motivation /MRI-Guided EP
    - (may be combined with the introductin section)
*** Cardiac EP for heart arrhythmia and ablation is the one demanding for dexterous control of catheter for tissue ablation
- Show data support obtained from American Heart Association (AHA) and Center for Disease Control (CHC)
*** The basic operation of EP is described as follows
- [Fig: illustrating the basic operation of EP, and the catheter configuration inside the anatomy]
- [Emphasize particular procedure and associated problems/difficulties]
- [Insertion done by junior surgeon]
*** A MR-guided catheterization can facilitate diagnosis and treatment
- How?
- Fig: showing the ablation features visualized on late-gadolinium MR images
*** Deduce to the need of our design
    
** The MR-compatible Robotic Platform
A MR-compatible, high performance robot has been developed for EP operation. Fig. shows the appearance of the robot. The robot is used to manipulate a catheter tip that locates near to the target heart tissue. During an EP operation, a surgeon use a controller to operate the catheter (Fig. ). In order to achieve effective manipulation of a catheter during a MRI-guided EP, the robot is developed to fulfil the following requirements:
+ The robot must be solely made of MR-compatible material.
+ The robot can give advancement, steering and rotation of a catheter that mounted on the robot during EP operation.
+ The robot is capable of response fast enough to the surgeon’s control inputs with negligible backlash.
+ The actuators have to provide precise displacement with sufficient output torque.
+ The size of the robot must not be too bulky and compactly assembled.

*** MR-compatible hydraulic actuator
**** The core of the MR-compatible platform is an efficient hydraulic actuator capable of providing precise bidirectional rotation or translation actuation depicted in Fig. .  
The actuator consists of two identical hydraulic piston-actuators, a gear, two long flexible tubes (>10m) and a hydraulic pump. 
Each piston-actuator consists of a piston, a rolling diaphragm and a cylinder. The two tubes and the hydraulic pump connect the two piston-actuators with fixed amount of pressurized fluid filled inside. 
The rolling diaphragms act as flexible seals. The two piston-actuators and the gear are assembled such that the gear transmits translational motion of one piston to other piston in opposite direction. 
When the hydraulic pump forces the pressurized fluid from one cylinder to another by a piston inside, the change of the fluid volume in one cylinder induces pressure on the wall of the rolling diaphragm and pushes the piston out. 
Simultaneously, the other piston is push into the other cylinder by the force transmitted from the gear and the atmospheric pressure due to the decrease of fluid inside the cylinder. 
As a result, the pistons provide bidirectional translation and the gear provides bidirectional rotation.
**** All the components except the hydraulic pump, which is isolated in a zero-EM-interference room, are made of MR-compatible and medical safe materials.
**** The proposed design together with the use of pressurized fluid can prevent backlash at the gear.
The gear and the piston shafts are not seamlessly contacted. Backlash refers to the phenomenon when the piston leaves contact with the gear such that motion cannot be transmitted. 
The pressurized fluid inside the two cylinders always provides force to push the two pistons out. 
Consequently, the teeth of the piston are forced to seamlessly contact with the teeth of the gear, thereby preventing backlash (Fig. ).
- (Existing bidirectional actuator designs such as [] usually has only one shaft and thus backlash is inevitable (Fig. ).)
**** The proposed design effectively converts the change of fluid volume inside the cylinders to the translational motion of the piston, based on the characteristics of negligible backlash and all the piston, rolling diaphragms and the gear are seamlessly assembled. 
Also, the coplanarity of the gear and the two piston shafts helps to effectively transmit the translational motion from one piston shaft to another. 
Moreover, the rolling diaphragms provide negligible friction between the pistons and the inner walls of the cylinders [] such that the energy loss during operation can be reduced.  
Although energy loss and response delay will likely occur because the volume of the pressurized fluid and the volume of the long flexible tubes will possibly be altered during operation, in practice and as will be shown in section XXX, the response is negligible that the piston react once the surgeon gives control input.
**** There are cases that require larger range of rotation.
For instance, the rotation of catheter may need more than 360 degree to produce a 360 degree sweeping motion of the tip inside the heart chamber, because torsion may occur in the long (>1.5m) catheter. 
However, the range of the rotation of the gear is limited by the stroke length and the diameter of the rolling diaphragms, because the gear is placed between the two piston shafts, as illustrated in Fig. . 
**** Two types of assembly are designed for different requirement of range of rotation of the gear.
Figure depicts the two designs in which the two cylinders are assembled in parallel-shape and in V-shape. 
In the following context, we refer them as the P-type actuator and the V-type actuator, respectively. 
The V-type actuator has larger range of rotation than that of the P-type because a smaller gear can be installed and thus produces larger range of rotation of the gear.
There is a trade-off between the maximum range of rotation and the resolution. 
Under the same-sized gear teeth and the same change of fluid volume inside the cylinder, the V-type actuator has larger range of rotation but also coarse resolution, because small gear has larger gear ratio. 
– (Although the V-shape assembly also has limitation of maximum piston shaft length.)
- (geometric equation relating the )
**** Assume that all the elastic effect of the rolling diaphragm is negligible such that the change of the fluid volume inside one of the cylinder of the hydraulic actuator $\Delta V_c$  is related to the displacement of the piston shaft $\Delta h$  by:
    \Delta V_c = \pi r^2_c \Delta h		(1)
where $r_c$ is the inner radius of the cylinder. 
In ideal case where the fluid is incompressible and the volume of inside the long flexible tube is constant, $\Delta V_c$ is solely induced by the change of volume inside the hydraclic pump $\Delta V_p \propto \Delta l$ which is proportional to the displacement of the piston inside hydraulic pump $\Delta l$. 
Therefore, the displacement of the piston shaft $\Delta h$ of the actuator is also proportional to $\Delta l$ :
	    \Delta V_c = \pi r^2_c \Delta h
\implies    \Delta h \propto \Delta l	
	    \Delta h = k_t \Delta l			(2)
where $k_t$ is the input-output ratio (I-O ratio) of the piston shaft. 
For the case without backlash at the gear, the angular change of the gear $\Delta \theta$ is proportional to the displacement of the piston shaft $\Delta h$ and thus also proportional to $\Delta l$:
	    \Delta \theta \propto \Delta l		
\implies    \Delta \theta = k_g \Delta l		(3)
where $k_g$ is the I-O  ratio of the gear.
- (The proportionality in (2) and (3) vanishes if the fluid volume is not constant or backlash occurs.)
- (need more complicated model including fluid dynamics to explain the time delay?)
**** [The expected characteristics/advantages:, stroke and accuracy]
- fast response
- output torque

*** The MR-compatible robotic platform
**** The proposed hydraulic actuators are compactly assembled in a MR-compatible robotic platform depicted in Fig. , which provides effective steering (bending), fine advancement, rotation and coarse advancement of a catheter mounted on it. 
The design technical specifications of our current prototype are summarized in Table 1.
**** The steering and the advancement of the catheter are provided by two P-type actuators as depicted in Fig. . 
The platform tightly holds the steering wheel of the catheter and the catheter handle such that the gears of the two P-type actuators directly actuate the catheter with fine resolution and without backlash.
**** The rotation and the coarse advancement of the catheter are provided by two V-type hydraulic actuators as depicted in Fig. .
The V-type actuator is used instead of the P-type actuator because catheter may need larger range of rotation as mentioned before. 
The V-type actuators provide both the rotation and the coarse advancement via intermediate gears to magnify the range of motion and thus have coarser resolution than the steering and advancement and may encounter the problem of backlash.
- (How the specific requirements for EP are matched?)
- [Table of design parameters: dimension, components, DoF requirement, ranges of motion, resolution (or input-output ratios of each DOF), material name et al]

** Control interface (combine with B?)
*** Fig. depicts the schematic diagram for carrying out EP by the MR-compatible robotic platform.
- [Schematic diagram: including connections between motor drivers, valves, mcu, MRI scanner room, control rooms, etc…]
- [which components are in the MRI-scanner room and the control room?]
- [Fig: figure of the controller]
- [Description of how the EP is carried out by the user using the robot:]
  - [Surgeon uses controller to control the platform for cardiac ablation, according to the (real-time) MRI which reflects catheterization in 3D roadmap]
  - [the controller input is sent to the microprocessor in the control room to actuate robotic platform]

** Experimental Evalulations
*** To examine the applicability of the proposed design for EP, the robotic platform depicted in Fig. was constructed
- [Fig. of real robot, long flexible tubes, cylinder pump]
- Actuation experiments were conducted to evaluate the actuation performance in terms of time delay, precision (related to backlash) and operation speed, output torque
- MR-compatibility tests were also carried out to investigate the effects to MRI.

*** MR-compatibility test
- Image artifacts
- SNR analysis
- [Fig: depicting the zero-artifact using 1-2 significant MRI sequences]
- (actuation inside MRI scanner?)

*** Performance analysis
Specification
- resolution, speed, I/O ratios 
   depending on the resolution of the cylinder and I/O ratio
- output torque
- range of motion


**** Step response
- rise time, overshoot, settling time, time constant


**** Frequency response
- time delay
- bode plot

**** hysterysis and backlash


**** workspace analysis with catheter

** Discussion
*** Highlight the significant novelties - 1st MR-compatible robotic platform for EP
*** Definition/justification of our proposed performance indices, such as time consuming, efficiency
*** Contribution of this work. How it could be extended to other clinical applications?

** Conclusion
*** The first MR-compatible robot for EP
    - Efficient and effective actuation of rotation, advancement and bending
    - Other main features
    - ...
*** Future work
    - Extensible to other clinical applications/surgeries
    - Difficulty even using robot, and pave a way to our future work in regards of model-free catheter control
 
      

* paper draft for RAM
  :PROPERTIES:
  :Directory: file:~/Work/HKU/MRcompatible_platform/RAM
  :END:
  
  - try to pick out the most important message at every page

** Abstract - the 1st paragraph (100 words)

- one short paragraph
  - motivation/advantages using MRI in MIS
    - aim of this paper
      - motivate the use of MRI in robot-assisted MIS 
      - exploit MRI in robot-assisted MIS
      - how to incorporate MRI in robot-assisted MIS
      - present a MR-compatible robotic platform for Cardiac Electrophysiological (EP) that was demonstrated in the Surgical Robot Challenge

** Introduction - MRI-guided robot-assisted MIS (800 words)

- What is MIS and its advantages
  - brief description of MIS
  - small wound, faster recovery
  - requires high precision of tool manipulation within a relatively small, confined workspace
  - most surgeons currently conduct MIS based on pre-op MRI, intra-op 2D, rough images
    - depend on the experience of surgeons
  - example: EP in cardiac catheterization, deep brain stimulation (DBS) in neurosurgery

- what is MRI and the advantage of intra-operative MRI
  - brief description of intra-operative (Late gadolinium enhancement) T2-weighted MRI 
    - 
  - MRI provide better quality (intra-operative) images
    - better quality and high contrast images of soft tissue
    - monitoring the physiological and pathological change of region of interest during MIS
    - construction of roadmap for specific surgical goals
      - e.g. registering lesion targets on MR-images for EP treatment
      - e.g. in DBS treatment, planning of placing an electrode accurately at the subthalamic nucleus (STN) in the deep brain under stereotactic guidance.
  - example in EP:
    - enable intra-operative assessment of ablation location and progress
      - construction of cardiac roadmap [aliot2009ehra/hrs, nazarian2008feasibility]: registering lesion targets on MR-images for EP treatment
      - t2-weighted cardiac MRI [schmidt2009electroanatomic, peters2009t2]
      - edema [peters2009t2weighted] and scar tissue [ren2007apotential]
  - example in DBS:
    - fMRI/DT-MRI reveals critical structure related to the deep brain nuclei, the corticospinal tract, red nucleus and third nerve nucleus for planning of placing an electrode accurately at the subthalamic nucleus (STN) under stereotactic guidance [XXX].
    - 

- Technical difficulties of incorporating MRI in MIS
  - requires fast image processing 
    - image processing is computationally intensive: difficult to carry out fast enough to provide intra-operative image
    - realignment of exact, deformed physiological features to pre-planned roadmap
    - rigid image co-registration [ishihara2007mrievaluation] between the pre-and intra-op images would help compensate the 6D-offset due to patient positioning and motion, but rapid morphological changes cause inaccuracies.
    - non-rigid 3D image registrations [relan2011personalitzation, archip2007nonrigid] have been used in the conventional EP, but mostly applied only once after the EAM for improved integration between map and the pre-op roadmap
    - processing of non-rigid registrations is normally computationally intensive (>5sec)
  - requires special actuation method
    - tele-manipulate the surgical tools via robotic platform so that surgeons do not need to expose to high magnetic field 
    - conventional actuation method is usually not MR-compatible
  - requires sensors that can work inside MRI scanner
    - positional feedback
    - force feedback
  

- last paragraph sums up and connects to the next section
  -          


** The surgeon-robot close-loop (not good, to be changed) (2000 words)

- overview
  - 3 components in the close-loop: Image processing, mri-compatible actuation and sensory feedback
  - general setting in the MRI scanner room and the control room
  - schematic diagram

*** Intra-operative image processing
- intra-operative image registration
  - Image registration is the process of transforming different sets of data into one coordinate system. (from wiki)
  - data from multiple images, different sensors, times, depths, or viewpoints. (from wiki)
  - terminology: non-rigid image registration
    - especially to cope with deformation of object
      - deformation due to e.g. breathing, anatomical changes (e.g. brain shift)
  - intra-operative image registration: look for continuous mapping between pre-operative (pre-op) and intra-operative (intra-op) image
  - update high resolution pre-op image with rapidly acquired intra-op image
  - DD, transform/ operation in Lie’s group, continues and smooth manifold, all mathematic operations (e.g. composition rather than simple addition) become much more complicated
  - fig: merging high quality pre-op image and intra-op image

- objectives/advantages of intra-operative imaging
  - intra-operatively
  - describing continuous morphological changes of soft tissues 
  - instantly reveal effect of surgical actions
  - fused into and update roadmap 
  - smoothen the repeated workflow of surgical tool path planning 

- intensity-based (IB) and feature-based (FB) approach
  - IB: based on optical-flow, requires higher computation cost, less sensitive to image artifact
  - FB: based on feature correspondence, faster and simpler computation, larger error in matching the feature correspondence
  - thus IB is preferable if the fast enough computation is available

- High-performance computational architecture, enabling technology for fast image processing during surgery
  - GPU-based, higher floating computation throughput than multi-core CPU, highly parallelized design (hundreds of processing unit)
    - A 3D MR image comprising a large number of voxels can be “split” into smaller segments and processed on a multi-threaded architecture consisted of hundreds of stream processors
    - previous study demonstrated order of magnitude speed-up as compared to CPU
    - The growing trend of computation power is much faster than CPU    
  - FPGA-based computation, focus the design of dataflow program and pipelining
    - flexible architecture that optimization of dataflow and pipeline
    - customizable data format, enable trade-off between accuracy and performance
    - overcome memory bandwidth constraint of GPU, minimize memory transfer into/from processor 
    - enable parallelization and scalability
    - deterministic computation time
    - gradient computation as an example:
      - one output can be generated at every clock cycle
      - figure
  - explain the computation mechanism with fig
    - pros and cons 
  - several existing methods
    - pros and cons 

- Diffeomorphic demons registration
  - original demons approach [wang2005validation]
  - our previous work [kwok2014fpgabased,kwok2014mribased]
    - register RF ablation targets on cardiac roadmap for electrophysiology (EP)
    - < 3mm registration error
    - based on local intensity gradient
  - Diffeomorphic demons registration [vercauteren2007nonparametric,vercauteren2009diffeomorphic]
    - not only does it ensure preserving the topology of large deforming tissue structure, but it also allows for smooth forward and inverse transformation
    - thus guaranteeing tighter, more accurate alignment of ablation landmards and electro-anatomic mapping (EAM) contact points with the EP roadmap [vercauteren2009diffeomorphic]
    - both pre-op and intra-op image sets will have to be interpolated in a common region of Cartesian girds to calculate the intensity differences for processing the diffeomorphic demons; this induces larger number of pixel/voxels perations, amount of inlinked or non-coalesced memory access to be provessed.
    - state-of-art using GPU can achieve only 4-5 second computation [muyanozcelik2008fast,gu2010implementation]
  - matching/searching spectral correspondence to handle large deformation [lombaert2013spectral]
    - e.g. taking global scope of brain image
    - it is the state-of-art using CPUs that can achieve only 25 to 45 min


Algorithm 1: General Diffeomorphic Demons Framework
1. Input: Fixed image  and moving Image 
2. repeat until converge:
3. Compute update field  based on  and 
4. Apply fluid-like regularization 
5. Update velocity field  
6. Apply diffusion-like regularization 
7. Output: Transformation  from  to 


- virtual 3D environment construction
  - examples with figs




*** MRI-compatible actuation

- In addition to imaging issues, enhanced stability and adequate flexibility of robot-assisted surgical platform also poses increasing demand on intra-op MRI navigation.
- Considering the operation on delicate tissue, the robot system must has high accuracy and can be finely controlled, in other words, backlash should be minimized and it should be able to remain locked in its original position if any power failure or emergency stop happens.
- The workspace is tightly constrained inside the scanner bore. These all bring up the strict demands on compacted mechanical design of the robot. 
- Sterilization should also be taken into consideration, especially for the design of end effector.
- Actuators driven by oscillation of piezoelectric materials, such as ultrasonic motor, have been extensively applied (e.g. [XXX]) to be tailor-made for interventional MRI applications because of its high-fidelity dynamic accuracy. 

- Recent advanced designs was proposed to operate the piezoelectric motor electronics using direct digital synthesizers [XXX] in order to attenuate EM interference that will cause the image artifact. Even though the signal-to-noise ratio (SNR) is promising with <15% reduction, complex EM-shielded enclosure is required to surround on all sides of the motor drivers, thus degrading the motor compactness [XXX]. 
- The presence of electric current supplied from the external electrical source inevitably infringes the new standard of MR-safety [XXX]. 
- These disadvantages have naturally shifted the research focuses towards intrinsically MR-safe actuators driven by other energy sources, e.g. pressured fluid flow, instead of EM power [XXX]. 
- Compact actuation units allowing the robotic manipulation taking place inside the MRI bore is required for providing highly precise and reliable targeting of lesions located by the intra-op imaging. 
- To this end, various pneumatic/hydraulic actuators [XXX] have been designed, which are capable of operating in an MR environment, even inside the scanner, without adversely affecting MR image quality.

- a robotic platform that allows surgeons tele-manipulate surgical tools which are located in the MRI-scanner room
  - should have negligible effect to the MR image quality. 
  - must has high accuracy and can be finely controlled
    - e.g. backlash should be minimized and it should be able to remain locked in its original position if any power failure or emergency stop happens.
  - The workspace is tightly constrained inside the scanner bore. These all bring up the strict demands on compacted mechanical design of the robot.
  - Sterilization should also be taken into consideration
  - 

- recent advanced MR-compatible actuation methods 
  - ultrasound, piezoelectric
    - using direct digital synthesizers [shang2015piezoelectrically,hao2012amriguided] in order to attenuate EM interference that will cause the image artifact (piezoelectric)
    - Even though the signal-to-noise ratio (SNR) is promising with <15% reduction, complex EM-shielded enclosure is required to surround on all sides of the motor drivers, thus degrading the motor compactness [hao2012amriguided,bannan2015development].
    - The presence of electric current supplied from the external electrical source inevitably infringes the new standard of MR-safety [stoianovici2014mrisafe].
    - 
  - magnetic-driven (move to future work?)
    - [vartholomeos2011mripowered]
    - pros and cons

- pneumatic actuation
  - pros and cons
  - several examples

- Hydraulic actuation
  - O-ring vs rolling diaphragm
  - pros and cons


*** Sensory feedback 

- it is important to feedback the surgical tools' 3D positions that are defined in the same coordinate frame as the MR image's coordinate frame
  - the sensory feedback allows implementation of feedback control method
    - for more accurate manipulation of surgical tools
    - implementation of intuitive control-interface
    - to close the surgeon-robot loop
  - explain why the same coordinate frame should be used


- MR-conditional/safe sensors
  - kinematics sensors
    - active tracking unit for positional feedback
      - e.g. [wang2015realtime]
      - comprises small coils
      - connected with a receiver channel of the scanner via coaxial cables in order to measure MR gradient field.
      - The reveived coil signal is highly localized [galassi2015fast] and can be readily differentiated from the other coils' signal
      - thus enabling high-frame rate of tracking (≥40Hz)
      - The routing of the coaxial cables is required from the coil to the receiver interface [sarioglu2015anoptically]
      - the size and length of the cables have to be minimized for reduction of any EM interference
      - particularly challenging while operating larger numbers (>8) of active coil.
      - coil-to-channel electronic interface also has to be specifically designed for particular types of scanners only
    - semi-active tracking unit
      - the coil does not have to connect with the scanner receiver channel, but only act as an radio-frequency (RF) receiver and inductor in an isolated LC circuit that resonates with MR frequency ~63.8MHz or 123.5MHz, respectively, for 1.5T or 3T scanner either [rube2014wireless]
      - may require tedious LC tuning process to match the resonant frequency within tolerance of ±1MHz [galassi2015fast]
      - 3D coordinates matching of just three coils is complicated [galassi2015fast]
      - miniaturization to include commercial MR-safe capacitors is very challenging
	- the criteria for high quality factor (Q>50) that is inversely proportional to the circuit electrical resistance
	- high resistance that may generate excessive heat
      - only
  - list some other existing sensors if possible
    - e.g. forces sensor
      - some examples in the literature and their working principles
	- optical Fiber Bragg Grating (FBG)-based sensing unit to measure force [chen-mriconditional]
	- 
      - pros and cons

- image registration


*** Control interface

- A control interface that allows surgeons intuitively manipulate the surgical tools
  - within a 3D virtual environment constructed from intra-operative MR images
  - a fig of our control-interface
    - details to be discussed in the results section

- one of the key units in the interface is a method to control the robotic platform that actually manipulate the surgical tools for specific purposes
  - position control
    - example in literature
  - force control
    - example in literature
  - hybrid (position and force) control
    - example in literature
  - compensating physiological motion
    - example in literature

- control methods for rigid surgical tools and flexible surgical tools
  - very briefly explain the need of flexible surgical tools
  - rigid surgical tools
    - model-based method
      - example in literature
  - flexible surgical tools
    - model-free method 
      - example in literature
      

** An example - A robotic platform for cardiac electrophysiological interventions in the Surgical Robot Challenge (800 words)

- overview of our system
  - fig

- Image processing
  - FPGA-based computation
  - results
    - comp. time
    - figs
      - e.g. 3D figures, registered images

- Real-time positional feedback 
  - active tracking coil
    - specifications, fig
      - e.g. working frequency
  - results
    - accuracy

- The catheter robot
  - hydraulic transmission with rolling diaphragm 
    - design figs, number of DOF, function of each DOF
  - results
    - SNR test fig
    - response results

- The surgeon-robot interface
  - The model-free control method
    - real-time update of a Jacobian mapping defined between the desired Endoscopic displacement and control input of the robotic platform
      - control schematic diagram

- A left atrium phantom model that has characteristics closed to human physiological characteristics
  - explain why mimicking this(these) characteristic(s) is important
  - flexible atrium
  - custom-made pump
  - fig of the phantom
  - subject test result

** Discussion and Conclusions (800 words)
- current stage
  - what can be done now
  - limitations
  - examples of MRI-guided robotic platform
    - ours and others

- future directions
  - for improving for the close-loop, some preliminary results on 
    - imaging
    - Sensing
      - semi-active tracking
    - actuation
    - control interface
      - operational space control of continuum robot in 3D task space
      - enable autonomous control 
    - lab-based validation 
      - improvement on 3D printing technologies
  - some advance features
    - decision making, motion/path planning, more autonomous and/or intuitive control-interface

** Acknowledgments

** References



