* General info
  [[file:~/Work/HKU/Poster_corridor/]]

* notes
  
** TODO ask for figures
   ask chimlee for coil design figures
   ask martin or other for phantom figure

** TODO ask for conclusion text
   
* Task

** TODO submit poster
   DEADLINE: <2016-04-30 Fri>

* DONE Poster outline
  CLOSED: [2016-04-29 Fri 17:37] SCHEDULED: <2016-04-29 Fri 11:00-13:00>
** Title
   - High-performance Robot-assisted Systems for MRI-guided Cardiac Interventions * 
   - MRI-guided and Robot-assisted Technologies for Surgical Interventions
** Introduction
   - Magnetic resonance imaging (MRI) techniques
     - produce high-contrast images
     - enable/provide intra-operative, real-time assessment of lesion tissue
   - MRI-guided and Robot-assisted Systems enhances saftey and efficacy of surgical interventions
   - Examples of surgical interventions (omitted)
     - Cardiovascular electrophysiology (EP) 
     - Neurosurgery
   - Figure of good quality MR images
** Objectives
   1. Development of fast computing architecture for real-time MR image processing
   2. Development of high-performance, MR-conditional robotic platform
   3. Advanced control interface
   4. Validation of potential clinical advantages 
   5. Ultimate objective : Figure of integrated robotic system
      
** Methodology


*** Fast MR image registration (Objective 1)
    - Field-Programmable Gate Arrays (FPGAs)-based computing architecture for accurate localization of ablation targets
    - Figure
*** MR-compatible actuation and sensing (Objective 2)
    1. design: MR-compatible pnuematic stepper motor 
       - add chimlee for more design figure of coil
    2. Micro coil sensor for real-time positional tracking
       - figure
*** Control interface for catheterization (Objective 3)
    - Novel model-free control for flexible continuum robots
    - Visual-motor alignment of operator’s motion in virtual endoscopic fly-through view
	
*** Validation (Objective 4)
    1. Development of dynamic left atrial phantom model for lab-based validation
        - phantom model figure, currently copied from video, to be modified
    2. Computer-simulated RFA test
	  - Subject test: volunteers were invited to manually maneuver an EP catheter to target the virtual catheter tip to the lesion targets
	  - validate the potential benefits of providing enhanced guidance in the form of haptic and visual feedback
    3. MRI-based validation
       1. Test of FPGA-based MR image registration
	  - figure
       2. Signal-to-noise (SNR) test
	  - figure

** Results
*** MR image registration
    FPGA-based computation enables fast (<0.1s) MR registration

*** MR-compatible robotic platform
Figure of the robotic platform with pneumatic/hydraulic actuators installed (the above figure to be replaced if not to be disclosed)

*** Control interface
Enhancement of control performance has been proven in subject test of ablation task
*** Validation
    1. Lab-based validation
       1. Computer-simulated RFA test -- the same test in model-free control?
       2. Figure of the phantom model
    2. MRI-based validation
       1. SNR images


*** Visual, position and haptic sensing (omitted)
    1. Micro coil
       tracking accuracy +/- 0.5mm at 40Hz
    2. (optional?) FBG-based sensing units
*** Model-free kinematics control interface for flexible catheter (omitted)
    - Ablation performances are found to be improved significantly with the visual-motor realignment updated in real time
    - Subject found easier to complete the simulated ablation task with the aid of our model-free robotic control
    - Both accuracy and effciency of robotic catheterization are enhanced
    - Quantitive data needed
** Conclusions/outlooks
To be revised at last
*** Prospective impacts of using robotic catheter for MRI-guided EP:
    1. Decrease chances of post-precedural arrhythmia recurrence
    2. Increase safety of catheter navigation
       - Thereby decreasing the rates of nerve damage, esophageal fistula creation, pulmonary-vein stenosis and stroke, the major risks of EP procedures
    3. Enhancing the dexterity of catheter control facilitating better treatments for more complex arrhythmias
    4. Serve as bencmark for the design and integration of MR-conditional robotic devices
       - Open a new dimension for other procedures, such as breast biopsy neurosurgery and prostate intervention that can also benefit from intra-op MRI
*** Something more to say....






* Materials
** Proposal

** Hamlyn Symposium video
   [[file:~/Work/HKU/Hamlyn_symposium_2016/][(Directory)]]
*** Video captions:
**** Why MRI-guided Catheterization?
     - Intra-operative MRI provides fast and high-contrast soft tissue images withouth emitting radiation
     - During ablation, physiological change of tissue can be well-distinguished by late gadolinium enhancement T2-weighted MRI (Khomolvski et al. Circulation 2014)
     - Physician can readily monitor the catheter ablation progress and hence reduce the chance of arrhythmias reoccurrence
**** MR-safe actuations
     - The MR-conditional robot comprises components made of MR-conditional materials
     - The robot actuation is designed to be driven by hydraulic power transmitted from the motors in control room
**** Catheter Manipulation
**** Tracking coil
     - Real-time MR-based positional tracking units offer accurate alignment between the catheter and the MR images
     - tracking accuracy +/- 0.5mm at 40Hz
**** Human machine interface
     - A 3D motion inut device is used to command the 3-DOF manipulation of EP ablation catheter
     - The online updated Jacobian allows instant realignment between the endoscopic view and the input left-and-right motion. The realignment is continuously updated/estimated in real time using a model-free controller
     - The updated Jacobian allows intuitive maneuvering of catheter aiming at the lesion targets based on the endoscopic view
     - Simlated tasks were conducted, in which ablation has to be applied precisely on the target lesions
     - Ablation performances are found to be improved significantly with the visual-motor realignment updated in real time
     - Subject found easier to complete the simulated ablation task with the aid of our model-free robotic control
     - Both accuracy and effciency of robotic catheterization are enhanced
     - Dynamic left atrial phantom model will be incorporated in our future validation
**** Prospective impacts of using robotic catheter for MRI-guided EP:
     1) Decrease chances of post-precedural arrhythmia recurrence
     2) Increase safety of catheter navigation
	- Thereby decreasing the rates of nerve damage, esophageal fistula creation, pulmonary-vein stenosis and stroke, the major risks of EP procedures
     3) Enhancing the dexterity of catheter control facilitating better treatments for more complex arrhythmias
     4) Serve as bencmark for the design and integration of MR-conditional robotic devices
	- Open a new dimension for other procedures, such as breast biopsy neurosurgery and prostate intervention that can also benefit from intra-op MRI
	


** IROS posters
   
** ziyan's ppt
   [[file:~/Work/HKU/Poster_corridor/][ppt location]]
