* General info
  [[file:~/Work/HKU/Poster_corridor/]]

* notes
  
* Task

** DONE revise corridor poster
   CLOSED: [2016-10-12 Wed 11:02] SCHEDULED: <2016-10-08 Sat>
   - State "DONE"       from "WAITING"    [2016-10-12 Wed 11:02]
   - State "WAITING"    from "TODO"       [2016-10-08 Sat 16:06] \\
     waiting for kawai's revision
*** according to information of RAM
    [[file:~/Work/HKU/MRcompatible_platform/RAM/][file:~/Work/HKU/MRcompatible_platform/RAM/]]

* Poster outline
** Title
   - High-performance Robot-assisted Systems for MRI-guided Cardiac Interventions
   - MRI-guided and Robot-assisted Technologies for Surgical Interventions
   - Development of robotic platform for MRI-guided Intra-cardiac Catheterization * 
** Introduction
   - Intra-cardiac Catheterization 
     - a thin (<3mm), long (~1.5m) catheter is inserted from the femoral vein to the heart chamber for surgical intervention
     - for treatment of cardiovascular diseases such as arryhythmia 
   - Magnetic Resonance Imaging (MRI)
     - provide high-contrast images for cardiovascular tissue
     - enable construction of 3D cardiac roadmap
   - MRI-guided and robot-assisted system can
     - enhance safety and efficacy to manipulate the long flexible catheter 
     - avoid exposing patients and clinicians to harmful radiation from X-ray and computed tomography (CT) 
   - No existing commercial robotic catheterization platform is MR-safe/conditional 
** Objectives
   - Development of 
     - Fast computing architecture for Intra-operative MRI
     - High-performance and MR-conditional robotic platform
     - Positional sensing of catheter in MRI scanner
     - Intuitive control interface for effective catheterization
      
** Methodology
   - Intra-operative image processing
     - Diffeomorphic Demons image registration
     - High performance Field-Programmable Gate Arrays (FPGAs)-based computation 

   - MR-safe actuation units
     - Fabrication using MR-safe (non-ferromagnetic) material by 3D-printing technologies
     - Master-slave pneumatic/hydraulic transmission to ensure negligible electromagnetic interference to MRI

   - Tracking coils for real-time positional feedback in MRI 
     - allows visualization of the catheter configuration in MR images
     - enables implementation of robotic feedback control of the catheter

   - Control interface for catheterization
     - Novel model-free control for flexible continuum robots
     - Visual-motor alignment of operator’s motion in virtual endoscopic view
	
** Research accomplishments
   - Computation using FPGAs is 25 time faster than state-of-the-art GPUs.
   - A catheter robot with the following features:
     - Hydraulic actuation effectively transmit power for long distance (at least 10m) with small hysterysis (<1.5 degree)
     - Rolling diagram reduces friction thus enhances efficiency
     - A clinically-used catheter can be easily plugged-in
   - Small and flexible tracking coils can provide accurate (+/- 0.5mm) and fast positional feedback (40Hz)
   - Maximum Signal-to-noise (SNR) loss in MR image is within 2% only when robot is in motion.
   - More accurate and faster robot-assisted catheterization using the control interface has been proven in a subject test of ablation task

** Conclusions/outlooks
   - The presented work is the first MR-conditional robotic platform for cardiac catheterization, which can be serve as benchmark for extension to other MRI-guided surgical procedures such as breast biopsy, neurosurgery, and prostate intervention. 

To be revised at last
*** Prospective impacts of using robotic catheter for MRI-guided EP:
    1. Decrease chances of post-precedural arrhythmia recurrence
    2. Increase safety of catheter navigation
       - Thereby decreasing the rates of nerve damage, esophageal fistula creation, pulmonary-vein stenosis and stroke, the major risks of EP procedures
    3. Enhancing the dexterity of catheter control facilitating better treatments for more complex arrhythmias
    4. Serve as benchmark for the design and integration of MR-conditional robotic devices
       - Open a new dimension for other procedures, such as breast biopsy neurosurgery and prostate intervention that can also benefit from intra-op MRI
*** Something more to say....







** Introduction 
   - Magnetic resonance imaging (MRI) techniques
     - produce high-contrast images
     - enable/provide intra-operative 

** Methodology

** Objectives

** Research accomplishments

** Conclusions/outlooks


* Materials
** Proposal

** Hamlyn Symposium video
   [[file:~/Work/HKU/Hamlyn_symposium_2016/][(Directory)]]
*** Video captions:
**** Why MRI-guided Catheterization?
     - Intra-operative MRI provides fast and high-contrast soft tissue images withouth emitting radiation
     - During ablation, physiological change of tissue can be well-distinguished by late gadolinium enhancement T2-weighted MRI (Khomolvski et al. Circulation 2014)
     - Physician can readily monitor the catheter ablation progress and hence reduce the chance of arrhythmias reoccurrence
**** MR-safe actuations
     - The MR-conditional robot comprises components made of MR-conditional materials
     - The robot actuation is designed to be driven by hydraulic power transmitted from the motors in control room
**** Catheter Manipulation
**** Tracking coil
     - Real-time MR-based positional tracking units offer accurate alignment between the catheter and the MR images
     - tracking accuracy +/- 0.5mm at 40Hz
**** Human machine interface
     - A 3D motion inut device is used to command the 3-DOF manipulation of EP ablation catheter
     - The online updated Jacobian allows instant realignment between the endoscopic view and the input left-and-right motion. The realignment is continuously updated/estimated in real time using a model-free controller
     - The updated Jacobian allows intuitive maneuvering of catheter aiming at the lesion targets based on the endoscopic view
     - Simlated tasks were conducted, in which ablation has to be applied precisely on the target lesions
     - Ablation performances are found to be improved significantly with the visual-motor realignment updated in real time
     - Subject found easier to complete the simulated ablation task with the aid of our model-free robotic control
     - Both accuracy and effciency of robotic catheterization are enhanced
     - Dynamic left atrial phantom model will be incorporated in our future validation
**** Prospective impacts of using robotic catheter for MRI-guided EP:
     1) Decrease chances of post-precedural arrhythmia recurrence
     2) Increase safety of catheter navigation
	- Thereby decreasing the rates of nerve damage, esophageal fistula creation, pulmonary-vein stenosis and stroke, the major risks of EP procedures
     3) Enhancing the dexterity of catheter control facilitating better treatments for more complex arrhythmias
     4) Serve as bencmark for the design and integration of MR-conditional robotic devices
	- Open a new dimension for other procedures, such as breast biopsy neurosurgery and prostate intervention that can also benefit from intra-op MRI
	


** IROS posters
   
** ziyan's ppt
   [[file:~/Work/HKU/Poster_corridor/][ppt location]]
